// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: service/user/pb/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Area          string                 `protobuf:"bytes,5,opt,name=area,proto3" json:"area,omitempty"`
	Gender        string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Points        int32                  `protobuf:"varint,7,opt,name=points,proto3" json:"points,omitempty"`
	Role          string                 `protobuf:"bytes,8,opt,name=role,proto3" json:"role,omitempty"` // user / volunteer / admin
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_service_user_pb_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *UserInfo) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UserInfo) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *UserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_service_user_pb_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_service_user_pb_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_service_user_pb_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_service_user_pb_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_service_user_pb_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LogoutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResp) Reset() {
	*x = LogoutResp{}
	mi := &file_service_user_pb_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResp) ProtoMessage() {}

func (x *LogoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResp.ProtoReflect.Descriptor instead.
func (*LogoutResp) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{6}
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_service_user_pb_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserInfoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	mi := &file_service_user_pb_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserInfoResp) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Area          string                 `protobuf:"bytes,5,opt,name=area,proto3" json:"area,omitempty"`
	Gender        string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	ServiceTypes  []string               `protobuf:"bytes,7,rep,name=service_types,json=serviceTypes,proto3" json:"service_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoReq) Reset() {
	*x = UpdateUserInfoReq{}
	mi := &file_service_user_pb_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoReq) ProtoMessage() {}

func (x *UpdateUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoReq) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserInfoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserInfoReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserInfoReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserInfoReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUserInfoReq) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *UpdateUserInfoReq) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateUserInfoReq) GetServiceTypes() []string {
	if x != nil {
		return x.ServiceTypes
	}
	return nil
}

type UpdateUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoResp) Reset() {
	*x = UpdateUserInfoResp{}
	mi := &file_service_user_pb_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoResp) ProtoMessage() {}

func (x *UpdateUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoResp.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoResp) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{10}
}

type ChangePasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordReq) Reset() {
	*x = ChangePasswordReq{}
	mi := &file_service_user_pb_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordReq) ProtoMessage() {}

func (x *ChangePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordReq.ProtoReflect.Descriptor instead.
func (*ChangePasswordReq) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{11}
}

func (x *ChangePasswordReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChangePasswordReq) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResp) Reset() {
	*x = ChangePasswordResp{}
	mi := &file_service_user_pb_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResp) ProtoMessage() {}

func (x *ChangePasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResp.ProtoReflect.Descriptor instead.
func (*ChangePasswordResp) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{12}
}

type GetPointsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPointsReq) Reset() {
	*x = GetPointsReq{}
	mi := &file_service_user_pb_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPointsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointsReq) ProtoMessage() {}

func (x *GetPointsReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointsReq.ProtoReflect.Descriptor instead.
func (*GetPointsReq) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetPointsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetPointsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        int32                  `protobuf:"varint,1,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPointsResp) Reset() {
	*x = GetPointsResp{}
	mi := &file_service_user_pb_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPointsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointsResp) ProtoMessage() {}

func (x *GetPointsResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointsResp.ProtoReflect.Descriptor instead.
func (*GetPointsResp) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetPointsResp) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type AddPointsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Delta         int32                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPointsReq) Reset() {
	*x = AddPointsReq{}
	mi := &file_service_user_pb_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPointsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPointsReq) ProtoMessage() {}

func (x *AddPointsReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPointsReq.ProtoReflect.Descriptor instead.
func (*AddPointsReq) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{15}
}

func (x *AddPointsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddPointsReq) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *AddPointsReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AddPointsReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type AddPointsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewTotal      int32                  `protobuf:"varint,1,opt,name=new_total,json=newTotal,proto3" json:"new_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPointsResp) Reset() {
	*x = AddPointsResp{}
	mi := &file_service_user_pb_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPointsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPointsResp) ProtoMessage() {}

func (x *AddPointsResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPointsResp.ProtoReflect.Descriptor instead.
func (*AddPointsResp) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{16}
}

func (x *AddPointsResp) GetNewTotal() int32 {
	if x != nil {
		return x.NewTotal
	}
	return 0
}

type ListPointLogsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPointLogsReq) Reset() {
	*x = ListPointLogsReq{}
	mi := &file_service_user_pb_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPointLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPointLogsReq) ProtoMessage() {}

func (x *ListPointLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPointLogsReq.ProtoReflect.Descriptor instead.
func (*ListPointLogsReq) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{17}
}

func (x *ListPointLogsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListPointLogsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPointLogsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PointLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Delta         int32                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Balance       int32                  `protobuf:"varint,5,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointLog) Reset() {
	*x = PointLog{}
	mi := &file_service_user_pb_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointLog) ProtoMessage() {}

func (x *PointLog) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointLog.ProtoReflect.Descriptor instead.
func (*PointLog) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{18}
}

func (x *PointLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PointLog) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *PointLog) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PointLog) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PointLog) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *PointLog) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListPointLogsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*PointLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPointLogsResp) Reset() {
	*x = ListPointLogsResp{}
	mi := &file_service_user_pb_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPointLogsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPointLogsResp) ProtoMessage() {}

func (x *ListPointLogsResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPointLogsResp.ProtoReflect.Descriptor instead.
func (*ListPointLogsResp) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{19}
}

func (x *ListPointLogsResp) GetLogs() []*PointLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ListPointLogsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type NotificationSettings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskNotify     bool                   `protobuf:"varint,1,opt,name=task_notify,json=taskNotify,proto3" json:"task_notify,omitempty"`
	AdoptionNotify bool                   `protobuf:"varint,2,opt,name=adoption_notify,json=adoptionNotify,proto3" json:"adoption_notify,omitempty"`
	PointsNotify   bool                   `protobuf:"varint,3,opt,name=points_notify,json=pointsNotify,proto3" json:"points_notify,omitempty"`
	SystemNotify   bool                   `protobuf:"varint,4,opt,name=system_notify,json=systemNotify,proto3" json:"system_notify,omitempty"`
	MessageNotify  bool                   `protobuf:"varint,5,opt,name=message_notify,json=messageNotify,proto3" json:"message_notify,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationSettings) Reset() {
	*x = NotificationSettings{}
	mi := &file_service_user_pb_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationSettings) ProtoMessage() {}

func (x *NotificationSettings) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationSettings.ProtoReflect.Descriptor instead.
func (*NotificationSettings) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{20}
}

func (x *NotificationSettings) GetTaskNotify() bool {
	if x != nil {
		return x.TaskNotify
	}
	return false
}

func (x *NotificationSettings) GetAdoptionNotify() bool {
	if x != nil {
		return x.AdoptionNotify
	}
	return false
}

func (x *NotificationSettings) GetPointsNotify() bool {
	if x != nil {
		return x.PointsNotify
	}
	return false
}

func (x *NotificationSettings) GetSystemNotify() bool {
	if x != nil {
		return x.SystemNotify
	}
	return false
}

func (x *NotificationSettings) GetMessageNotify() bool {
	if x != nil {
		return x.MessageNotify
	}
	return false
}

type GetNotificationSettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationSettingsReq) Reset() {
	*x = GetNotificationSettingsReq{}
	mi := &file_service_user_pb_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationSettingsReq) ProtoMessage() {}

func (x *GetNotificationSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationSettingsReq.ProtoReflect.Descriptor instead.
func (*GetNotificationSettingsReq) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{21}
}

func (x *GetNotificationSettingsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetNotificationSettingsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *NotificationSettings  `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationSettingsResp) Reset() {
	*x = GetNotificationSettingsResp{}
	mi := &file_service_user_pb_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationSettingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationSettingsResp) ProtoMessage() {}

func (x *GetNotificationSettingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationSettingsResp.ProtoReflect.Descriptor instead.
func (*GetNotificationSettingsResp) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{22}
}

func (x *GetNotificationSettingsResp) GetSettings() *NotificationSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateNotificationSettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Settings      *NotificationSettings  `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationSettingsReq) Reset() {
	*x = UpdateNotificationSettingsReq{}
	mi := &file_service_user_pb_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationSettingsReq) ProtoMessage() {}

func (x *UpdateNotificationSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationSettingsReq.ProtoReflect.Descriptor instead.
func (*UpdateNotificationSettingsReq) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateNotificationSettingsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateNotificationSettingsReq) GetSettings() *NotificationSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateNotificationSettingsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationSettingsResp) Reset() {
	*x = UpdateNotificationSettingsResp{}
	mi := &file_service_user_pb_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationSettingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationSettingsResp) ProtoMessage() {}

func (x *UpdateNotificationSettingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationSettingsResp.ProtoReflect.Descriptor instead.
func (*UpdateNotificationSettingsResp) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{24}
}

type SubmitFeedbackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FeedbackType  string                 `protobuf:"bytes,2,opt,name=feedback_type,json=feedbackType,proto3" json:"feedback_type,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Contact       string                 `protobuf:"bytes,4,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFeedbackReq) Reset() {
	*x = SubmitFeedbackReq{}
	mi := &file_service_user_pb_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFeedbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFeedbackReq) ProtoMessage() {}

func (x *SubmitFeedbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFeedbackReq.ProtoReflect.Descriptor instead.
func (*SubmitFeedbackReq) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{25}
}

func (x *SubmitFeedbackReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmitFeedbackReq) GetFeedbackType() string {
	if x != nil {
		return x.FeedbackType
	}
	return ""
}

func (x *SubmitFeedbackReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SubmitFeedbackReq) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

type SubmitFeedbackResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackId    int64                  `protobuf:"varint,1,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFeedbackResp) Reset() {
	*x = SubmitFeedbackResp{}
	mi := &file_service_user_pb_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFeedbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFeedbackResp) ProtoMessage() {}

func (x *SubmitFeedbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_pb_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFeedbackResp.ProtoReflect.Descriptor instead.
func (*SubmitFeedbackResp) Descriptor() ([]byte, []int) {
	return file_service_user_pb_user_proto_rawDescGZIP(), []int{26}
}

func (x *SubmitFeedbackResp) GetFeedbackId() int64 {
	if x != nil {
		return x.FeedbackId
	}
	return 0
}

var File_service_user_pb_user_proto protoreflect.FileDescriptor

const file_service_user_pb_user_proto_rawDesc = "" +
	"\n" +
	"\x1aservice/user/pb/user.proto\x12\x04user\"\xdb\x01\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04area\x18\x05 \x01(\tR\x04area\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12\x16\n" +
	"\x06points\x18\a \x01(\x05R\x06points\x12\x12\n" +
	"\x04role\x18\b \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\"[\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"=\n" +
	"\fRegisterResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\":\n" +
	"\tLoginResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"$\n" +
	"\tLogoutReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\f\n" +
	"\n" +
	"LogoutResp\")\n" +
	"\x0eGetUserInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"5\n" +
	"\x0fGetUserInfoResp\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\"\xc7\x01\n" +
	"\x11UpdateUserInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04area\x18\x05 \x01(\tR\x04area\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12#\n" +
	"\rservice_types\x18\a \x03(\tR\fserviceTypes\"\x14\n" +
	"\x12UpdateUserInfoResp\"r\n" +
	"\x11ChangePasswordReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"\x14\n" +
	"\x12ChangePasswordResp\"'\n" +
	"\fGetPointsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"'\n" +
	"\rGetPointsResp\x12\x16\n" +
	"\x06points\x18\x01 \x01(\x05R\x06points\"n\n" +
	"\fAddPointsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x05R\x05delta\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\",\n" +
	"\rAddPointsResp\x12\x1b\n" +
	"\tnew_total\x18\x01 \x01(\x05R\bnewTotal\"S\n" +
	"\x10ListPointLogsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"\x9a\x01\n" +
	"\bPointLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x05R\x05delta\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x05R\abalance\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"M\n" +
	"\x11ListPointLogsResp\x12\"\n" +
	"\x04logs\x18\x01 \x03(\v2\x0e.user.PointLogR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xd1\x01\n" +
	"\x14NotificationSettings\x12\x1f\n" +
	"\vtask_notify\x18\x01 \x01(\bR\n" +
	"taskNotify\x12'\n" +
	"\x0fadoption_notify\x18\x02 \x01(\bR\x0eadoptionNotify\x12#\n" +
	"\rpoints_notify\x18\x03 \x01(\bR\fpointsNotify\x12#\n" +
	"\rsystem_notify\x18\x04 \x01(\bR\fsystemNotify\x12%\n" +
	"\x0emessage_notify\x18\x05 \x01(\bR\rmessageNotify\"5\n" +
	"\x1aGetNotificationSettingsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"U\n" +
	"\x1bGetNotificationSettingsResp\x126\n" +
	"\bsettings\x18\x01 \x01(\v2\x1a.user.NotificationSettingsR\bsettings\"p\n" +
	"\x1dUpdateNotificationSettingsReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x126\n" +
	"\bsettings\x18\x02 \x01(\v2\x1a.user.NotificationSettingsR\bsettings\" \n" +
	"\x1eUpdateNotificationSettingsResp\"\x85\x01\n" +
	"\x11SubmitFeedbackReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12#\n" +
	"\rfeedback_type\x18\x02 \x01(\tR\ffeedbackType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x18\n" +
	"\acontact\x18\x04 \x01(\tR\acontact\"5\n" +
	"\x12SubmitFeedbackResp\x12\x1f\n" +
	"\vfeedback_id\x18\x01 \x01(\x03R\n" +
	"feedbackId2\x99\x06\n" +
	"\vUserService\x121\n" +
	"\bRegister\x12\x11.user.RegisterReq\x1a\x12.user.RegisterResp\x12(\n" +
	"\x05Login\x12\x0e.user.LoginReq\x1a\x0f.user.LoginResp\x12+\n" +
	"\x06Logout\x12\x0f.user.LogoutReq\x1a\x10.user.LogoutResp\x12:\n" +
	"\vGetUserInfo\x12\x14.user.GetUserInfoReq\x1a\x15.user.GetUserInfoResp\x12C\n" +
	"\x0eUpdateUserInfo\x12\x17.user.UpdateUserInfoReq\x1a\x18.user.UpdateUserInfoResp\x12C\n" +
	"\x0eChangePassword\x12\x17.user.ChangePasswordReq\x1a\x18.user.ChangePasswordResp\x124\n" +
	"\tGetPoints\x12\x12.user.GetPointsReq\x1a\x13.user.GetPointsResp\x124\n" +
	"\tAddPoints\x12\x12.user.AddPointsReq\x1a\x13.user.AddPointsResp\x12@\n" +
	"\rListPointLogs\x12\x16.user.ListPointLogsReq\x1a\x17.user.ListPointLogsResp\x12^\n" +
	"\x17GetNotificationSettings\x12 .user.GetNotificationSettingsReq\x1a!.user.GetNotificationSettingsResp\x12g\n" +
	"\x1aUpdateNotificationSettings\x12#.user.UpdateNotificationSettingsReq\x1a$.user.UpdateNotificationSettingsResp\x12C\n" +
	"\x0eSubmitFeedback\x12\x17.user.SubmitFeedbackReq\x1a\x18.user.SubmitFeedbackRespB3Z1github.com/luyb177/meow-nook/service/user/pb/userb\x06proto3"

var (
	file_service_user_pb_user_proto_rawDescOnce sync.Once
	file_service_user_pb_user_proto_rawDescData []byte
)

func file_service_user_pb_user_proto_rawDescGZIP() []byte {
	file_service_user_pb_user_proto_rawDescOnce.Do(func() {
		file_service_user_pb_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_user_pb_user_proto_rawDesc), len(file_service_user_pb_user_proto_rawDesc)))
	})
	return file_service_user_pb_user_proto_rawDescData
}

var file_service_user_pb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_service_user_pb_user_proto_goTypes = []any{
	(*UserInfo)(nil),                       // 0: user.UserInfo
	(*RegisterReq)(nil),                    // 1: user.RegisterReq
	(*RegisterResp)(nil),                   // 2: user.RegisterResp
	(*LoginReq)(nil),                       // 3: user.LoginReq
	(*LoginResp)(nil),                      // 4: user.LoginResp
	(*LogoutReq)(nil),                      // 5: user.LogoutReq
	(*LogoutResp)(nil),                     // 6: user.LogoutResp
	(*GetUserInfoReq)(nil),                 // 7: user.GetUserInfoReq
	(*GetUserInfoResp)(nil),                // 8: user.GetUserInfoResp
	(*UpdateUserInfoReq)(nil),              // 9: user.UpdateUserInfoReq
	(*UpdateUserInfoResp)(nil),             // 10: user.UpdateUserInfoResp
	(*ChangePasswordReq)(nil),              // 11: user.ChangePasswordReq
	(*ChangePasswordResp)(nil),             // 12: user.ChangePasswordResp
	(*GetPointsReq)(nil),                   // 13: user.GetPointsReq
	(*GetPointsResp)(nil),                  // 14: user.GetPointsResp
	(*AddPointsReq)(nil),                   // 15: user.AddPointsReq
	(*AddPointsResp)(nil),                  // 16: user.AddPointsResp
	(*ListPointLogsReq)(nil),               // 17: user.ListPointLogsReq
	(*PointLog)(nil),                       // 18: user.PointLog
	(*ListPointLogsResp)(nil),              // 19: user.ListPointLogsResp
	(*NotificationSettings)(nil),           // 20: user.NotificationSettings
	(*GetNotificationSettingsReq)(nil),     // 21: user.GetNotificationSettingsReq
	(*GetNotificationSettingsResp)(nil),    // 22: user.GetNotificationSettingsResp
	(*UpdateNotificationSettingsReq)(nil),  // 23: user.UpdateNotificationSettingsReq
	(*UpdateNotificationSettingsResp)(nil), // 24: user.UpdateNotificationSettingsResp
	(*SubmitFeedbackReq)(nil),              // 25: user.SubmitFeedbackReq
	(*SubmitFeedbackResp)(nil),             // 26: user.SubmitFeedbackResp
}
var file_service_user_pb_user_proto_depIdxs = []int32{
	0,  // 0: user.GetUserInfoResp.user:type_name -> user.UserInfo
	18, // 1: user.ListPointLogsResp.logs:type_name -> user.PointLog
	20, // 2: user.GetNotificationSettingsResp.settings:type_name -> user.NotificationSettings
	20, // 3: user.UpdateNotificationSettingsReq.settings:type_name -> user.NotificationSettings
	1,  // 4: user.UserService.Register:input_type -> user.RegisterReq
	3,  // 5: user.UserService.Login:input_type -> user.LoginReq
	5,  // 6: user.UserService.Logout:input_type -> user.LogoutReq
	7,  // 7: user.UserService.GetUserInfo:input_type -> user.GetUserInfoReq
	9,  // 8: user.UserService.UpdateUserInfo:input_type -> user.UpdateUserInfoReq
	11, // 9: user.UserService.ChangePassword:input_type -> user.ChangePasswordReq
	13, // 10: user.UserService.GetPoints:input_type -> user.GetPointsReq
	15, // 11: user.UserService.AddPoints:input_type -> user.AddPointsReq
	17, // 12: user.UserService.ListPointLogs:input_type -> user.ListPointLogsReq
	21, // 13: user.UserService.GetNotificationSettings:input_type -> user.GetNotificationSettingsReq
	23, // 14: user.UserService.UpdateNotificationSettings:input_type -> user.UpdateNotificationSettingsReq
	25, // 15: user.UserService.SubmitFeedback:input_type -> user.SubmitFeedbackReq
	2,  // 16: user.UserService.Register:output_type -> user.RegisterResp
	4,  // 17: user.UserService.Login:output_type -> user.LoginResp
	6,  // 18: user.UserService.Logout:output_type -> user.LogoutResp
	8,  // 19: user.UserService.GetUserInfo:output_type -> user.GetUserInfoResp
	10, // 20: user.UserService.UpdateUserInfo:output_type -> user.UpdateUserInfoResp
	12, // 21: user.UserService.ChangePassword:output_type -> user.ChangePasswordResp
	14, // 22: user.UserService.GetPoints:output_type -> user.GetPointsResp
	16, // 23: user.UserService.AddPoints:output_type -> user.AddPointsResp
	19, // 24: user.UserService.ListPointLogs:output_type -> user.ListPointLogsResp
	22, // 25: user.UserService.GetNotificationSettings:output_type -> user.GetNotificationSettingsResp
	24, // 26: user.UserService.UpdateNotificationSettings:output_type -> user.UpdateNotificationSettingsResp
	26, // 27: user.UserService.SubmitFeedback:output_type -> user.SubmitFeedbackResp
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_service_user_pb_user_proto_init() }
func file_service_user_pb_user_proto_init() {
	if File_service_user_pb_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_user_pb_user_proto_rawDesc), len(file_service_user_pb_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_user_pb_user_proto_goTypes,
		DependencyIndexes: file_service_user_pb_user_proto_depIdxs,
		MessageInfos:      file_service_user_pb_user_proto_msgTypes,
	}.Build()
	File_service_user_pb_user_proto = out.File
	file_service_user_pb_user_proto_goTypes = nil
	file_service_user_pb_user_proto_depIdxs = nil
}
