// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: adoption.proto

package server

import (
	"context"

	"github.com/luyb177/meow-nook/service/adoption/internal/logic"
	"github.com/luyb177/meow-nook/service/adoption/internal/svc"
	"github.com/luyb177/meow-nook/service/adoption/pb/adoption/v1"
)

type AdoptionServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedAdoptionServiceServer
}

func NewAdoptionServiceServer(svcCtx *svc.ServiceContext) *AdoptionServiceServer {
	return &AdoptionServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AdoptionServiceServer) ApplyAdoption(ctx context.Context, in *v1.ApplyAdoptionReq) (*v1.ApplyAdoptionResp, error) {
	l := logic.NewApplyAdoptionLogic(ctx, s.svcCtx)
	return l.ApplyAdoption(in)
}

func (s *AdoptionServiceServer) ReviewApplication(ctx context.Context, in *v1.ReviewApplicationReq) (*v1.ReviewApplicationResp, error) {
	l := logic.NewReviewApplicationLogic(ctx, s.svcCtx)
	return l.ReviewApplication(in)
}

func (s *AdoptionServiceServer) GetApplication(ctx context.Context, in *v1.GetApplicationReq) (*v1.GetApplicationResp, error) {
	l := logic.NewGetApplicationLogic(ctx, s.svcCtx)
	return l.GetApplication(in)
}

func (s *AdoptionServiceServer) ListApplications(ctx context.Context, in *v1.ListApplicationsReq) (*v1.ListApplicationsResp, error) {
	l := logic.NewListApplicationsLogic(ctx, s.svcCtx)
	return l.ListApplications(in)
}

func (s *AdoptionServiceServer) SubmitFollowUp(ctx context.Context, in *v1.SubmitFollowUpReq) (*v1.SubmitFollowUpResp, error) {
	l := logic.NewSubmitFollowUpLogic(ctx, s.svcCtx)
	return l.SubmitFollowUp(in)
}

func (s *AdoptionServiceServer) ListFollowUps(ctx context.Context, in *v1.ListFollowUpsReq) (*v1.ListFollowUpsResp, error) {
	l := logic.NewListFollowUpsLogic(ctx, s.svcCtx)
	return l.ListFollowUps(in)
}
