// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: task.proto

package taskservice

import (
	"context"

	"github.com/luyb177/meow-nook/service/task/pb/task/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AbandonTaskReq     = v1.AbandonTaskReq
	AbandonTaskResp    = v1.AbandonTaskResp
	ClaimTaskReq       = v1.ClaimTaskReq
	ClaimTaskResp      = v1.ClaimTaskResp
	CompleteTaskReq    = v1.CompleteTaskReq
	CompleteTaskResp   = v1.CompleteTaskResp
	CreateTaskReq      = v1.CreateTaskReq
	CreateTaskResp     = v1.CreateTaskResp
	ExtendDeadlineReq  = v1.ExtendDeadlineReq
	ExtendDeadlineResp = v1.ExtendDeadlineResp
	GetTaskReq         = v1.GetTaskReq
	GetTaskResp        = v1.GetTaskResp
	ListTasksReq       = v1.ListTasksReq
	ListTasksResp      = v1.ListTasksResp
	TaskAssignee       = v1.TaskAssignee
	TaskInfo           = v1.TaskInfo
	TaskLog            = v1.TaskLog
	UpdateTaskReq      = v1.UpdateTaskReq
	UpdateTaskResp     = v1.UpdateTaskResp

	TaskService interface {
		CreateTask(ctx context.Context, in *CreateTaskReq, opts ...grpc.CallOption) (*CreateTaskResp, error)
		GetTask(ctx context.Context, in *GetTaskReq, opts ...grpc.CallOption) (*GetTaskResp, error)
		UpdateTask(ctx context.Context, in *UpdateTaskReq, opts ...grpc.CallOption) (*UpdateTaskResp, error)
		ListTasks(ctx context.Context, in *ListTasksReq, opts ...grpc.CallOption) (*ListTasksResp, error)
		ClaimTask(ctx context.Context, in *ClaimTaskReq, opts ...grpc.CallOption) (*ClaimTaskResp, error)
		AbandonTask(ctx context.Context, in *AbandonTaskReq, opts ...grpc.CallOption) (*AbandonTaskResp, error)
		CompleteTask(ctx context.Context, in *CompleteTaskReq, opts ...grpc.CallOption) (*CompleteTaskResp, error)
		ExtendDeadline(ctx context.Context, in *ExtendDeadlineReq, opts ...grpc.CallOption) (*ExtendDeadlineResp, error)
	}

	defaultTaskService struct {
		cli zrpc.Client
	}
)

func NewTaskService(cli zrpc.Client) TaskService {
	return &defaultTaskService{
		cli: cli,
	}
}

func (m *defaultTaskService) CreateTask(ctx context.Context, in *CreateTaskReq, opts ...grpc.CallOption) (*CreateTaskResp, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.CreateTask(ctx, in, opts...)
}

func (m *defaultTaskService) GetTask(ctx context.Context, in *GetTaskReq, opts ...grpc.CallOption) (*GetTaskResp, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.GetTask(ctx, in, opts...)
}

func (m *defaultTaskService) UpdateTask(ctx context.Context, in *UpdateTaskReq, opts ...grpc.CallOption) (*UpdateTaskResp, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.UpdateTask(ctx, in, opts...)
}

func (m *defaultTaskService) ListTasks(ctx context.Context, in *ListTasksReq, opts ...grpc.CallOption) (*ListTasksResp, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.ListTasks(ctx, in, opts...)
}

func (m *defaultTaskService) ClaimTask(ctx context.Context, in *ClaimTaskReq, opts ...grpc.CallOption) (*ClaimTaskResp, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.ClaimTask(ctx, in, opts...)
}

func (m *defaultTaskService) AbandonTask(ctx context.Context, in *AbandonTaskReq, opts ...grpc.CallOption) (*AbandonTaskResp, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.AbandonTask(ctx, in, opts...)
}

func (m *defaultTaskService) CompleteTask(ctx context.Context, in *CompleteTaskReq, opts ...grpc.CallOption) (*CompleteTaskResp, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.CompleteTask(ctx, in, opts...)
}

func (m *defaultTaskService) ExtendDeadline(ctx context.Context, in *ExtendDeadlineReq, opts ...grpc.CallOption) (*ExtendDeadlineResp, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.ExtendDeadline(ctx, in, opts...)
}
