services:
  # ================= ETCD =================
  etcd:
    image: quay.io/coreos/etcd:v3.5.15
    restart: unless-stopped
    environment:
      ETCD_NAME: etcd-node
      ETCD_DATA_DIR: /etcd-data

      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380

      #  内网 + 外网
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379,http://127.0.0.1:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380

      ETCD_INITIAL_CLUSTER: etcd-node=http://etcd:2380
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-cluster
      ETCD_INITIAL_CLUSTER_STATE: new

    volumes:
      - ./etcd/etcd-data:/etcd-data
    ports:
      - "2379:2379"
      - "2380:2380"

  # ================= REDIS =================
  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  # ================= MYSQL =================
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "your-strong-password"
    ports:
      - "3306:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql

  # ================= KAFKA =================
  kafka:
    image: apache/kafka:3.7.0
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # 双监听（关键）
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093,CONTROLLER://:9094

      # 内网 + 外网
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://127.0.0.1:9093

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - ./kafka/kafka-data:/var/lib/kafka/data

  # ================= CAT =================
  cat:
    image: crpi-u5azhs6neq326bz0.cn-hangzhou.personal.cr.aliyuncs.com/yub_lu/cat:0.0.2
    pull_policy: always   # 始终拉取
    depends_on:
      - etcd
      - mysql
      - redis
      - kafka
    volumes:
      - ./cat/etc:/app/etc
    command: ["./cat", "-f", "etc/cat.yaml"]

  # ================= USER =================
  user:
    image: crpi-u5azhs6neq326bz0.cn-hangzhou.personal.cr.aliyuncs.com/yub_lu/user:0.0.2
    pull_policy: always
    depends_on:
      - etcd
      - mysql
      - redis
    volumes:
      - ./user/etc:/app/etc
    command: ["./user", "-f", "etc/user.yaml"]

  # ================= GATEWAY =================
  gateway:
    image: crpi-u5azhs6neq326bz0.cn-hangzhou.personal.cr.aliyuncs.com/yub_lu/gateway:0.0.6
    pull_policy: always
    depends_on:
      - cat
      - user
    ports:
      - "8888:8888"
    volumes:
      - ./gateway/etc:/app/etc
    command: ["./gateway", "-f", "etc/gateway.yaml"]

networks:
  default:
    driver: bridge