// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pb/adoption/v1/adoption.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationStatus int32

const (
	ApplicationStatus_APP_STATUS_UNKNOWN ApplicationStatus = 0
	ApplicationStatus_PENDING_REVIEW     ApplicationStatus = 1 // 待审核
	ApplicationStatus_APPROVED           ApplicationStatus = 2 // 审核通过
	ApplicationStatus_REJECTED           ApplicationStatus = 3 // 审核未通过
	ApplicationStatus_COMPLETED          ApplicationStatus = 4 // 领养完成
	ApplicationStatus_WITHDRAWN          ApplicationStatus = 5 // 已撤回
)

// Enum value maps for ApplicationStatus.
var (
	ApplicationStatus_name = map[int32]string{
		0: "APP_STATUS_UNKNOWN",
		1: "PENDING_REVIEW",
		2: "APPROVED",
		3: "REJECTED",
		4: "COMPLETED",
		5: "WITHDRAWN",
	}
	ApplicationStatus_value = map[string]int32{
		"APP_STATUS_UNKNOWN": 0,
		"PENDING_REVIEW":     1,
		"APPROVED":           2,
		"REJECTED":           3,
		"COMPLETED":          4,
		"WITHDRAWN":          5,
	}
)

func (x ApplicationStatus) Enum() *ApplicationStatus {
	p := new(ApplicationStatus)
	*p = x
	return p
}

func (x ApplicationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_adoption_v1_adoption_proto_enumTypes[0].Descriptor()
}

func (ApplicationStatus) Type() protoreflect.EnumType {
	return &file_pb_adoption_v1_adoption_proto_enumTypes[0]
}

func (x ApplicationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicationStatus.Descriptor instead.
func (ApplicationStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_adoption_v1_adoption_proto_rawDescGZIP(), []int{0}
}

type AdoptionApplication struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CatId          int64                  `protobuf:"varint,2,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	CatName        string                 `protobuf:"bytes,3,opt,name=cat_name,json=catName,proto3" json:"cat_name,omitempty"`
	ApplicantId    int64                  `protobuf:"varint,4,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"`
	ApplicantName  string                 `protobuf:"bytes,5,opt,name=applicant_name,json=applicantName,proto3" json:"applicant_name,omitempty"`
	Status         ApplicationStatus      `protobuf:"varint,6,opt,name=status,proto3,enum=adoption.ApplicationStatus" json:"status,omitempty"`
	RejectReason   string                 `protobuf:"bytes,7,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	RequiredPoints int32                  `protobuf:"varint,8,opt,name=required_points,json=requiredPoints,proto3" json:"required_points,omitempty"`
	AppliedAt      int64                  `protobuf:"varint,9,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdoptionApplication) Reset() {
	*x = AdoptionApplication{}
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdoptionApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdoptionApplication) ProtoMessage() {}

func (x *AdoptionApplication) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdoptionApplication.ProtoReflect.Descriptor instead.
func (*AdoptionApplication) Descriptor() ([]byte, []int) {
	return file_pb_adoption_v1_adoption_proto_rawDescGZIP(), []int{0}
}

func (x *AdoptionApplication) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdoptionApplication) GetCatId() int64 {
	if x != nil {
		return x.CatId
	}
	return 0
}

func (x *AdoptionApplication) GetCatName() string {
	if x != nil {
		return x.CatName
	}
	return ""
}

func (x *AdoptionApplication) GetApplicantId() int64 {
	if x != nil {
		return x.ApplicantId
	}
	return 0
}

func (x *AdoptionApplication) GetApplicantName() string {
	if x != nil {
		return x.ApplicantName
	}
	return ""
}

func (x *AdoptionApplication) GetStatus() ApplicationStatus {
	if x != nil {
		return x.Status
	}
	return ApplicationStatus_APP_STATUS_UNKNOWN
}

func (x *AdoptionApplication) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *AdoptionApplication) GetRequiredPoints() int32 {
	if x != nil {
		return x.RequiredPoints
	}
	return 0
}

func (x *AdoptionApplication) GetAppliedAt() int64 {
	if x != nil {
		return x.AppliedAt
	}
	return 0
}

func (x *AdoptionApplication) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type FollowUpRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId int64                  `protobuf:"varint,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ApplicantId   int64                  `protobuf:"varint,3,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"`
	Stage         string                 `protobuf:"bytes,4,opt,name=stage,proto3" json:"stage,omitempty"` // 1周 / 1个月 / 3个月 / 6个月
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Photos        []string               `protobuf:"bytes,6,rep,name=photos,proto3" json:"photos,omitempty"`
	SubmittedAt   int64                  `protobuf:"varint,7,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUpRecord) Reset() {
	*x = FollowUpRecord{}
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUpRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUpRecord) ProtoMessage() {}

func (x *FollowUpRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUpRecord.ProtoReflect.Descriptor instead.
func (*FollowUpRecord) Descriptor() ([]byte, []int) {
	return file_pb_adoption_v1_adoption_proto_rawDescGZIP(), []int{1}
}

func (x *FollowUpRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FollowUpRecord) GetApplicationId() int64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *FollowUpRecord) GetApplicantId() int64 {
	if x != nil {
		return x.ApplicantId
	}
	return 0
}

func (x *FollowUpRecord) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *FollowUpRecord) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FollowUpRecord) GetPhotos() []string {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *FollowUpRecord) GetSubmittedAt() int64 {
	if x != nil {
		return x.SubmittedAt
	}
	return 0
}

type ApplyAdoptionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatId         int64                  `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	ApplicantId   int64                  `protobuf:"varint,2,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyAdoptionReq) Reset() {
	*x = ApplyAdoptionReq{}
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyAdoptionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyAdoptionReq) ProtoMessage() {}

func (x *ApplyAdoptionReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyAdoptionReq.ProtoReflect.Descriptor instead.
func (*ApplyAdoptionReq) Descriptor() ([]byte, []int) {
	return file_pb_adoption_v1_adoption_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyAdoptionReq) GetCatId() int64 {
	if x != nil {
		return x.CatId
	}
	return 0
}

func (x *ApplyAdoptionReq) GetApplicantId() int64 {
	if x != nil {
		return x.ApplicantId
	}
	return 0
}

func (x *ApplyAdoptionReq) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ApplyAdoptionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId int64                  `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyAdoptionResp) Reset() {
	*x = ApplyAdoptionResp{}
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyAdoptionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyAdoptionResp) ProtoMessage() {}

func (x *ApplyAdoptionResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyAdoptionResp.ProtoReflect.Descriptor instead.
func (*ApplyAdoptionResp) Descriptor() ([]byte, []int) {
	return file_pb_adoption_v1_adoption_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyAdoptionResp) GetApplicationId() int64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

type ReviewApplicationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId int64                  `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ReviewerId    int64                  `protobuf:"varint,2,opt,name=reviewer_id,json=reviewerId,proto3" json:"reviewer_id,omitempty"`
	Approved      bool                   `protobuf:"varint,3,opt,name=approved,proto3" json:"approved,omitempty"`
	RejectReason  string                 `protobuf:"bytes,4,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewApplicationReq) Reset() {
	*x = ReviewApplicationReq{}
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewApplicationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewApplicationReq) ProtoMessage() {}

func (x *ReviewApplicationReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewApplicationReq.ProtoReflect.Descriptor instead.
func (*ReviewApplicationReq) Descriptor() ([]byte, []int) {
	return file_pb_adoption_v1_adoption_proto_rawDescGZIP(), []int{4}
}

func (x *ReviewApplicationReq) GetApplicationId() int64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *ReviewApplicationReq) GetReviewerId() int64 {
	if x != nil {
		return x.ReviewerId
	}
	return 0
}

func (x *ReviewApplicationReq) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ReviewApplicationReq) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type ReviewApplicationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewApplicationResp) Reset() {
	*x = ReviewApplicationResp{}
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewApplicationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewApplicationResp) ProtoMessage() {}

func (x *ReviewApplicationResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewApplicationResp.ProtoReflect.Descriptor instead.
func (*ReviewApplicationResp) Descriptor() ([]byte, []int) {
	return file_pb_adoption_v1_adoption_proto_rawDescGZIP(), []int{5}
}

type GetApplicationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId int64                  `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationReq) Reset() {
	*x = GetApplicationReq{}
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationReq) ProtoMessage() {}

func (x *GetApplicationReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationReq.ProtoReflect.Descriptor instead.
func (*GetApplicationReq) Descriptor() ([]byte, []int) {
	return file_pb_adoption_v1_adoption_proto_rawDescGZIP(), []int{6}
}

func (x *GetApplicationReq) GetApplicationId() int64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

type GetApplicationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *AdoptionApplication   `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationResp) Reset() {
	*x = GetApplicationResp{}
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationResp) ProtoMessage() {}

func (x *GetApplicationResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationResp.ProtoReflect.Descriptor instead.
func (*GetApplicationResp) Descriptor() ([]byte, []int) {
	return file_pb_adoption_v1_adoption_proto_rawDescGZIP(), []int{7}
}

func (x *GetApplicationResp) GetApplication() *AdoptionApplication {
	if x != nil {
		return x.Application
	}
	return nil
}

type ListApplicationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicantId   int64                  `protobuf:"varint,1,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"` // 0 = all
	CatId         int64                  `protobuf:"varint,2,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`                   // 0 = all
	Status        ApplicationStatus      `protobuf:"varint,3,opt,name=status,proto3,enum=adoption.ApplicationStatus" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsReq) Reset() {
	*x = ListApplicationsReq{}
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsReq) ProtoMessage() {}

func (x *ListApplicationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsReq.ProtoReflect.Descriptor instead.
func (*ListApplicationsReq) Descriptor() ([]byte, []int) {
	return file_pb_adoption_v1_adoption_proto_rawDescGZIP(), []int{8}
}

func (x *ListApplicationsReq) GetApplicantId() int64 {
	if x != nil {
		return x.ApplicantId
	}
	return 0
}

func (x *ListApplicationsReq) GetCatId() int64 {
	if x != nil {
		return x.CatId
	}
	return 0
}

func (x *ListApplicationsReq) GetStatus() ApplicationStatus {
	if x != nil {
		return x.Status
	}
	return ApplicationStatus_APP_STATUS_UNKNOWN
}

func (x *ListApplicationsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListApplicationsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListApplicationsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*AdoptionApplication `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsResp) Reset() {
	*x = ListApplicationsResp{}
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResp) ProtoMessage() {}

func (x *ListApplicationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResp.ProtoReflect.Descriptor instead.
func (*ListApplicationsResp) Descriptor() ([]byte, []int) {
	return file_pb_adoption_v1_adoption_proto_rawDescGZIP(), []int{9}
}

func (x *ListApplicationsResp) GetApplications() []*AdoptionApplication {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *ListApplicationsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SubmitFollowUpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId int64                  `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ApplicantId   int64                  `protobuf:"varint,2,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"`
	Stage         string                 `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Photos        []string               `protobuf:"bytes,5,rep,name=photos,proto3" json:"photos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFollowUpReq) Reset() {
	*x = SubmitFollowUpReq{}
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFollowUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFollowUpReq) ProtoMessage() {}

func (x *SubmitFollowUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFollowUpReq.ProtoReflect.Descriptor instead.
func (*SubmitFollowUpReq) Descriptor() ([]byte, []int) {
	return file_pb_adoption_v1_adoption_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitFollowUpReq) GetApplicationId() int64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *SubmitFollowUpReq) GetApplicantId() int64 {
	if x != nil {
		return x.ApplicantId
	}
	return 0
}

func (x *SubmitFollowUpReq) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *SubmitFollowUpReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SubmitFollowUpReq) GetPhotos() []string {
	if x != nil {
		return x.Photos
	}
	return nil
}

type SubmitFollowUpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      int64                  `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFollowUpResp) Reset() {
	*x = SubmitFollowUpResp{}
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFollowUpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFollowUpResp) ProtoMessage() {}

func (x *SubmitFollowUpResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFollowUpResp.ProtoReflect.Descriptor instead.
func (*SubmitFollowUpResp) Descriptor() ([]byte, []int) {
	return file_pb_adoption_v1_adoption_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitFollowUpResp) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

type ListFollowUpsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId int64                  `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowUpsReq) Reset() {
	*x = ListFollowUpsReq{}
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowUpsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowUpsReq) ProtoMessage() {}

func (x *ListFollowUpsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowUpsReq.ProtoReflect.Descriptor instead.
func (*ListFollowUpsReq) Descriptor() ([]byte, []int) {
	return file_pb_adoption_v1_adoption_proto_rawDescGZIP(), []int{12}
}

func (x *ListFollowUpsReq) GetApplicationId() int64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

type ListFollowUpsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*FollowUpRecord      `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowUpsResp) Reset() {
	*x = ListFollowUpsResp{}
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowUpsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowUpsResp) ProtoMessage() {}

func (x *ListFollowUpsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adoption_v1_adoption_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowUpsResp.ProtoReflect.Descriptor instead.
func (*ListFollowUpsResp) Descriptor() ([]byte, []int) {
	return file_pb_adoption_v1_adoption_proto_rawDescGZIP(), []int{13}
}

func (x *ListFollowUpsResp) GetRecords() []*FollowUpRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_pb_adoption_v1_adoption_proto protoreflect.FileDescriptor

const file_pb_adoption_v1_adoption_proto_rawDesc = "" +
	"\n" +
	"\x1dpb/adoption/v1/adoption.proto\x12\badoption\"\xe2\x02\n" +
	"\x13AdoptionApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06cat_id\x18\x02 \x01(\x03R\x05catId\x12\x19\n" +
	"\bcat_name\x18\x03 \x01(\tR\acatName\x12!\n" +
	"\fapplicant_id\x18\x04 \x01(\x03R\vapplicantId\x12%\n" +
	"\x0eapplicant_name\x18\x05 \x01(\tR\rapplicantName\x123\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1b.adoption.ApplicationStatusR\x06status\x12#\n" +
	"\rreject_reason\x18\a \x01(\tR\frejectReason\x12'\n" +
	"\x0frequired_points\x18\b \x01(\x05R\x0erequiredPoints\x12\x1d\n" +
	"\n" +
	"applied_at\x18\t \x01(\x03R\tappliedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"\xd5\x01\n" +
	"\x0eFollowUpRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\x03R\rapplicationId\x12!\n" +
	"\fapplicant_id\x18\x03 \x01(\x03R\vapplicantId\x12\x14\n" +
	"\x05stage\x18\x04 \x01(\tR\x05stage\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06photos\x18\x06 \x03(\tR\x06photos\x12!\n" +
	"\fsubmitted_at\x18\a \x01(\x03R\vsubmittedAt\"`\n" +
	"\x10ApplyAdoptionReq\x12\x15\n" +
	"\x06cat_id\x18\x01 \x01(\x03R\x05catId\x12!\n" +
	"\fapplicant_id\x18\x02 \x01(\x03R\vapplicantId\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\":\n" +
	"\x11ApplyAdoptionResp\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x03R\rapplicationId\"\x9f\x01\n" +
	"\x14ReviewApplicationReq\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x03R\rapplicationId\x12\x1f\n" +
	"\vreviewer_id\x18\x02 \x01(\x03R\n" +
	"reviewerId\x12\x1a\n" +
	"\bapproved\x18\x03 \x01(\bR\bapproved\x12#\n" +
	"\rreject_reason\x18\x04 \x01(\tR\frejectReason\"\x17\n" +
	"\x15ReviewApplicationResp\":\n" +
	"\x11GetApplicationReq\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x03R\rapplicationId\"U\n" +
	"\x12GetApplicationResp\x12?\n" +
	"\vapplication\x18\x01 \x01(\v2\x1d.adoption.AdoptionApplicationR\vapplication\"\xac\x01\n" +
	"\x13ListApplicationsReq\x12!\n" +
	"\fapplicant_id\x18\x01 \x01(\x03R\vapplicantId\x12\x15\n" +
	"\x06cat_id\x18\x02 \x01(\x03R\x05catId\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.adoption.ApplicationStatusR\x06status\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x05R\x04size\"o\n" +
	"\x14ListApplicationsResp\x12A\n" +
	"\fapplications\x18\x01 \x03(\v2\x1d.adoption.AdoptionApplicationR\fapplications\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa5\x01\n" +
	"\x11SubmitFollowUpReq\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x03R\rapplicationId\x12!\n" +
	"\fapplicant_id\x18\x02 \x01(\x03R\vapplicantId\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06photos\x18\x05 \x03(\tR\x06photos\"1\n" +
	"\x12SubmitFollowUpResp\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\x03R\brecordId\"9\n" +
	"\x10ListFollowUpsReq\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x03R\rapplicationId\"G\n" +
	"\x11ListFollowUpsResp\x122\n" +
	"\arecords\x18\x01 \x03(\v2\x18.adoption.FollowUpRecordR\arecords*y\n" +
	"\x11ApplicationStatus\x12\x16\n" +
	"\x12APP_STATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0ePENDING_REVIEW\x10\x01\x12\f\n" +
	"\bAPPROVED\x10\x02\x12\f\n" +
	"\bREJECTED\x10\x03\x12\r\n" +
	"\tCOMPLETED\x10\x04\x12\r\n" +
	"\tWITHDRAWN\x10\x052\xe8\x03\n" +
	"\x0fAdoptionService\x12H\n" +
	"\rApplyAdoption\x12\x1a.adoption.ApplyAdoptionReq\x1a\x1b.adoption.ApplyAdoptionResp\x12T\n" +
	"\x11ReviewApplication\x12\x1e.adoption.ReviewApplicationReq\x1a\x1f.adoption.ReviewApplicationResp\x12K\n" +
	"\x0eGetApplication\x12\x1b.adoption.GetApplicationReq\x1a\x1c.adoption.GetApplicationResp\x12Q\n" +
	"\x10ListApplications\x12\x1d.adoption.ListApplicationsReq\x1a\x1e.adoption.ListApplicationsResp\x12K\n" +
	"\x0eSubmitFollowUp\x12\x1b.adoption.SubmitFollowUpReq\x1a\x1c.adoption.SubmitFollowUpResp\x12H\n" +
	"\rListFollowUps\x12\x1a.adoption.ListFollowUpsReq\x1a\x1b.adoption.ListFollowUpsRespB\x12Z\x10./pb/adoption/v1b\x06proto3"

var (
	file_pb_adoption_v1_adoption_proto_rawDescOnce sync.Once
	file_pb_adoption_v1_adoption_proto_rawDescData []byte
)

func file_pb_adoption_v1_adoption_proto_rawDescGZIP() []byte {
	file_pb_adoption_v1_adoption_proto_rawDescOnce.Do(func() {
		file_pb_adoption_v1_adoption_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_adoption_v1_adoption_proto_rawDesc), len(file_pb_adoption_v1_adoption_proto_rawDesc)))
	})
	return file_pb_adoption_v1_adoption_proto_rawDescData
}

var file_pb_adoption_v1_adoption_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_adoption_v1_adoption_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pb_adoption_v1_adoption_proto_goTypes = []any{
	(ApplicationStatus)(0),        // 0: adoption.ApplicationStatus
	(*AdoptionApplication)(nil),   // 1: adoption.AdoptionApplication
	(*FollowUpRecord)(nil),        // 2: adoption.FollowUpRecord
	(*ApplyAdoptionReq)(nil),      // 3: adoption.ApplyAdoptionReq
	(*ApplyAdoptionResp)(nil),     // 4: adoption.ApplyAdoptionResp
	(*ReviewApplicationReq)(nil),  // 5: adoption.ReviewApplicationReq
	(*ReviewApplicationResp)(nil), // 6: adoption.ReviewApplicationResp
	(*GetApplicationReq)(nil),     // 7: adoption.GetApplicationReq
	(*GetApplicationResp)(nil),    // 8: adoption.GetApplicationResp
	(*ListApplicationsReq)(nil),   // 9: adoption.ListApplicationsReq
	(*ListApplicationsResp)(nil),  // 10: adoption.ListApplicationsResp
	(*SubmitFollowUpReq)(nil),     // 11: adoption.SubmitFollowUpReq
	(*SubmitFollowUpResp)(nil),    // 12: adoption.SubmitFollowUpResp
	(*ListFollowUpsReq)(nil),      // 13: adoption.ListFollowUpsReq
	(*ListFollowUpsResp)(nil),     // 14: adoption.ListFollowUpsResp
}
var file_pb_adoption_v1_adoption_proto_depIdxs = []int32{
	0,  // 0: adoption.AdoptionApplication.status:type_name -> adoption.ApplicationStatus
	1,  // 1: adoption.GetApplicationResp.application:type_name -> adoption.AdoptionApplication
	0,  // 2: adoption.ListApplicationsReq.status:type_name -> adoption.ApplicationStatus
	1,  // 3: adoption.ListApplicationsResp.applications:type_name -> adoption.AdoptionApplication
	2,  // 4: adoption.ListFollowUpsResp.records:type_name -> adoption.FollowUpRecord
	3,  // 5: adoption.AdoptionService.ApplyAdoption:input_type -> adoption.ApplyAdoptionReq
	5,  // 6: adoption.AdoptionService.ReviewApplication:input_type -> adoption.ReviewApplicationReq
	7,  // 7: adoption.AdoptionService.GetApplication:input_type -> adoption.GetApplicationReq
	9,  // 8: adoption.AdoptionService.ListApplications:input_type -> adoption.ListApplicationsReq
	11, // 9: adoption.AdoptionService.SubmitFollowUp:input_type -> adoption.SubmitFollowUpReq
	13, // 10: adoption.AdoptionService.ListFollowUps:input_type -> adoption.ListFollowUpsReq
	4,  // 11: adoption.AdoptionService.ApplyAdoption:output_type -> adoption.ApplyAdoptionResp
	6,  // 12: adoption.AdoptionService.ReviewApplication:output_type -> adoption.ReviewApplicationResp
	8,  // 13: adoption.AdoptionService.GetApplication:output_type -> adoption.GetApplicationResp
	10, // 14: adoption.AdoptionService.ListApplications:output_type -> adoption.ListApplicationsResp
	12, // 15: adoption.AdoptionService.SubmitFollowUp:output_type -> adoption.SubmitFollowUpResp
	14, // 16: adoption.AdoptionService.ListFollowUps:output_type -> adoption.ListFollowUpsResp
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pb_adoption_v1_adoption_proto_init() }
func file_pb_adoption_v1_adoption_proto_init() {
	if File_pb_adoption_v1_adoption_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_adoption_v1_adoption_proto_rawDesc), len(file_pb_adoption_v1_adoption_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_adoption_v1_adoption_proto_goTypes,
		DependencyIndexes: file_pb_adoption_v1_adoption_proto_depIdxs,
		EnumInfos:         file_pb_adoption_v1_adoption_proto_enumTypes,
		MessageInfos:      file_pb_adoption_v1_adoption_proto_msgTypes,
	}.Build()
	File_pb_adoption_v1_adoption_proto = out.File
	file_pb_adoption_v1_adoption_proto_goTypes = nil
	file_pb_adoption_v1_adoption_proto_depIdxs = nil
}
