// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: pb/adoption/v1/adoption.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdoptionService_ApplyAdoption_FullMethodName     = "/adoption.AdoptionService/ApplyAdoption"
	AdoptionService_ReviewApplication_FullMethodName = "/adoption.AdoptionService/ReviewApplication"
	AdoptionService_GetApplication_FullMethodName    = "/adoption.AdoptionService/GetApplication"
	AdoptionService_ListApplications_FullMethodName  = "/adoption.AdoptionService/ListApplications"
	AdoptionService_SubmitFollowUp_FullMethodName    = "/adoption.AdoptionService/SubmitFollowUp"
	AdoptionService_ListFollowUps_FullMethodName     = "/adoption.AdoptionService/ListFollowUps"
)

// AdoptionServiceClient is the client API for AdoptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdoptionServiceClient interface {
	ApplyAdoption(ctx context.Context, in *ApplyAdoptionReq, opts ...grpc.CallOption) (*ApplyAdoptionResp, error)
	ReviewApplication(ctx context.Context, in *ReviewApplicationReq, opts ...grpc.CallOption) (*ReviewApplicationResp, error)
	GetApplication(ctx context.Context, in *GetApplicationReq, opts ...grpc.CallOption) (*GetApplicationResp, error)
	ListApplications(ctx context.Context, in *ListApplicationsReq, opts ...grpc.CallOption) (*ListApplicationsResp, error)
	SubmitFollowUp(ctx context.Context, in *SubmitFollowUpReq, opts ...grpc.CallOption) (*SubmitFollowUpResp, error)
	ListFollowUps(ctx context.Context, in *ListFollowUpsReq, opts ...grpc.CallOption) (*ListFollowUpsResp, error)
}

type adoptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdoptionServiceClient(cc grpc.ClientConnInterface) AdoptionServiceClient {
	return &adoptionServiceClient{cc}
}

func (c *adoptionServiceClient) ApplyAdoption(ctx context.Context, in *ApplyAdoptionReq, opts ...grpc.CallOption) (*ApplyAdoptionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyAdoptionResp)
	err := c.cc.Invoke(ctx, AdoptionService_ApplyAdoption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adoptionServiceClient) ReviewApplication(ctx context.Context, in *ReviewApplicationReq, opts ...grpc.CallOption) (*ReviewApplicationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewApplicationResp)
	err := c.cc.Invoke(ctx, AdoptionService_ReviewApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adoptionServiceClient) GetApplication(ctx context.Context, in *GetApplicationReq, opts ...grpc.CallOption) (*GetApplicationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApplicationResp)
	err := c.cc.Invoke(ctx, AdoptionService_GetApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adoptionServiceClient) ListApplications(ctx context.Context, in *ListApplicationsReq, opts ...grpc.CallOption) (*ListApplicationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListApplicationsResp)
	err := c.cc.Invoke(ctx, AdoptionService_ListApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adoptionServiceClient) SubmitFollowUp(ctx context.Context, in *SubmitFollowUpReq, opts ...grpc.CallOption) (*SubmitFollowUpResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitFollowUpResp)
	err := c.cc.Invoke(ctx, AdoptionService_SubmitFollowUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adoptionServiceClient) ListFollowUps(ctx context.Context, in *ListFollowUpsReq, opts ...grpc.CallOption) (*ListFollowUpsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFollowUpsResp)
	err := c.cc.Invoke(ctx, AdoptionService_ListFollowUps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdoptionServiceServer is the server API for AdoptionService service.
// All implementations must embed UnimplementedAdoptionServiceServer
// for forward compatibility.
type AdoptionServiceServer interface {
	ApplyAdoption(context.Context, *ApplyAdoptionReq) (*ApplyAdoptionResp, error)
	ReviewApplication(context.Context, *ReviewApplicationReq) (*ReviewApplicationResp, error)
	GetApplication(context.Context, *GetApplicationReq) (*GetApplicationResp, error)
	ListApplications(context.Context, *ListApplicationsReq) (*ListApplicationsResp, error)
	SubmitFollowUp(context.Context, *SubmitFollowUpReq) (*SubmitFollowUpResp, error)
	ListFollowUps(context.Context, *ListFollowUpsReq) (*ListFollowUpsResp, error)
	mustEmbedUnimplementedAdoptionServiceServer()
}

// UnimplementedAdoptionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdoptionServiceServer struct{}

func (UnimplementedAdoptionServiceServer) ApplyAdoption(context.Context, *ApplyAdoptionReq) (*ApplyAdoptionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyAdoption not implemented")
}
func (UnimplementedAdoptionServiceServer) ReviewApplication(context.Context, *ReviewApplicationReq) (*ReviewApplicationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewApplication not implemented")
}
func (UnimplementedAdoptionServiceServer) GetApplication(context.Context, *GetApplicationReq) (*GetApplicationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplication not implemented")
}
func (UnimplementedAdoptionServiceServer) ListApplications(context.Context, *ListApplicationsReq) (*ListApplicationsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApplications not implemented")
}
func (UnimplementedAdoptionServiceServer) SubmitFollowUp(context.Context, *SubmitFollowUpReq) (*SubmitFollowUpResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitFollowUp not implemented")
}
func (UnimplementedAdoptionServiceServer) ListFollowUps(context.Context, *ListFollowUpsReq) (*ListFollowUpsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFollowUps not implemented")
}
func (UnimplementedAdoptionServiceServer) mustEmbedUnimplementedAdoptionServiceServer() {}
func (UnimplementedAdoptionServiceServer) testEmbeddedByValue()                         {}

// UnsafeAdoptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdoptionServiceServer will
// result in compilation errors.
type UnsafeAdoptionServiceServer interface {
	mustEmbedUnimplementedAdoptionServiceServer()
}

func RegisterAdoptionServiceServer(s grpc.ServiceRegistrar, srv AdoptionServiceServer) {
	// If the following call panics, it indicates UnimplementedAdoptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdoptionService_ServiceDesc, srv)
}

func _AdoptionService_ApplyAdoption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyAdoptionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdoptionServiceServer).ApplyAdoption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdoptionService_ApplyAdoption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdoptionServiceServer).ApplyAdoption(ctx, req.(*ApplyAdoptionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdoptionService_ReviewApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewApplicationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdoptionServiceServer).ReviewApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdoptionService_ReviewApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdoptionServiceServer).ReviewApplication(ctx, req.(*ReviewApplicationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdoptionService_GetApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdoptionServiceServer).GetApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdoptionService_GetApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdoptionServiceServer).GetApplication(ctx, req.(*GetApplicationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdoptionService_ListApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdoptionServiceServer).ListApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdoptionService_ListApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdoptionServiceServer).ListApplications(ctx, req.(*ListApplicationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdoptionService_SubmitFollowUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitFollowUpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdoptionServiceServer).SubmitFollowUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdoptionService_SubmitFollowUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdoptionServiceServer).SubmitFollowUp(ctx, req.(*SubmitFollowUpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdoptionService_ListFollowUps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFollowUpsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdoptionServiceServer).ListFollowUps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdoptionService_ListFollowUps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdoptionServiceServer).ListFollowUps(ctx, req.(*ListFollowUpsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdoptionService_ServiceDesc is the grpc.ServiceDesc for AdoptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdoptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adoption.AdoptionService",
	HandlerType: (*AdoptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyAdoption",
			Handler:    _AdoptionService_ApplyAdoption_Handler,
		},
		{
			MethodName: "ReviewApplication",
			Handler:    _AdoptionService_ReviewApplication_Handler,
		},
		{
			MethodName: "GetApplication",
			Handler:    _AdoptionService_GetApplication_Handler,
		},
		{
			MethodName: "ListApplications",
			Handler:    _AdoptionService_ListApplications_Handler,
		},
		{
			MethodName: "SubmitFollowUp",
			Handler:    _AdoptionService_SubmitFollowUp_Handler,
		},
		{
			MethodName: "ListFollowUps",
			Handler:    _AdoptionService_ListFollowUps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/adoption/v1/adoption.proto",
}
