// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common/pb/errordetail/v1/error_detail.proto

package errordetailv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorDetail carries business error information across gRPC service boundaries.
// It is attached to a gRPC status via WithDetails so that the HTTP gateway
// can reconstruct the original {code, msg} response without string-parsing.
type ErrorDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Business error code (mirrors errorx code constants).
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// User-facing error message.
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// Internal cause for server-side logging only; never exposed to clients.
	Cause         string `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_common_pb_errordetail_v1_error_detail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_errordetail_v1_error_detail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_common_pb_errordetail_v1_error_detail_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetail) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorDetail) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ErrorDetail) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

var File_common_pb_errordetail_v1_error_detail_proto protoreflect.FileDescriptor

const file_common_pb_errordetail_v1_error_detail_proto_rawDesc = "" +
	"\n" +
	"+common/pb/errordetail/v1/error_detail.proto\x12\x0eerrordetail.v1\"I\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05causeBEZCgithub.com/luyb177/meow-nook/common/pb/errordetail/v1;errordetailv1b\x06proto3"

var (
	file_common_pb_errordetail_v1_error_detail_proto_rawDescOnce sync.Once
	file_common_pb_errordetail_v1_error_detail_proto_rawDescData []byte
)

func file_common_pb_errordetail_v1_error_detail_proto_rawDescGZIP() []byte {
	file_common_pb_errordetail_v1_error_detail_proto_rawDescOnce.Do(func() {
		file_common_pb_errordetail_v1_error_detail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_pb_errordetail_v1_error_detail_proto_rawDesc), len(file_common_pb_errordetail_v1_error_detail_proto_rawDesc)))
	})
	return file_common_pb_errordetail_v1_error_detail_proto_rawDescData
}

var file_common_pb_errordetail_v1_error_detail_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_pb_errordetail_v1_error_detail_proto_goTypes = []any{
	(*ErrorDetail)(nil), // 0: errordetail.v1.ErrorDetail
}
var file_common_pb_errordetail_v1_error_detail_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_pb_errordetail_v1_error_detail_proto_init() }
func file_common_pb_errordetail_v1_error_detail_proto_init() {
	if File_common_pb_errordetail_v1_error_detail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_pb_errordetail_v1_error_detail_proto_rawDesc), len(file_common_pb_errordetail_v1_error_detail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_pb_errordetail_v1_error_detail_proto_goTypes,
		DependencyIndexes: file_common_pb_errordetail_v1_error_detail_proto_depIdxs,
		MessageInfos:      file_common_pb_errordetail_v1_error_detail_proto_msgTypes,
	}.Build()
	File_common_pb_errordetail_v1_error_detail_proto = out.File
	file_common_pb_errordetail_v1_error_detail_proto_goTypes = nil
	file_common_pb_errordetail_v1_error_detail_proto_depIdxs = nil
}
