// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: post.proto

package server

import (
	"context"

	"github.com/luyb177/meow-nook/service/post/internal/logic"
	"github.com/luyb177/meow-nook/service/post/internal/svc"
	"github.com/luyb177/meow-nook/service/post/pb/post/v1"
)

type PostServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedPostServiceServer
}

func NewPostServiceServer(svcCtx *svc.ServiceContext) *PostServiceServer {
	return &PostServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PostServiceServer) CreatePost(ctx context.Context, in *v1.CreatePostReq) (*v1.CreatePostResp, error) {
	l := logic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

func (s *PostServiceServer) GetPost(ctx context.Context, in *v1.GetPostReq) (*v1.GetPostResp, error) {
	l := logic.NewGetPostLogic(ctx, s.svcCtx)
	return l.GetPost(in)
}

func (s *PostServiceServer) DeletePost(ctx context.Context, in *v1.DeletePostReq) (*v1.DeletePostResp, error) {
	l := logic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}

func (s *PostServiceServer) ListPosts(ctx context.Context, in *v1.ListPostsReq) (*v1.ListPostsResp, error) {
	l := logic.NewListPostsLogic(ctx, s.svcCtx)
	return l.ListPosts(in)
}

func (s *PostServiceServer) LikePost(ctx context.Context, in *v1.LikePostReq) (*v1.LikePostResp, error) {
	l := logic.NewLikePostLogic(ctx, s.svcCtx)
	return l.LikePost(in)
}

func (s *PostServiceServer) UnlikePost(ctx context.Context, in *v1.UnlikePostReq) (*v1.UnlikePostResp, error) {
	l := logic.NewUnlikePostLogic(ctx, s.svcCtx)
	return l.UnlikePost(in)
}

func (s *PostServiceServer) FavoritePost(ctx context.Context, in *v1.FavoritePostReq) (*v1.FavoritePostResp, error) {
	l := logic.NewFavoritePostLogic(ctx, s.svcCtx)
	return l.FavoritePost(in)
}

func (s *PostServiceServer) UnfavoritePost(ctx context.Context, in *v1.UnfavoritePostReq) (*v1.UnfavoritePostResp, error) {
	l := logic.NewUnfavoritePostLogic(ctx, s.svcCtx)
	return l.UnfavoritePost(in)
}

func (s *PostServiceServer) AddComment(ctx context.Context, in *v1.AddCommentReq) (*v1.AddCommentResp, error) {
	l := logic.NewAddCommentLogic(ctx, s.svcCtx)
	return l.AddComment(in)
}

func (s *PostServiceServer) DeleteComment(ctx context.Context, in *v1.DeleteCommentReq) (*v1.DeleteCommentResp, error) {
	l := logic.NewDeleteCommentLogic(ctx, s.svcCtx)
	return l.DeleteComment(in)
}

func (s *PostServiceServer) ListComments(ctx context.Context, in *v1.ListCommentsReq) (*v1.ListCommentsResp, error) {
	l := logic.NewListCommentsLogic(ctx, s.svcCtx)
	return l.ListComments(in)
}

func (s *PostServiceServer) ReportPost(ctx context.Context, in *v1.ReportPostReq) (*v1.ReportPostResp, error) {
	l := logic.NewReportPostLogic(ctx, s.svcCtx)
	return l.ReportPost(in)
}
