// Code generated by goctl. Safe to edit.
// goctl 1.10.1
// Source: user.proto

package userservice

import (
	"context"

	v1 "github.com/luyb177/meow-nook/service/user/pb/user/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginReq                = v1.LoginReq
	LoginResp               = v1.LoginResp
	RegisterReq             = v1.RegisterReq
	RegisterResp            = v1.RegisterResp
	Response                = v1.Response
	SendVerificationCodeReq = v1.SendVerificationCodeReq
	TestReq                 = v1.TestReq
	VerifyCodeReq           = v1.VerifyCodeReq
	VerifyChannel           = v1.VerifyChannel
	VerifyPurpose           = v1.VerifyPurpose

	UserService interface {
		// Auth
		Test(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*Response, error)
		SendVerificationCode(ctx context.Context, in *SendVerificationCodeReq, opts ...grpc.CallOption) (*Response, error)
		VerifyCode(ctx context.Context, in *VerifyCodeReq, opts ...grpc.CallOption) (*Response, error)
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{cli: cli}
}

func (m *defaultUserService) Test(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.Test(ctx, in, opts...)
}

func (m *defaultUserService) SendVerificationCode(ctx context.Context, in *SendVerificationCodeReq, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.SendVerificationCode(ctx, in, opts...)
}

func (m *defaultUserService) VerifyCode(ctx context.Context, in *VerifyCodeReq, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.VerifyCode(ctx, in, opts...)
}

func (m *defaultUserService) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
