// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package userservice

import (
	"context"

	"github.com/luyb177/meow-nook/service/user/pb/user/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddPointsReq                   = v1.AddPointsReq
	AddPointsResp                  = v1.AddPointsResp
	ChangePasswordReq              = v1.ChangePasswordReq
	ChangePasswordResp             = v1.ChangePasswordResp
	GetNotificationSettingsReq     = v1.GetNotificationSettingsReq
	GetNotificationSettingsResp    = v1.GetNotificationSettingsResp
	GetPointsReq                   = v1.GetPointsReq
	GetPointsResp                  = v1.GetPointsResp
	GetUserInfoReq                 = v1.GetUserInfoReq
	GetUserInfoResp                = v1.GetUserInfoResp
	ListPointLogsReq               = v1.ListPointLogsReq
	ListPointLogsResp              = v1.ListPointLogsResp
	LoginReq                       = v1.LoginReq
	LoginResp                      = v1.LoginResp
	LogoutReq                      = v1.LogoutReq
	LogoutResp                     = v1.LogoutResp
	NotificationSettings           = v1.NotificationSettings
	PointLog                       = v1.PointLog
	RegisterReq                    = v1.RegisterReq
	RegisterResp                   = v1.RegisterResp
	Response                       = v1.Response
	SendVerificationCodeReq        = v1.SendVerificationCodeReq
	SubmitFeedbackReq              = v1.SubmitFeedbackReq
	SubmitFeedbackResp             = v1.SubmitFeedbackResp
	UpdateNotificationSettingsReq  = v1.UpdateNotificationSettingsReq
	UpdateNotificationSettingsResp = v1.UpdateNotificationSettingsResp
	UpdateUserInfoReq              = v1.UpdateUserInfoReq
	UpdateUserInfoResp             = v1.UpdateUserInfoResp
	UserInfo                       = v1.UserInfo

	UserService interface {
		// Auth
		SendVerificationCode(ctx context.Context, in *SendVerificationCodeReq, opts ...grpc.CallOption) (*Response, error)
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error)
		// Profile
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error)
		ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*ChangePasswordResp, error)
		// Points
		GetPoints(ctx context.Context, in *GetPointsReq, opts ...grpc.CallOption) (*GetPointsResp, error)
		AddPoints(ctx context.Context, in *AddPointsReq, opts ...grpc.CallOption) (*AddPointsResp, error)
		ListPointLogs(ctx context.Context, in *ListPointLogsReq, opts ...grpc.CallOption) (*ListPointLogsResp, error)
		// Notifications
		GetNotificationSettings(ctx context.Context, in *GetNotificationSettingsReq, opts ...grpc.CallOption) (*GetNotificationSettingsResp, error)
		UpdateNotificationSettings(ctx context.Context, in *UpdateNotificationSettingsReq, opts ...grpc.CallOption) (*UpdateNotificationSettingsResp, error)
		// Feedback
		SubmitFeedback(ctx context.Context, in *SubmitFeedbackReq, opts ...grpc.CallOption) (*SubmitFeedbackResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// Auth
func (m *defaultUserService) SendVerificationCode(ctx context.Context, in *SendVerificationCodeReq, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.SendVerificationCode(ctx, in, opts...)
}

func (m *defaultUserService) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserService) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

// Profile
func (m *defaultUserService) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

func (m *defaultUserService) ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*ChangePasswordResp, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}

// Points
func (m *defaultUserService) GetPoints(ctx context.Context, in *GetPointsReq, opts ...grpc.CallOption) (*GetPointsResp, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.GetPoints(ctx, in, opts...)
}

func (m *defaultUserService) AddPoints(ctx context.Context, in *AddPointsReq, opts ...grpc.CallOption) (*AddPointsResp, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.AddPoints(ctx, in, opts...)
}

func (m *defaultUserService) ListPointLogs(ctx context.Context, in *ListPointLogsReq, opts ...grpc.CallOption) (*ListPointLogsResp, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.ListPointLogs(ctx, in, opts...)
}

// Notifications
func (m *defaultUserService) GetNotificationSettings(ctx context.Context, in *GetNotificationSettingsReq, opts ...grpc.CallOption) (*GetNotificationSettingsResp, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.GetNotificationSettings(ctx, in, opts...)
}

func (m *defaultUserService) UpdateNotificationSettings(ctx context.Context, in *UpdateNotificationSettingsReq, opts ...grpc.CallOption) (*UpdateNotificationSettingsResp, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.UpdateNotificationSettings(ctx, in, opts...)
}

// Feedback
func (m *defaultUserService) SubmitFeedback(ctx context.Context, in *SubmitFeedbackReq, opts ...grpc.CallOption) (*SubmitFeedbackResp, error) {
	client := v1.NewUserServiceClient(m.cli.Conn())
	return client.SubmitFeedback(ctx, in, opts...)
}
