FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin/task ./service/task/task.go

FROM alpine:3.20
RUN apk add --no-cache tzdata ca-certificates
WORKDIR /app
COPY --from=builder /app/bin/task .
COPY service/task/etc/task.yaml ./etc/
EXPOSE 9003
CMD ["./task", "-f", "etc/task.yaml"]
