FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin/user ./service/user/user.go

FROM alpine:3.20
RUN apk add --no-cache tzdata ca-certificates
WORKDIR /app
COPY --from=builder /app/bin/user .
COPY service/user/etc/user.yaml ./etc/
EXPOSE 9001
CMD ["./user", "-f", "etc/user.yaml"]
