FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin/post ./service/post/post.go

FROM alpine:3.20
RUN apk add --no-cache tzdata ca-certificates
WORKDIR /app
COPY --from=builder /app/bin/post .
COPY service/post/etc/post.yaml ./etc/
EXPOSE 9005
CMD ["./post", "-f", "etc/post.yaml"]
