// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: pb/cat/v1/cat.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatService_ApplyCreateCat_FullMethodName          = "/cat.CatService/ApplyCreateCat"
	CatService_CancelApplyCreateCat_FullMethodName    = "/cat.CatService/CancelApplyCreateCat"
	CatService_GetApplyDetail_FullMethodName          = "/cat.CatService/GetApplyDetail"
	CatService_ListMyApplies_FullMethodName           = "/cat.CatService/ListMyApplies"
	CatService_ApproveCreateCat_FullMethodName        = "/cat.CatService/ApproveCreateCat"
	CatService_RejectCreateCat_FullMethodName         = "/cat.CatService/RejectCreateCat"
	CatService_DirectCreateCat_FullMethodName         = "/cat.CatService/DirectCreateCat"
	CatService_ListPendingApplies_FullMethodName      = "/cat.CatService/ListPendingApplies"
	CatService_ListCats_FullMethodName                = "/cat.CatService/ListCats"
	CatService_ApplyAdopt_FullMethodName              = "/cat.CatService/ApplyAdopt"
	CatService_CancelAdoptApply_FullMethodName        = "/cat.CatService/CancelAdoptApply"
	CatService_GetAdoptApplyDetail_FullMethodName     = "/cat.CatService/GetAdoptApplyDetail"
	CatService_ListMyAdoptApplies_FullMethodName      = "/cat.CatService/ListMyAdoptApplies"
	CatService_ListMyAdoptions_FullMethodName         = "/cat.CatService/ListMyAdoptions"
	CatService_CompleteVisit_FullMethodName           = "/cat.CatService/CompleteVisit"
	CatService_ApproveAdopt_FullMethodName            = "/cat.CatService/ApproveAdopt"
	CatService_RejectAdopt_FullMethodName             = "/cat.CatService/RejectAdopt"
	CatService_ListPendingAdoptApplies_FullMethodName = "/cat.CatService/ListPendingAdoptApplies"
	CatService_CreateAdoption_FullMethodName          = "/cat.CatService/CreateAdoption"
	CatService_DirectAdopt_FullMethodName             = "/cat.CatService/DirectAdopt"
	CatService_GetAdoptionDetail_FullMethodName       = "/cat.CatService/GetAdoptionDetail"
	CatService_ListAdoptions_FullMethodName           = "/cat.CatService/ListAdoptions"
	CatService_UpdateAdoption_FullMethodName          = "/cat.CatService/UpdateAdoption"
	CatService_RecordHomeVisit_FullMethodName         = "/cat.CatService/RecordHomeVisit"
	CatService_RecordFollowUpVisit_FullMethodName     = "/cat.CatService/RecordFollowUpVisit"
	CatService_UpdateReturnStatus_FullMethodName      = "/cat.CatService/UpdateReturnStatus"
	CatService_ApplyCreateTask_FullMethodName         = "/cat.CatService/ApplyCreateTask"
	CatService_CancelTaskApply_FullMethodName         = "/cat.CatService/CancelTaskApply"
	CatService_GetTaskApplyDetail_FullMethodName      = "/cat.CatService/GetTaskApplyDetail"
	CatService_ListMyTaskApplies_FullMethodName       = "/cat.CatService/ListMyTaskApplies"
	CatService_ClaimTask_FullMethodName               = "/cat.CatService/ClaimTask"
	CatService_AbandonTask_FullMethodName             = "/cat.CatService/AbandonTask"
	CatService_CompleteTask_FullMethodName            = "/cat.CatService/CompleteTask"
	CatService_GetTaskDetail_FullMethodName           = "/cat.CatService/GetTaskDetail"
	CatService_ListTasks_FullMethodName               = "/cat.CatService/ListTasks"
	CatService_ListMyClaimedTasks_FullMethodName      = "/cat.CatService/ListMyClaimedTasks"
	CatService_ListMyCompletedTasks_FullMethodName    = "/cat.CatService/ListMyCompletedTasks"
	CatService_ApproveTaskApply_FullMethodName        = "/cat.CatService/ApproveTaskApply"
	CatService_RejectTaskApply_FullMethodName         = "/cat.CatService/RejectTaskApply"
	CatService_ListPendingTaskApplies_FullMethodName  = "/cat.CatService/ListPendingTaskApplies"
	CatService_DirectCreateTask_FullMethodName        = "/cat.CatService/DirectCreateTask"
	CatService_UpdateTask_FullMethodName              = "/cat.CatService/UpdateTask"
	CatService_CancelTask_FullMethodName              = "/cat.CatService/CancelTask"
	CatService_EscalateTaskUrgency_FullMethodName     = "/cat.CatService/EscalateTaskUrgency"
	CatService_GetTaskFlows_FullMethodName            = "/cat.CatService/GetTaskFlows"
	CatService_GetTaskLogs_FullMethodName             = "/cat.CatService/GetTaskLogs"
)

// CatServiceClient is the client API for CatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatServiceClient interface {
	// 志愿者
	ApplyCreateCat(ctx context.Context, in *ApplyCreateCatRequest, opts ...grpc.CallOption) (*ApplyCreateCatResponse, error)
	CancelApplyCreateCat(ctx context.Context, in *CancelApplyCreateCatRequest, opts ...grpc.CallOption) (*Response, error)
	GetApplyDetail(ctx context.Context, in *GetApplyDetailRequest, opts ...grpc.CallOption) (*GetApplyDetailResponse, error)
	ListMyApplies(ctx context.Context, in *ListMyAppliesRequest, opts ...grpc.CallOption) (*ListMyAppliesResponse, error)
	// 管理员
	ApproveCreateCat(ctx context.Context, in *ApproveCreateCatRequest, opts ...grpc.CallOption) (*ApproveCreateCatResponse, error)
	RejectCreateCat(ctx context.Context, in *RejectCreateCatRequest, opts ...grpc.CallOption) (*Response, error)
	DirectCreateCat(ctx context.Context, in *DirectCreateCatRequest, opts ...grpc.CallOption) (*DirectCreateCatResponse, error)
	ListPendingApplies(ctx context.Context, in *ListPendingAppliesRequest, opts ...grpc.CallOption) (*ListPendingAppliesResponse, error)
	ListCats(ctx context.Context, in *ListCatsReq, opts ...grpc.CallOption) (*ListCatsResp, error)
	// 申请领养
	ApplyAdopt(ctx context.Context, in *ApplyAdoptRequest, opts ...grpc.CallOption) (*ApplyAdoptResponse, error)
	// 取消申请
	CancelAdoptApply(ctx context.Context, in *CancelAdoptApplyRequest, opts ...grpc.CallOption) (*CancelAdoptApplyResponse, error)
	// 查看申请详情
	GetAdoptApplyDetail(ctx context.Context, in *GetAdoptApplyDetailRequest, opts ...grpc.CallOption) (*GetAdoptApplyDetailResponse, error)
	// 我的申请列表
	ListMyAdoptApplies(ctx context.Context, in *ListMyAdoptAppliesRequest, opts ...grpc.CallOption) (*ListMyAdoptAppliesResponse, error)
	// 我的领养记录
	ListMyAdoptions(ctx context.Context, in *ListMyAdoptionsRequest, opts ...grpc.CallOption) (*ListAdoptionsResponse, error)
	// 完成回访
	CompleteVisit(ctx context.Context, in *RecordFollowUpVisitRequest, opts ...grpc.CallOption) (*RecordFollowUpVisitResponse, error)
	// 审核通过
	ApproveAdopt(ctx context.Context, in *ApproveAdoptRequest, opts ...grpc.CallOption) (*ApproveAdoptResponse, error)
	// 审核拒绝
	RejectAdopt(ctx context.Context, in *RejectAdoptRequest, opts ...grpc.CallOption) (*RejectAdoptResponse, error)
	// 待审核列表
	ListPendingAdoptApplies(ctx context.Context, in *ListPendingAdoptAppliesRequest, opts ...grpc.CallOption) (*ListPendingAdoptAppliesResponse, error)
	// 从申请创建领养记录
	CreateAdoption(ctx context.Context, in *CreateAdoptionRequest, opts ...grpc.CallOption) (*CreateAdoptionResponse, error)
	// 直接领养
	DirectAdopt(ctx context.Context, in *DirectAdoptRequest, opts ...grpc.CallOption) (*DirectAdoptResponse, error)
	// 查看领养详情
	GetAdoptionDetail(ctx context.Context, in *GetAdoptionDetailRequest, opts ...grpc.CallOption) (*GetAdoptionDetailResponse, error)
	// 领养记录列表
	ListAdoptions(ctx context.Context, in *ListAdoptionsRequest, opts ...grpc.CallOption) (*ListAdoptionsResponse, error)
	// 更新领养信息
	UpdateAdoption(ctx context.Context, in *UpdateAdoptionRequest, opts ...grpc.CallOption) (*UpdateAdoptionResponse, error)
	// 记录家访
	RecordHomeVisit(ctx context.Context, in *RecordHomeVisitRequest, opts ...grpc.CallOption) (*RecordHomeVisitResponse, error)
	// 记录回访
	RecordFollowUpVisit(ctx context.Context, in *RecordFollowUpVisitRequest, opts ...grpc.CallOption) (*RecordFollowUpVisitResponse, error)
	// 更新退回状态
	UpdateReturnStatus(ctx context.Context, in *UpdateReturnStatusRequest, opts ...grpc.CallOption) (*UpdateReturnStatusResponse, error)
	// 申请创建任务
	ApplyCreateTask(ctx context.Context, in *ApplyCreateTaskRequest, opts ...grpc.CallOption) (*ApplyCreateTaskResponse, error)
	// 取消任务申请
	CancelTaskApply(ctx context.Context, in *CancelTaskApplyRequest, opts ...grpc.CallOption) (*CancelTaskApplyResponse, error)
	// 查看任务申请详情
	GetTaskApplyDetail(ctx context.Context, in *GetTaskApplyDetailRequest, opts ...grpc.CallOption) (*GetTaskApplyDetailResponse, error)
	// 我的任务申请列表
	ListMyTaskApplies(ctx context.Context, in *ListMyTaskAppliesRequest, opts ...grpc.CallOption) (*ListMyTaskAppliesResponse, error)
	// 认领任务
	ClaimTask(ctx context.Context, in *ClaimTaskRequest, opts ...grpc.CallOption) (*ClaimTaskResponse, error)
	// 放弃任务
	AbandonTask(ctx context.Context, in *AbandonTaskRequest, opts ...grpc.CallOption) (*AbandonTaskResponse, error)
	// 完成任务
	CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*CompleteTaskResponse, error)
	// 查看任务详情
	GetTaskDetail(ctx context.Context, in *GetTaskDetailRequest, opts ...grpc.CallOption) (*GetTaskDetailResponse, error)
	// 任务列表（公开查询）
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	// 我认领的任务列表
	ListMyClaimedTasks(ctx context.Context, in *ListMyClaimedTasksRequest, opts ...grpc.CallOption) (*ListMyClaimedTasksResponse, error)
	// 我完成的任务列表
	ListMyCompletedTasks(ctx context.Context, in *ListMyCompletedTasksRequest, opts ...grpc.CallOption) (*ListMyCompletedTasksResponse, error)
	// 审核通过任务申请
	ApproveTaskApply(ctx context.Context, in *ApproveTaskApplyRequest, opts ...grpc.CallOption) (*ApproveTaskApplyResponse, error)
	// 拒绝任务申请
	RejectTaskApply(ctx context.Context, in *RejectTaskApplyRequest, opts ...grpc.CallOption) (*RejectTaskApplyResponse, error)
	// 待审核任务申请列表
	ListPendingTaskApplies(ctx context.Context, in *ListPendingTaskAppliesRequest, opts ...grpc.CallOption) (*ListPendingTaskAppliesResponse, error)
	// 直接创建任务（跳过申请）
	DirectCreateTask(ctx context.Context, in *DirectCreateTaskRequest, opts ...grpc.CallOption) (*DirectCreateTaskResponse, error)
	// 更新任务
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error)
	// 取消任务
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
	// 升级任务紧急度
	EscalateTaskUrgency(ctx context.Context, in *EscalateTaskUrgencyRequest, opts ...grpc.CallOption) (*EscalateTaskUrgencyResponse, error)
	// 查看任务流转日志
	GetTaskFlows(ctx context.Context, in *GetTaskFlowsRequest, opts ...grpc.CallOption) (*GetTaskFlowsResponse, error)
	// 查看任务操作日志
	GetTaskLogs(ctx context.Context, in *GetTaskLogsRequest, opts ...grpc.CallOption) (*GetTaskLogsResponse, error)
}

type catServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatServiceClient(cc grpc.ClientConnInterface) CatServiceClient {
	return &catServiceClient{cc}
}

func (c *catServiceClient) ApplyCreateCat(ctx context.Context, in *ApplyCreateCatRequest, opts ...grpc.CallOption) (*ApplyCreateCatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyCreateCatResponse)
	err := c.cc.Invoke(ctx, CatService_ApplyCreateCat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) CancelApplyCreateCat(ctx context.Context, in *CancelApplyCreateCatRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, CatService_CancelApplyCreateCat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetApplyDetail(ctx context.Context, in *GetApplyDetailRequest, opts ...grpc.CallOption) (*GetApplyDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApplyDetailResponse)
	err := c.cc.Invoke(ctx, CatService_GetApplyDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListMyApplies(ctx context.Context, in *ListMyAppliesRequest, opts ...grpc.CallOption) (*ListMyAppliesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyAppliesResponse)
	err := c.cc.Invoke(ctx, CatService_ListMyApplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ApproveCreateCat(ctx context.Context, in *ApproveCreateCatRequest, opts ...grpc.CallOption) (*ApproveCreateCatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveCreateCatResponse)
	err := c.cc.Invoke(ctx, CatService_ApproveCreateCat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) RejectCreateCat(ctx context.Context, in *RejectCreateCatRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, CatService_RejectCreateCat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) DirectCreateCat(ctx context.Context, in *DirectCreateCatRequest, opts ...grpc.CallOption) (*DirectCreateCatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectCreateCatResponse)
	err := c.cc.Invoke(ctx, CatService_DirectCreateCat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListPendingApplies(ctx context.Context, in *ListPendingAppliesRequest, opts ...grpc.CallOption) (*ListPendingAppliesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingAppliesResponse)
	err := c.cc.Invoke(ctx, CatService_ListPendingApplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListCats(ctx context.Context, in *ListCatsReq, opts ...grpc.CallOption) (*ListCatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCatsResp)
	err := c.cc.Invoke(ctx, CatService_ListCats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ApplyAdopt(ctx context.Context, in *ApplyAdoptRequest, opts ...grpc.CallOption) (*ApplyAdoptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyAdoptResponse)
	err := c.cc.Invoke(ctx, CatService_ApplyAdopt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) CancelAdoptApply(ctx context.Context, in *CancelAdoptApplyRequest, opts ...grpc.CallOption) (*CancelAdoptApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelAdoptApplyResponse)
	err := c.cc.Invoke(ctx, CatService_CancelAdoptApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetAdoptApplyDetail(ctx context.Context, in *GetAdoptApplyDetailRequest, opts ...grpc.CallOption) (*GetAdoptApplyDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdoptApplyDetailResponse)
	err := c.cc.Invoke(ctx, CatService_GetAdoptApplyDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListMyAdoptApplies(ctx context.Context, in *ListMyAdoptAppliesRequest, opts ...grpc.CallOption) (*ListMyAdoptAppliesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyAdoptAppliesResponse)
	err := c.cc.Invoke(ctx, CatService_ListMyAdoptApplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListMyAdoptions(ctx context.Context, in *ListMyAdoptionsRequest, opts ...grpc.CallOption) (*ListAdoptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdoptionsResponse)
	err := c.cc.Invoke(ctx, CatService_ListMyAdoptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) CompleteVisit(ctx context.Context, in *RecordFollowUpVisitRequest, opts ...grpc.CallOption) (*RecordFollowUpVisitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordFollowUpVisitResponse)
	err := c.cc.Invoke(ctx, CatService_CompleteVisit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ApproveAdopt(ctx context.Context, in *ApproveAdoptRequest, opts ...grpc.CallOption) (*ApproveAdoptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveAdoptResponse)
	err := c.cc.Invoke(ctx, CatService_ApproveAdopt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) RejectAdopt(ctx context.Context, in *RejectAdoptRequest, opts ...grpc.CallOption) (*RejectAdoptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectAdoptResponse)
	err := c.cc.Invoke(ctx, CatService_RejectAdopt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListPendingAdoptApplies(ctx context.Context, in *ListPendingAdoptAppliesRequest, opts ...grpc.CallOption) (*ListPendingAdoptAppliesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingAdoptAppliesResponse)
	err := c.cc.Invoke(ctx, CatService_ListPendingAdoptApplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) CreateAdoption(ctx context.Context, in *CreateAdoptionRequest, opts ...grpc.CallOption) (*CreateAdoptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAdoptionResponse)
	err := c.cc.Invoke(ctx, CatService_CreateAdoption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) DirectAdopt(ctx context.Context, in *DirectAdoptRequest, opts ...grpc.CallOption) (*DirectAdoptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectAdoptResponse)
	err := c.cc.Invoke(ctx, CatService_DirectAdopt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetAdoptionDetail(ctx context.Context, in *GetAdoptionDetailRequest, opts ...grpc.CallOption) (*GetAdoptionDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdoptionDetailResponse)
	err := c.cc.Invoke(ctx, CatService_GetAdoptionDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListAdoptions(ctx context.Context, in *ListAdoptionsRequest, opts ...grpc.CallOption) (*ListAdoptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdoptionsResponse)
	err := c.cc.Invoke(ctx, CatService_ListAdoptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) UpdateAdoption(ctx context.Context, in *UpdateAdoptionRequest, opts ...grpc.CallOption) (*UpdateAdoptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdoptionResponse)
	err := c.cc.Invoke(ctx, CatService_UpdateAdoption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) RecordHomeVisit(ctx context.Context, in *RecordHomeVisitRequest, opts ...grpc.CallOption) (*RecordHomeVisitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordHomeVisitResponse)
	err := c.cc.Invoke(ctx, CatService_RecordHomeVisit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) RecordFollowUpVisit(ctx context.Context, in *RecordFollowUpVisitRequest, opts ...grpc.CallOption) (*RecordFollowUpVisitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordFollowUpVisitResponse)
	err := c.cc.Invoke(ctx, CatService_RecordFollowUpVisit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) UpdateReturnStatus(ctx context.Context, in *UpdateReturnStatusRequest, opts ...grpc.CallOption) (*UpdateReturnStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateReturnStatusResponse)
	err := c.cc.Invoke(ctx, CatService_UpdateReturnStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ApplyCreateTask(ctx context.Context, in *ApplyCreateTaskRequest, opts ...grpc.CallOption) (*ApplyCreateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyCreateTaskResponse)
	err := c.cc.Invoke(ctx, CatService_ApplyCreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) CancelTaskApply(ctx context.Context, in *CancelTaskApplyRequest, opts ...grpc.CallOption) (*CancelTaskApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTaskApplyResponse)
	err := c.cc.Invoke(ctx, CatService_CancelTaskApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetTaskApplyDetail(ctx context.Context, in *GetTaskApplyDetailRequest, opts ...grpc.CallOption) (*GetTaskApplyDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskApplyDetailResponse)
	err := c.cc.Invoke(ctx, CatService_GetTaskApplyDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListMyTaskApplies(ctx context.Context, in *ListMyTaskAppliesRequest, opts ...grpc.CallOption) (*ListMyTaskAppliesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyTaskAppliesResponse)
	err := c.cc.Invoke(ctx, CatService_ListMyTaskApplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ClaimTask(ctx context.Context, in *ClaimTaskRequest, opts ...grpc.CallOption) (*ClaimTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimTaskResponse)
	err := c.cc.Invoke(ctx, CatService_ClaimTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) AbandonTask(ctx context.Context, in *AbandonTaskRequest, opts ...grpc.CallOption) (*AbandonTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbandonTaskResponse)
	err := c.cc.Invoke(ctx, CatService_AbandonTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*CompleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteTaskResponse)
	err := c.cc.Invoke(ctx, CatService_CompleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetTaskDetail(ctx context.Context, in *GetTaskDetailRequest, opts ...grpc.CallOption) (*GetTaskDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDetailResponse)
	err := c.cc.Invoke(ctx, CatService_GetTaskDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, CatService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListMyClaimedTasks(ctx context.Context, in *ListMyClaimedTasksRequest, opts ...grpc.CallOption) (*ListMyClaimedTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyClaimedTasksResponse)
	err := c.cc.Invoke(ctx, CatService_ListMyClaimedTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListMyCompletedTasks(ctx context.Context, in *ListMyCompletedTasksRequest, opts ...grpc.CallOption) (*ListMyCompletedTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyCompletedTasksResponse)
	err := c.cc.Invoke(ctx, CatService_ListMyCompletedTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ApproveTaskApply(ctx context.Context, in *ApproveTaskApplyRequest, opts ...grpc.CallOption) (*ApproveTaskApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveTaskApplyResponse)
	err := c.cc.Invoke(ctx, CatService_ApproveTaskApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) RejectTaskApply(ctx context.Context, in *RejectTaskApplyRequest, opts ...grpc.CallOption) (*RejectTaskApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectTaskApplyResponse)
	err := c.cc.Invoke(ctx, CatService_RejectTaskApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListPendingTaskApplies(ctx context.Context, in *ListPendingTaskAppliesRequest, opts ...grpc.CallOption) (*ListPendingTaskAppliesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingTaskAppliesResponse)
	err := c.cc.Invoke(ctx, CatService_ListPendingTaskApplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) DirectCreateTask(ctx context.Context, in *DirectCreateTaskRequest, opts ...grpc.CallOption) (*DirectCreateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectCreateTaskResponse)
	err := c.cc.Invoke(ctx, CatService_DirectCreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTaskResponse)
	err := c.cc.Invoke(ctx, CatService_UpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTaskResponse)
	err := c.cc.Invoke(ctx, CatService_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) EscalateTaskUrgency(ctx context.Context, in *EscalateTaskUrgencyRequest, opts ...grpc.CallOption) (*EscalateTaskUrgencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EscalateTaskUrgencyResponse)
	err := c.cc.Invoke(ctx, CatService_EscalateTaskUrgency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetTaskFlows(ctx context.Context, in *GetTaskFlowsRequest, opts ...grpc.CallOption) (*GetTaskFlowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskFlowsResponse)
	err := c.cc.Invoke(ctx, CatService_GetTaskFlows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetTaskLogs(ctx context.Context, in *GetTaskLogsRequest, opts ...grpc.CallOption) (*GetTaskLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskLogsResponse)
	err := c.cc.Invoke(ctx, CatService_GetTaskLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatServiceServer is the server API for CatService service.
// All implementations must embed UnimplementedCatServiceServer
// for forward compatibility.
type CatServiceServer interface {
	// 志愿者
	ApplyCreateCat(context.Context, *ApplyCreateCatRequest) (*ApplyCreateCatResponse, error)
	CancelApplyCreateCat(context.Context, *CancelApplyCreateCatRequest) (*Response, error)
	GetApplyDetail(context.Context, *GetApplyDetailRequest) (*GetApplyDetailResponse, error)
	ListMyApplies(context.Context, *ListMyAppliesRequest) (*ListMyAppliesResponse, error)
	// 管理员
	ApproveCreateCat(context.Context, *ApproveCreateCatRequest) (*ApproveCreateCatResponse, error)
	RejectCreateCat(context.Context, *RejectCreateCatRequest) (*Response, error)
	DirectCreateCat(context.Context, *DirectCreateCatRequest) (*DirectCreateCatResponse, error)
	ListPendingApplies(context.Context, *ListPendingAppliesRequest) (*ListPendingAppliesResponse, error)
	ListCats(context.Context, *ListCatsReq) (*ListCatsResp, error)
	// 申请领养
	ApplyAdopt(context.Context, *ApplyAdoptRequest) (*ApplyAdoptResponse, error)
	// 取消申请
	CancelAdoptApply(context.Context, *CancelAdoptApplyRequest) (*CancelAdoptApplyResponse, error)
	// 查看申请详情
	GetAdoptApplyDetail(context.Context, *GetAdoptApplyDetailRequest) (*GetAdoptApplyDetailResponse, error)
	// 我的申请列表
	ListMyAdoptApplies(context.Context, *ListMyAdoptAppliesRequest) (*ListMyAdoptAppliesResponse, error)
	// 我的领养记录
	ListMyAdoptions(context.Context, *ListMyAdoptionsRequest) (*ListAdoptionsResponse, error)
	// 完成回访
	CompleteVisit(context.Context, *RecordFollowUpVisitRequest) (*RecordFollowUpVisitResponse, error)
	// 审核通过
	ApproveAdopt(context.Context, *ApproveAdoptRequest) (*ApproveAdoptResponse, error)
	// 审核拒绝
	RejectAdopt(context.Context, *RejectAdoptRequest) (*RejectAdoptResponse, error)
	// 待审核列表
	ListPendingAdoptApplies(context.Context, *ListPendingAdoptAppliesRequest) (*ListPendingAdoptAppliesResponse, error)
	// 从申请创建领养记录
	CreateAdoption(context.Context, *CreateAdoptionRequest) (*CreateAdoptionResponse, error)
	// 直接领养
	DirectAdopt(context.Context, *DirectAdoptRequest) (*DirectAdoptResponse, error)
	// 查看领养详情
	GetAdoptionDetail(context.Context, *GetAdoptionDetailRequest) (*GetAdoptionDetailResponse, error)
	// 领养记录列表
	ListAdoptions(context.Context, *ListAdoptionsRequest) (*ListAdoptionsResponse, error)
	// 更新领养信息
	UpdateAdoption(context.Context, *UpdateAdoptionRequest) (*UpdateAdoptionResponse, error)
	// 记录家访
	RecordHomeVisit(context.Context, *RecordHomeVisitRequest) (*RecordHomeVisitResponse, error)
	// 记录回访
	RecordFollowUpVisit(context.Context, *RecordFollowUpVisitRequest) (*RecordFollowUpVisitResponse, error)
	// 更新退回状态
	UpdateReturnStatus(context.Context, *UpdateReturnStatusRequest) (*UpdateReturnStatusResponse, error)
	// 申请创建任务
	ApplyCreateTask(context.Context, *ApplyCreateTaskRequest) (*ApplyCreateTaskResponse, error)
	// 取消任务申请
	CancelTaskApply(context.Context, *CancelTaskApplyRequest) (*CancelTaskApplyResponse, error)
	// 查看任务申请详情
	GetTaskApplyDetail(context.Context, *GetTaskApplyDetailRequest) (*GetTaskApplyDetailResponse, error)
	// 我的任务申请列表
	ListMyTaskApplies(context.Context, *ListMyTaskAppliesRequest) (*ListMyTaskAppliesResponse, error)
	// 认领任务
	ClaimTask(context.Context, *ClaimTaskRequest) (*ClaimTaskResponse, error)
	// 放弃任务
	AbandonTask(context.Context, *AbandonTaskRequest) (*AbandonTaskResponse, error)
	// 完成任务
	CompleteTask(context.Context, *CompleteTaskRequest) (*CompleteTaskResponse, error)
	// 查看任务详情
	GetTaskDetail(context.Context, *GetTaskDetailRequest) (*GetTaskDetailResponse, error)
	// 任务列表（公开查询）
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// 我认领的任务列表
	ListMyClaimedTasks(context.Context, *ListMyClaimedTasksRequest) (*ListMyClaimedTasksResponse, error)
	// 我完成的任务列表
	ListMyCompletedTasks(context.Context, *ListMyCompletedTasksRequest) (*ListMyCompletedTasksResponse, error)
	// 审核通过任务申请
	ApproveTaskApply(context.Context, *ApproveTaskApplyRequest) (*ApproveTaskApplyResponse, error)
	// 拒绝任务申请
	RejectTaskApply(context.Context, *RejectTaskApplyRequest) (*RejectTaskApplyResponse, error)
	// 待审核任务申请列表
	ListPendingTaskApplies(context.Context, *ListPendingTaskAppliesRequest) (*ListPendingTaskAppliesResponse, error)
	// 直接创建任务（跳过申请）
	DirectCreateTask(context.Context, *DirectCreateTaskRequest) (*DirectCreateTaskResponse, error)
	// 更新任务
	UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error)
	// 取消任务
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error)
	// 升级任务紧急度
	EscalateTaskUrgency(context.Context, *EscalateTaskUrgencyRequest) (*EscalateTaskUrgencyResponse, error)
	// 查看任务流转日志
	GetTaskFlows(context.Context, *GetTaskFlowsRequest) (*GetTaskFlowsResponse, error)
	// 查看任务操作日志
	GetTaskLogs(context.Context, *GetTaskLogsRequest) (*GetTaskLogsResponse, error)
	mustEmbedUnimplementedCatServiceServer()
}

// UnimplementedCatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatServiceServer struct{}

func (UnimplementedCatServiceServer) ApplyCreateCat(context.Context, *ApplyCreateCatRequest) (*ApplyCreateCatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyCreateCat not implemented")
}
func (UnimplementedCatServiceServer) CancelApplyCreateCat(context.Context, *CancelApplyCreateCatRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelApplyCreateCat not implemented")
}
func (UnimplementedCatServiceServer) GetApplyDetail(context.Context, *GetApplyDetailRequest) (*GetApplyDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplyDetail not implemented")
}
func (UnimplementedCatServiceServer) ListMyApplies(context.Context, *ListMyAppliesRequest) (*ListMyAppliesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyApplies not implemented")
}
func (UnimplementedCatServiceServer) ApproveCreateCat(context.Context, *ApproveCreateCatRequest) (*ApproveCreateCatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveCreateCat not implemented")
}
func (UnimplementedCatServiceServer) RejectCreateCat(context.Context, *RejectCreateCatRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectCreateCat not implemented")
}
func (UnimplementedCatServiceServer) DirectCreateCat(context.Context, *DirectCreateCatRequest) (*DirectCreateCatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DirectCreateCat not implemented")
}
func (UnimplementedCatServiceServer) ListPendingApplies(context.Context, *ListPendingAppliesRequest) (*ListPendingAppliesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingApplies not implemented")
}
func (UnimplementedCatServiceServer) ListCats(context.Context, *ListCatsReq) (*ListCatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCats not implemented")
}
func (UnimplementedCatServiceServer) ApplyAdopt(context.Context, *ApplyAdoptRequest) (*ApplyAdoptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyAdopt not implemented")
}
func (UnimplementedCatServiceServer) CancelAdoptApply(context.Context, *CancelAdoptApplyRequest) (*CancelAdoptApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelAdoptApply not implemented")
}
func (UnimplementedCatServiceServer) GetAdoptApplyDetail(context.Context, *GetAdoptApplyDetailRequest) (*GetAdoptApplyDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdoptApplyDetail not implemented")
}
func (UnimplementedCatServiceServer) ListMyAdoptApplies(context.Context, *ListMyAdoptAppliesRequest) (*ListMyAdoptAppliesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyAdoptApplies not implemented")
}
func (UnimplementedCatServiceServer) ListMyAdoptions(context.Context, *ListMyAdoptionsRequest) (*ListAdoptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyAdoptions not implemented")
}
func (UnimplementedCatServiceServer) CompleteVisit(context.Context, *RecordFollowUpVisitRequest) (*RecordFollowUpVisitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteVisit not implemented")
}
func (UnimplementedCatServiceServer) ApproveAdopt(context.Context, *ApproveAdoptRequest) (*ApproveAdoptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveAdopt not implemented")
}
func (UnimplementedCatServiceServer) RejectAdopt(context.Context, *RejectAdoptRequest) (*RejectAdoptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectAdopt not implemented")
}
func (UnimplementedCatServiceServer) ListPendingAdoptApplies(context.Context, *ListPendingAdoptAppliesRequest) (*ListPendingAdoptAppliesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingAdoptApplies not implemented")
}
func (UnimplementedCatServiceServer) CreateAdoption(context.Context, *CreateAdoptionRequest) (*CreateAdoptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdoption not implemented")
}
func (UnimplementedCatServiceServer) DirectAdopt(context.Context, *DirectAdoptRequest) (*DirectAdoptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DirectAdopt not implemented")
}
func (UnimplementedCatServiceServer) GetAdoptionDetail(context.Context, *GetAdoptionDetailRequest) (*GetAdoptionDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdoptionDetail not implemented")
}
func (UnimplementedCatServiceServer) ListAdoptions(context.Context, *ListAdoptionsRequest) (*ListAdoptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdoptions not implemented")
}
func (UnimplementedCatServiceServer) UpdateAdoption(context.Context, *UpdateAdoptionRequest) (*UpdateAdoptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdoption not implemented")
}
func (UnimplementedCatServiceServer) RecordHomeVisit(context.Context, *RecordHomeVisitRequest) (*RecordHomeVisitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordHomeVisit not implemented")
}
func (UnimplementedCatServiceServer) RecordFollowUpVisit(context.Context, *RecordFollowUpVisitRequest) (*RecordFollowUpVisitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordFollowUpVisit not implemented")
}
func (UnimplementedCatServiceServer) UpdateReturnStatus(context.Context, *UpdateReturnStatusRequest) (*UpdateReturnStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateReturnStatus not implemented")
}
func (UnimplementedCatServiceServer) ApplyCreateTask(context.Context, *ApplyCreateTaskRequest) (*ApplyCreateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyCreateTask not implemented")
}
func (UnimplementedCatServiceServer) CancelTaskApply(context.Context, *CancelTaskApplyRequest) (*CancelTaskApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTaskApply not implemented")
}
func (UnimplementedCatServiceServer) GetTaskApplyDetail(context.Context, *GetTaskApplyDetailRequest) (*GetTaskApplyDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskApplyDetail not implemented")
}
func (UnimplementedCatServiceServer) ListMyTaskApplies(context.Context, *ListMyTaskAppliesRequest) (*ListMyTaskAppliesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyTaskApplies not implemented")
}
func (UnimplementedCatServiceServer) ClaimTask(context.Context, *ClaimTaskRequest) (*ClaimTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimTask not implemented")
}
func (UnimplementedCatServiceServer) AbandonTask(context.Context, *AbandonTaskRequest) (*AbandonTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbandonTask not implemented")
}
func (UnimplementedCatServiceServer) CompleteTask(context.Context, *CompleteTaskRequest) (*CompleteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTask not implemented")
}
func (UnimplementedCatServiceServer) GetTaskDetail(context.Context, *GetTaskDetailRequest) (*GetTaskDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskDetail not implemented")
}
func (UnimplementedCatServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedCatServiceServer) ListMyClaimedTasks(context.Context, *ListMyClaimedTasksRequest) (*ListMyClaimedTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyClaimedTasks not implemented")
}
func (UnimplementedCatServiceServer) ListMyCompletedTasks(context.Context, *ListMyCompletedTasksRequest) (*ListMyCompletedTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyCompletedTasks not implemented")
}
func (UnimplementedCatServiceServer) ApproveTaskApply(context.Context, *ApproveTaskApplyRequest) (*ApproveTaskApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveTaskApply not implemented")
}
func (UnimplementedCatServiceServer) RejectTaskApply(context.Context, *RejectTaskApplyRequest) (*RejectTaskApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectTaskApply not implemented")
}
func (UnimplementedCatServiceServer) ListPendingTaskApplies(context.Context, *ListPendingTaskAppliesRequest) (*ListPendingTaskAppliesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingTaskApplies not implemented")
}
func (UnimplementedCatServiceServer) DirectCreateTask(context.Context, *DirectCreateTaskRequest) (*DirectCreateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DirectCreateTask not implemented")
}
func (UnimplementedCatServiceServer) UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedCatServiceServer) CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedCatServiceServer) EscalateTaskUrgency(context.Context, *EscalateTaskUrgencyRequest) (*EscalateTaskUrgencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EscalateTaskUrgency not implemented")
}
func (UnimplementedCatServiceServer) GetTaskFlows(context.Context, *GetTaskFlowsRequest) (*GetTaskFlowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskFlows not implemented")
}
func (UnimplementedCatServiceServer) GetTaskLogs(context.Context, *GetTaskLogsRequest) (*GetTaskLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskLogs not implemented")
}
func (UnimplementedCatServiceServer) mustEmbedUnimplementedCatServiceServer() {}
func (UnimplementedCatServiceServer) testEmbeddedByValue()                    {}

// UnsafeCatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatServiceServer will
// result in compilation errors.
type UnsafeCatServiceServer interface {
	mustEmbedUnimplementedCatServiceServer()
}

func RegisterCatServiceServer(s grpc.ServiceRegistrar, srv CatServiceServer) {
	// If the following call panics, it indicates UnimplementedCatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatService_ServiceDesc, srv)
}

func _CatService_ApplyCreateCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyCreateCatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ApplyCreateCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ApplyCreateCat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ApplyCreateCat(ctx, req.(*ApplyCreateCatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_CancelApplyCreateCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelApplyCreateCatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).CancelApplyCreateCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_CancelApplyCreateCat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).CancelApplyCreateCat(ctx, req.(*CancelApplyCreateCatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetApplyDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplyDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetApplyDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetApplyDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetApplyDetail(ctx, req.(*GetApplyDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListMyApplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyAppliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListMyApplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListMyApplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListMyApplies(ctx, req.(*ListMyAppliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ApproveCreateCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveCreateCatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ApproveCreateCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ApproveCreateCat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ApproveCreateCat(ctx, req.(*ApproveCreateCatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_RejectCreateCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectCreateCatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).RejectCreateCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_RejectCreateCat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).RejectCreateCat(ctx, req.(*RejectCreateCatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_DirectCreateCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectCreateCatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).DirectCreateCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_DirectCreateCat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).DirectCreateCat(ctx, req.(*DirectCreateCatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListPendingApplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingAppliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListPendingApplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListPendingApplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListPendingApplies(ctx, req.(*ListPendingAppliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListCats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListCats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListCats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListCats(ctx, req.(*ListCatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ApplyAdopt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyAdoptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ApplyAdopt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ApplyAdopt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ApplyAdopt(ctx, req.(*ApplyAdoptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_CancelAdoptApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAdoptApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).CancelAdoptApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_CancelAdoptApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).CancelAdoptApply(ctx, req.(*CancelAdoptApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetAdoptApplyDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdoptApplyDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetAdoptApplyDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetAdoptApplyDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetAdoptApplyDetail(ctx, req.(*GetAdoptApplyDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListMyAdoptApplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyAdoptAppliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListMyAdoptApplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListMyAdoptApplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListMyAdoptApplies(ctx, req.(*ListMyAdoptAppliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListMyAdoptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyAdoptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListMyAdoptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListMyAdoptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListMyAdoptions(ctx, req.(*ListMyAdoptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_CompleteVisit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordFollowUpVisitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).CompleteVisit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_CompleteVisit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).CompleteVisit(ctx, req.(*RecordFollowUpVisitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ApproveAdopt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveAdoptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ApproveAdopt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ApproveAdopt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ApproveAdopt(ctx, req.(*ApproveAdoptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_RejectAdopt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectAdoptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).RejectAdopt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_RejectAdopt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).RejectAdopt(ctx, req.(*RejectAdoptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListPendingAdoptApplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingAdoptAppliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListPendingAdoptApplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListPendingAdoptApplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListPendingAdoptApplies(ctx, req.(*ListPendingAdoptAppliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_CreateAdoption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdoptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).CreateAdoption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_CreateAdoption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).CreateAdoption(ctx, req.(*CreateAdoptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_DirectAdopt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectAdoptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).DirectAdopt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_DirectAdopt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).DirectAdopt(ctx, req.(*DirectAdoptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetAdoptionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdoptionDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetAdoptionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetAdoptionDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetAdoptionDetail(ctx, req.(*GetAdoptionDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListAdoptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdoptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListAdoptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListAdoptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListAdoptions(ctx, req.(*ListAdoptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_UpdateAdoption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdoptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).UpdateAdoption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_UpdateAdoption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).UpdateAdoption(ctx, req.(*UpdateAdoptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_RecordHomeVisit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordHomeVisitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).RecordHomeVisit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_RecordHomeVisit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).RecordHomeVisit(ctx, req.(*RecordHomeVisitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_RecordFollowUpVisit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordFollowUpVisitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).RecordFollowUpVisit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_RecordFollowUpVisit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).RecordFollowUpVisit(ctx, req.(*RecordFollowUpVisitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_UpdateReturnStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReturnStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).UpdateReturnStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_UpdateReturnStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).UpdateReturnStatus(ctx, req.(*UpdateReturnStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ApplyCreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyCreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ApplyCreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ApplyCreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ApplyCreateTask(ctx, req.(*ApplyCreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_CancelTaskApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).CancelTaskApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_CancelTaskApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).CancelTaskApply(ctx, req.(*CancelTaskApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetTaskApplyDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskApplyDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetTaskApplyDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetTaskApplyDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetTaskApplyDetail(ctx, req.(*GetTaskApplyDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListMyTaskApplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyTaskAppliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListMyTaskApplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListMyTaskApplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListMyTaskApplies(ctx, req.(*ListMyTaskAppliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ClaimTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ClaimTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ClaimTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ClaimTask(ctx, req.(*ClaimTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_AbandonTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).AbandonTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_AbandonTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).AbandonTask(ctx, req.(*AbandonTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_CompleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).CompleteTask(ctx, req.(*CompleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetTaskDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetTaskDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetTaskDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetTaskDetail(ctx, req.(*GetTaskDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListMyClaimedTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyClaimedTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListMyClaimedTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListMyClaimedTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListMyClaimedTasks(ctx, req.(*ListMyClaimedTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListMyCompletedTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyCompletedTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListMyCompletedTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListMyCompletedTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListMyCompletedTasks(ctx, req.(*ListMyCompletedTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ApproveTaskApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveTaskApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ApproveTaskApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ApproveTaskApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ApproveTaskApply(ctx, req.(*ApproveTaskApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_RejectTaskApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectTaskApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).RejectTaskApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_RejectTaskApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).RejectTaskApply(ctx, req.(*RejectTaskApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListPendingTaskApplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingTaskAppliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListPendingTaskApplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListPendingTaskApplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListPendingTaskApplies(ctx, req.(*ListPendingTaskAppliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_DirectCreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectCreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).DirectCreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_DirectCreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).DirectCreateTask(ctx, req.(*DirectCreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_EscalateTaskUrgency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EscalateTaskUrgencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).EscalateTaskUrgency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_EscalateTaskUrgency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).EscalateTaskUrgency(ctx, req.(*EscalateTaskUrgencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetTaskFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskFlowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetTaskFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetTaskFlows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetTaskFlows(ctx, req.(*GetTaskFlowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetTaskLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetTaskLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetTaskLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetTaskLogs(ctx, req.(*GetTaskLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatService_ServiceDesc is the grpc.ServiceDesc for CatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cat.CatService",
	HandlerType: (*CatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyCreateCat",
			Handler:    _CatService_ApplyCreateCat_Handler,
		},
		{
			MethodName: "CancelApplyCreateCat",
			Handler:    _CatService_CancelApplyCreateCat_Handler,
		},
		{
			MethodName: "GetApplyDetail",
			Handler:    _CatService_GetApplyDetail_Handler,
		},
		{
			MethodName: "ListMyApplies",
			Handler:    _CatService_ListMyApplies_Handler,
		},
		{
			MethodName: "ApproveCreateCat",
			Handler:    _CatService_ApproveCreateCat_Handler,
		},
		{
			MethodName: "RejectCreateCat",
			Handler:    _CatService_RejectCreateCat_Handler,
		},
		{
			MethodName: "DirectCreateCat",
			Handler:    _CatService_DirectCreateCat_Handler,
		},
		{
			MethodName: "ListPendingApplies",
			Handler:    _CatService_ListPendingApplies_Handler,
		},
		{
			MethodName: "ListCats",
			Handler:    _CatService_ListCats_Handler,
		},
		{
			MethodName: "ApplyAdopt",
			Handler:    _CatService_ApplyAdopt_Handler,
		},
		{
			MethodName: "CancelAdoptApply",
			Handler:    _CatService_CancelAdoptApply_Handler,
		},
		{
			MethodName: "GetAdoptApplyDetail",
			Handler:    _CatService_GetAdoptApplyDetail_Handler,
		},
		{
			MethodName: "ListMyAdoptApplies",
			Handler:    _CatService_ListMyAdoptApplies_Handler,
		},
		{
			MethodName: "ListMyAdoptions",
			Handler:    _CatService_ListMyAdoptions_Handler,
		},
		{
			MethodName: "CompleteVisit",
			Handler:    _CatService_CompleteVisit_Handler,
		},
		{
			MethodName: "ApproveAdopt",
			Handler:    _CatService_ApproveAdopt_Handler,
		},
		{
			MethodName: "RejectAdopt",
			Handler:    _CatService_RejectAdopt_Handler,
		},
		{
			MethodName: "ListPendingAdoptApplies",
			Handler:    _CatService_ListPendingAdoptApplies_Handler,
		},
		{
			MethodName: "CreateAdoption",
			Handler:    _CatService_CreateAdoption_Handler,
		},
		{
			MethodName: "DirectAdopt",
			Handler:    _CatService_DirectAdopt_Handler,
		},
		{
			MethodName: "GetAdoptionDetail",
			Handler:    _CatService_GetAdoptionDetail_Handler,
		},
		{
			MethodName: "ListAdoptions",
			Handler:    _CatService_ListAdoptions_Handler,
		},
		{
			MethodName: "UpdateAdoption",
			Handler:    _CatService_UpdateAdoption_Handler,
		},
		{
			MethodName: "RecordHomeVisit",
			Handler:    _CatService_RecordHomeVisit_Handler,
		},
		{
			MethodName: "RecordFollowUpVisit",
			Handler:    _CatService_RecordFollowUpVisit_Handler,
		},
		{
			MethodName: "UpdateReturnStatus",
			Handler:    _CatService_UpdateReturnStatus_Handler,
		},
		{
			MethodName: "ApplyCreateTask",
			Handler:    _CatService_ApplyCreateTask_Handler,
		},
		{
			MethodName: "CancelTaskApply",
			Handler:    _CatService_CancelTaskApply_Handler,
		},
		{
			MethodName: "GetTaskApplyDetail",
			Handler:    _CatService_GetTaskApplyDetail_Handler,
		},
		{
			MethodName: "ListMyTaskApplies",
			Handler:    _CatService_ListMyTaskApplies_Handler,
		},
		{
			MethodName: "ClaimTask",
			Handler:    _CatService_ClaimTask_Handler,
		},
		{
			MethodName: "AbandonTask",
			Handler:    _CatService_AbandonTask_Handler,
		},
		{
			MethodName: "CompleteTask",
			Handler:    _CatService_CompleteTask_Handler,
		},
		{
			MethodName: "GetTaskDetail",
			Handler:    _CatService_GetTaskDetail_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _CatService_ListTasks_Handler,
		},
		{
			MethodName: "ListMyClaimedTasks",
			Handler:    _CatService_ListMyClaimedTasks_Handler,
		},
		{
			MethodName: "ListMyCompletedTasks",
			Handler:    _CatService_ListMyCompletedTasks_Handler,
		},
		{
			MethodName: "ApproveTaskApply",
			Handler:    _CatService_ApproveTaskApply_Handler,
		},
		{
			MethodName: "RejectTaskApply",
			Handler:    _CatService_RejectTaskApply_Handler,
		},
		{
			MethodName: "ListPendingTaskApplies",
			Handler:    _CatService_ListPendingTaskApplies_Handler,
		},
		{
			MethodName: "DirectCreateTask",
			Handler:    _CatService_DirectCreateTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _CatService_UpdateTask_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _CatService_CancelTask_Handler,
		},
		{
			MethodName: "EscalateTaskUrgency",
			Handler:    _CatService_EscalateTaskUrgency_Handler,
		},
		{
			MethodName: "GetTaskFlows",
			Handler:    _CatService_GetTaskFlows_Handler,
		},
		{
			MethodName: "GetTaskLogs",
			Handler:    _CatService_GetTaskLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/cat/v1/cat.proto",
}
