// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: pb/cat/v1/cat.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatService_ApplyCreateCat_FullMethodName              = "/cat.CatService/ApplyCreateCat"
	CatService_ApplyUpdateCatInfo_FullMethodName          = "/cat.CatService/ApplyUpdateCatInfo"
	CatService_GetMyCreateCatApplyDetail_FullMethodName   = "/cat.CatService/GetMyCreateCatApplyDetail"
	CatService_GetMyUpdateCatApplyDetail_FullMethodName   = "/cat.CatService/GetMyUpdateCatApplyDetail"
	CatService_ApplyAddMedicalRecord_FullMethodName       = "/cat.CatService/ApplyAddMedicalRecord"
	CatService_ApplyAddRescueRecord_FullMethodName        = "/cat.CatService/ApplyAddRescueRecord"
	CatService_ApplyCreateCatTask_FullMethodName          = "/cat.CatService/ApplyCreateCatTask"
	CatService_ClaimCatTask_FullMethodName                = "/cat.CatService/ClaimCatTask"
	CatService_AbandonCatTask_FullMethodName              = "/cat.CatService/AbandonCatTask"
	CatService_UploadTaskProgress_FullMethodName          = "/cat.CatService/UploadTaskProgress"
	CatService_ApproveCreateCat_FullMethodName            = "/cat.CatService/ApproveCreateCat"
	CatService_RejectCreateCat_FullMethodName             = "/cat.CatService/RejectCreateCat"
	CatService_GetCreateCatApplyDetail_FullMethodName     = "/cat.CatService/GetCreateCatApplyDetail"
	CatService_ListCreateCatApply_FullMethodName          = "/cat.CatService/ListCreateCatApply"
	CatService_ApproveUpdateCatInfo_FullMethodName        = "/cat.CatService/ApproveUpdateCatInfo"
	CatService_RejectUpdateCatInfo_FullMethodName         = "/cat.CatService/RejectUpdateCatInfo"
	CatService_GetUpdateCatApplyDetail_FullMethodName     = "/cat.CatService/GetUpdateCatApplyDetail"
	CatService_ListUpdateCatApply_FullMethodName          = "/cat.CatService/ListUpdateCatApply"
	CatService_ApproveMedicalRecord_FullMethodName        = "/cat.CatService/ApproveMedicalRecord"
	CatService_RejectMedicalRecord_FullMethodName         = "/cat.CatService/RejectMedicalRecord"
	CatService_ApproveCreateCatTask_FullMethodName        = "/cat.CatService/ApproveCreateCatTask"
	CatService_RejectCreateCatTask_FullMethodName         = "/cat.CatService/RejectCreateCatTask"
	CatService_GetCreateCatTaskApplyDetail_FullMethodName = "/cat.CatService/GetCreateCatTaskApplyDetail"
	CatService_ListCreateCatTaskApply_FullMethodName      = "/cat.CatService/ListCreateCatTaskApply"
	CatService_CreateCatTask_FullMethodName               = "/cat.CatService/CreateCatTask"
	CatService_UpdateCatTaskStatus_FullMethodName         = "/cat.CatService/UpdateCatTaskStatus"
	CatService_UpdateAdoptionStatus_FullMethodName        = "/cat.CatService/UpdateAdoptionStatus"
	CatService_GetCatDetail_FullMethodName                = "/cat.CatService/GetCatDetail"
	CatService_ListCats_FullMethodName                    = "/cat.CatService/ListCats"
	CatService_ListCatTasks_FullMethodName                = "/cat.CatService/ListCatTasks"
)

// CatServiceClient is the client API for CatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatServiceClient interface {
	// 申请创建小猫档案
	ApplyCreateCat(ctx context.Context, in *ApplyCreateCatRequest, opts ...grpc.CallOption) (*ApplyCreateCatResponse, error)
	// 申请修改猫咪档案信息
	ApplyUpdateCatInfo(ctx context.Context, in *ApplyUpdateCatInfoRequest, opts ...grpc.CallOption) (*ApplyUpdateCatInfoResponse, error)
	// 查看自己提交的创建申请详情
	GetMyCreateCatApplyDetail(ctx context.Context, in *GetMyCreateCatApplyDetailRequest, opts ...grpc.CallOption) (*GetMyCreateCatApplyDetailResponse, error)
	// 查看自己提交的修改申请详情
	GetMyUpdateCatApplyDetail(ctx context.Context, in *GetMyUpdateCatApplyDetailRequest, opts ...grpc.CallOption) (*GetMyUpdateCatApplyDetailResponse, error)
	// 申请新增医疗记录
	ApplyAddMedicalRecord(ctx context.Context, in *ApplyAddMedicalRecordRequest, opts ...grpc.CallOption) (*ApplyAddMedicalRecordResponse, error)
	// 申请新增救助记录
	ApplyAddRescueRecord(ctx context.Context, in *ApplyAddRescueRecordRequest, opts ...grpc.CallOption) (*ApplyAddRescueRecordResponse, error)
	// 申请创建任务
	ApplyCreateCatTask(ctx context.Context, in *ApplyCreateCatTaskRequest, opts ...grpc.CallOption) (*ApplyCreateCatTaskResponse, error)
	// 申请认领任务
	ClaimCatTask(ctx context.Context, in *ClaimCatTaskRequest, opts ...grpc.CallOption) (*ClaimCatTaskResponse, error)
	// 申请放弃任务
	AbandonCatTask(ctx context.Context, in *AbandonCatTaskRequest, opts ...grpc.CallOption) (*AbandonCatTaskResponse, error)
	// 上传任务进度（图片/备注）
	UploadTaskProgress(ctx context.Context, in *UploadTaskProgressRequest, opts ...grpc.CallOption) (*UploadTaskProgressResponse, error)
	ApproveCreateCat(ctx context.Context, in *ApproveCreateCatRequest, opts ...grpc.CallOption) (*ApproveCreateCatResponse, error)
	RejectCreateCat(ctx context.Context, in *RejectCreateCatRequest, opts ...grpc.CallOption) (*RejectCreateCatResponse, error)
	GetCreateCatApplyDetail(ctx context.Context, in *GetCreateCatApplyDetailRequest, opts ...grpc.CallOption) (*GetCreateCatApplyDetailResponse, error)
	ListCreateCatApply(ctx context.Context, in *ListCreateCatApplyRequest, opts ...grpc.CallOption) (*ListCreateCatApplyResponse, error)
	ApproveUpdateCatInfo(ctx context.Context, in *ApproveUpdateCatInfoRequest, opts ...grpc.CallOption) (*ApproveUpdateCatInfoResponse, error)
	RejectUpdateCatInfo(ctx context.Context, in *RejectUpdateCatInfoRequest, opts ...grpc.CallOption) (*RejectUpdateCatInfoResponse, error)
	GetUpdateCatApplyDetail(ctx context.Context, in *GetUpdateCatApplyDetailRequest, opts ...grpc.CallOption) (*GetUpdateCatApplyDetailResponse, error)
	ListUpdateCatApply(ctx context.Context, in *ListUpdateCatApplyRequest, opts ...grpc.CallOption) (*ListUpdateCatApplyResponse, error)
	ApproveMedicalRecord(ctx context.Context, in *ApproveMedicalRecordRequest, opts ...grpc.CallOption) (*ApproveMedicalRecordResponse, error)
	RejectMedicalRecord(ctx context.Context, in *RejectMedicalRecordRequest, opts ...grpc.CallOption) (*RejectMedicalRecordResponse, error)
	// 管理员审核志愿者任务申请
	ApproveCreateCatTask(ctx context.Context, in *ApproveCreateCatTaskRequest, opts ...grpc.CallOption) (*ApproveCreateCatTaskResponse, error)
	RejectCreateCatTask(ctx context.Context, in *RejectCreateCatTaskRequest, opts ...grpc.CallOption) (*RejectCreateCatTaskResponse, error)
	GetCreateCatTaskApplyDetail(ctx context.Context, in *GetCreateCatTaskApplyDetailRequest, opts ...grpc.CallOption) (*GetCreateCatTaskApplyDetailResponse, error)
	ListCreateCatTaskApply(ctx context.Context, in *ListCreateCatTaskApplyRequest, opts ...grpc.CallOption) (*ListCreateCatTaskApplyResponse, error)
	// 管理员直接创建正式任务（无需审核）
	CreateCatTask(ctx context.Context, in *CreateCatTaskRequest, opts ...grpc.CallOption) (*CreateCatTaskResponse, error)
	// 管理员更新任务状态
	UpdateCatTaskStatus(ctx context.Context, in *UpdateCatTaskStatusRequest, opts ...grpc.CallOption) (*UpdateCatTaskStatusResponse, error)
	UpdateAdoptionStatus(ctx context.Context, in *UpdateAdoptionStatusRequest, opts ...grpc.CallOption) (*UpdateAdoptionStatusResponse, error)
	// 猫咪详情
	GetCatDetail(ctx context.Context, in *GetCatDetailRequest, opts ...grpc.CallOption) (*GetCatDetailResponse, error)
	// 猫咪列表
	ListCats(ctx context.Context, in *ListCatsRequest, opts ...grpc.CallOption) (*ListCatsResponse, error)
	// 正式任务列表
	ListCatTasks(ctx context.Context, in *ListCatTasksRequest, opts ...grpc.CallOption) (*ListCatTasksResponse, error)
}

type catServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatServiceClient(cc grpc.ClientConnInterface) CatServiceClient {
	return &catServiceClient{cc}
}

func (c *catServiceClient) ApplyCreateCat(ctx context.Context, in *ApplyCreateCatRequest, opts ...grpc.CallOption) (*ApplyCreateCatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyCreateCatResponse)
	err := c.cc.Invoke(ctx, CatService_ApplyCreateCat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ApplyUpdateCatInfo(ctx context.Context, in *ApplyUpdateCatInfoRequest, opts ...grpc.CallOption) (*ApplyUpdateCatInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyUpdateCatInfoResponse)
	err := c.cc.Invoke(ctx, CatService_ApplyUpdateCatInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetMyCreateCatApplyDetail(ctx context.Context, in *GetMyCreateCatApplyDetailRequest, opts ...grpc.CallOption) (*GetMyCreateCatApplyDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyCreateCatApplyDetailResponse)
	err := c.cc.Invoke(ctx, CatService_GetMyCreateCatApplyDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetMyUpdateCatApplyDetail(ctx context.Context, in *GetMyUpdateCatApplyDetailRequest, opts ...grpc.CallOption) (*GetMyUpdateCatApplyDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyUpdateCatApplyDetailResponse)
	err := c.cc.Invoke(ctx, CatService_GetMyUpdateCatApplyDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ApplyAddMedicalRecord(ctx context.Context, in *ApplyAddMedicalRecordRequest, opts ...grpc.CallOption) (*ApplyAddMedicalRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyAddMedicalRecordResponse)
	err := c.cc.Invoke(ctx, CatService_ApplyAddMedicalRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ApplyAddRescueRecord(ctx context.Context, in *ApplyAddRescueRecordRequest, opts ...grpc.CallOption) (*ApplyAddRescueRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyAddRescueRecordResponse)
	err := c.cc.Invoke(ctx, CatService_ApplyAddRescueRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ApplyCreateCatTask(ctx context.Context, in *ApplyCreateCatTaskRequest, opts ...grpc.CallOption) (*ApplyCreateCatTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyCreateCatTaskResponse)
	err := c.cc.Invoke(ctx, CatService_ApplyCreateCatTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ClaimCatTask(ctx context.Context, in *ClaimCatTaskRequest, opts ...grpc.CallOption) (*ClaimCatTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimCatTaskResponse)
	err := c.cc.Invoke(ctx, CatService_ClaimCatTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) AbandonCatTask(ctx context.Context, in *AbandonCatTaskRequest, opts ...grpc.CallOption) (*AbandonCatTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbandonCatTaskResponse)
	err := c.cc.Invoke(ctx, CatService_AbandonCatTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) UploadTaskProgress(ctx context.Context, in *UploadTaskProgressRequest, opts ...grpc.CallOption) (*UploadTaskProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadTaskProgressResponse)
	err := c.cc.Invoke(ctx, CatService_UploadTaskProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ApproveCreateCat(ctx context.Context, in *ApproveCreateCatRequest, opts ...grpc.CallOption) (*ApproveCreateCatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveCreateCatResponse)
	err := c.cc.Invoke(ctx, CatService_ApproveCreateCat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) RejectCreateCat(ctx context.Context, in *RejectCreateCatRequest, opts ...grpc.CallOption) (*RejectCreateCatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectCreateCatResponse)
	err := c.cc.Invoke(ctx, CatService_RejectCreateCat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetCreateCatApplyDetail(ctx context.Context, in *GetCreateCatApplyDetailRequest, opts ...grpc.CallOption) (*GetCreateCatApplyDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCreateCatApplyDetailResponse)
	err := c.cc.Invoke(ctx, CatService_GetCreateCatApplyDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListCreateCatApply(ctx context.Context, in *ListCreateCatApplyRequest, opts ...grpc.CallOption) (*ListCreateCatApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCreateCatApplyResponse)
	err := c.cc.Invoke(ctx, CatService_ListCreateCatApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ApproveUpdateCatInfo(ctx context.Context, in *ApproveUpdateCatInfoRequest, opts ...grpc.CallOption) (*ApproveUpdateCatInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveUpdateCatInfoResponse)
	err := c.cc.Invoke(ctx, CatService_ApproveUpdateCatInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) RejectUpdateCatInfo(ctx context.Context, in *RejectUpdateCatInfoRequest, opts ...grpc.CallOption) (*RejectUpdateCatInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectUpdateCatInfoResponse)
	err := c.cc.Invoke(ctx, CatService_RejectUpdateCatInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetUpdateCatApplyDetail(ctx context.Context, in *GetUpdateCatApplyDetailRequest, opts ...grpc.CallOption) (*GetUpdateCatApplyDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUpdateCatApplyDetailResponse)
	err := c.cc.Invoke(ctx, CatService_GetUpdateCatApplyDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListUpdateCatApply(ctx context.Context, in *ListUpdateCatApplyRequest, opts ...grpc.CallOption) (*ListUpdateCatApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUpdateCatApplyResponse)
	err := c.cc.Invoke(ctx, CatService_ListUpdateCatApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ApproveMedicalRecord(ctx context.Context, in *ApproveMedicalRecordRequest, opts ...grpc.CallOption) (*ApproveMedicalRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveMedicalRecordResponse)
	err := c.cc.Invoke(ctx, CatService_ApproveMedicalRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) RejectMedicalRecord(ctx context.Context, in *RejectMedicalRecordRequest, opts ...grpc.CallOption) (*RejectMedicalRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectMedicalRecordResponse)
	err := c.cc.Invoke(ctx, CatService_RejectMedicalRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ApproveCreateCatTask(ctx context.Context, in *ApproveCreateCatTaskRequest, opts ...grpc.CallOption) (*ApproveCreateCatTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveCreateCatTaskResponse)
	err := c.cc.Invoke(ctx, CatService_ApproveCreateCatTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) RejectCreateCatTask(ctx context.Context, in *RejectCreateCatTaskRequest, opts ...grpc.CallOption) (*RejectCreateCatTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectCreateCatTaskResponse)
	err := c.cc.Invoke(ctx, CatService_RejectCreateCatTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetCreateCatTaskApplyDetail(ctx context.Context, in *GetCreateCatTaskApplyDetailRequest, opts ...grpc.CallOption) (*GetCreateCatTaskApplyDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCreateCatTaskApplyDetailResponse)
	err := c.cc.Invoke(ctx, CatService_GetCreateCatTaskApplyDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListCreateCatTaskApply(ctx context.Context, in *ListCreateCatTaskApplyRequest, opts ...grpc.CallOption) (*ListCreateCatTaskApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCreateCatTaskApplyResponse)
	err := c.cc.Invoke(ctx, CatService_ListCreateCatTaskApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) CreateCatTask(ctx context.Context, in *CreateCatTaskRequest, opts ...grpc.CallOption) (*CreateCatTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCatTaskResponse)
	err := c.cc.Invoke(ctx, CatService_CreateCatTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) UpdateCatTaskStatus(ctx context.Context, in *UpdateCatTaskStatusRequest, opts ...grpc.CallOption) (*UpdateCatTaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCatTaskStatusResponse)
	err := c.cc.Invoke(ctx, CatService_UpdateCatTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) UpdateAdoptionStatus(ctx context.Context, in *UpdateAdoptionStatusRequest, opts ...grpc.CallOption) (*UpdateAdoptionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdoptionStatusResponse)
	err := c.cc.Invoke(ctx, CatService_UpdateAdoptionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) GetCatDetail(ctx context.Context, in *GetCatDetailRequest, opts ...grpc.CallOption) (*GetCatDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCatDetailResponse)
	err := c.cc.Invoke(ctx, CatService_GetCatDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListCats(ctx context.Context, in *ListCatsRequest, opts ...grpc.CallOption) (*ListCatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCatsResponse)
	err := c.cc.Invoke(ctx, CatService_ListCats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catServiceClient) ListCatTasks(ctx context.Context, in *ListCatTasksRequest, opts ...grpc.CallOption) (*ListCatTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCatTasksResponse)
	err := c.cc.Invoke(ctx, CatService_ListCatTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatServiceServer is the server API for CatService service.
// All implementations must embed UnimplementedCatServiceServer
// for forward compatibility.
type CatServiceServer interface {
	// 申请创建小猫档案
	ApplyCreateCat(context.Context, *ApplyCreateCatRequest) (*ApplyCreateCatResponse, error)
	// 申请修改猫咪档案信息
	ApplyUpdateCatInfo(context.Context, *ApplyUpdateCatInfoRequest) (*ApplyUpdateCatInfoResponse, error)
	// 查看自己提交的创建申请详情
	GetMyCreateCatApplyDetail(context.Context, *GetMyCreateCatApplyDetailRequest) (*GetMyCreateCatApplyDetailResponse, error)
	// 查看自己提交的修改申请详情
	GetMyUpdateCatApplyDetail(context.Context, *GetMyUpdateCatApplyDetailRequest) (*GetMyUpdateCatApplyDetailResponse, error)
	// 申请新增医疗记录
	ApplyAddMedicalRecord(context.Context, *ApplyAddMedicalRecordRequest) (*ApplyAddMedicalRecordResponse, error)
	// 申请新增救助记录
	ApplyAddRescueRecord(context.Context, *ApplyAddRescueRecordRequest) (*ApplyAddRescueRecordResponse, error)
	// 申请创建任务
	ApplyCreateCatTask(context.Context, *ApplyCreateCatTaskRequest) (*ApplyCreateCatTaskResponse, error)
	// 申请认领任务
	ClaimCatTask(context.Context, *ClaimCatTaskRequest) (*ClaimCatTaskResponse, error)
	// 申请放弃任务
	AbandonCatTask(context.Context, *AbandonCatTaskRequest) (*AbandonCatTaskResponse, error)
	// 上传任务进度（图片/备注）
	UploadTaskProgress(context.Context, *UploadTaskProgressRequest) (*UploadTaskProgressResponse, error)
	ApproveCreateCat(context.Context, *ApproveCreateCatRequest) (*ApproveCreateCatResponse, error)
	RejectCreateCat(context.Context, *RejectCreateCatRequest) (*RejectCreateCatResponse, error)
	GetCreateCatApplyDetail(context.Context, *GetCreateCatApplyDetailRequest) (*GetCreateCatApplyDetailResponse, error)
	ListCreateCatApply(context.Context, *ListCreateCatApplyRequest) (*ListCreateCatApplyResponse, error)
	ApproveUpdateCatInfo(context.Context, *ApproveUpdateCatInfoRequest) (*ApproveUpdateCatInfoResponse, error)
	RejectUpdateCatInfo(context.Context, *RejectUpdateCatInfoRequest) (*RejectUpdateCatInfoResponse, error)
	GetUpdateCatApplyDetail(context.Context, *GetUpdateCatApplyDetailRequest) (*GetUpdateCatApplyDetailResponse, error)
	ListUpdateCatApply(context.Context, *ListUpdateCatApplyRequest) (*ListUpdateCatApplyResponse, error)
	ApproveMedicalRecord(context.Context, *ApproveMedicalRecordRequest) (*ApproveMedicalRecordResponse, error)
	RejectMedicalRecord(context.Context, *RejectMedicalRecordRequest) (*RejectMedicalRecordResponse, error)
	// 管理员审核志愿者任务申请
	ApproveCreateCatTask(context.Context, *ApproveCreateCatTaskRequest) (*ApproveCreateCatTaskResponse, error)
	RejectCreateCatTask(context.Context, *RejectCreateCatTaskRequest) (*RejectCreateCatTaskResponse, error)
	GetCreateCatTaskApplyDetail(context.Context, *GetCreateCatTaskApplyDetailRequest) (*GetCreateCatTaskApplyDetailResponse, error)
	ListCreateCatTaskApply(context.Context, *ListCreateCatTaskApplyRequest) (*ListCreateCatTaskApplyResponse, error)
	// 管理员直接创建正式任务（无需审核）
	CreateCatTask(context.Context, *CreateCatTaskRequest) (*CreateCatTaskResponse, error)
	// 管理员更新任务状态
	UpdateCatTaskStatus(context.Context, *UpdateCatTaskStatusRequest) (*UpdateCatTaskStatusResponse, error)
	UpdateAdoptionStatus(context.Context, *UpdateAdoptionStatusRequest) (*UpdateAdoptionStatusResponse, error)
	// 猫咪详情
	GetCatDetail(context.Context, *GetCatDetailRequest) (*GetCatDetailResponse, error)
	// 猫咪列表
	ListCats(context.Context, *ListCatsRequest) (*ListCatsResponse, error)
	// 正式任务列表
	ListCatTasks(context.Context, *ListCatTasksRequest) (*ListCatTasksResponse, error)
	mustEmbedUnimplementedCatServiceServer()
}

// UnimplementedCatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatServiceServer struct{}

func (UnimplementedCatServiceServer) ApplyCreateCat(context.Context, *ApplyCreateCatRequest) (*ApplyCreateCatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyCreateCat not implemented")
}
func (UnimplementedCatServiceServer) ApplyUpdateCatInfo(context.Context, *ApplyUpdateCatInfoRequest) (*ApplyUpdateCatInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyUpdateCatInfo not implemented")
}
func (UnimplementedCatServiceServer) GetMyCreateCatApplyDetail(context.Context, *GetMyCreateCatApplyDetailRequest) (*GetMyCreateCatApplyDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyCreateCatApplyDetail not implemented")
}
func (UnimplementedCatServiceServer) GetMyUpdateCatApplyDetail(context.Context, *GetMyUpdateCatApplyDetailRequest) (*GetMyUpdateCatApplyDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyUpdateCatApplyDetail not implemented")
}
func (UnimplementedCatServiceServer) ApplyAddMedicalRecord(context.Context, *ApplyAddMedicalRecordRequest) (*ApplyAddMedicalRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyAddMedicalRecord not implemented")
}
func (UnimplementedCatServiceServer) ApplyAddRescueRecord(context.Context, *ApplyAddRescueRecordRequest) (*ApplyAddRescueRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyAddRescueRecord not implemented")
}
func (UnimplementedCatServiceServer) ApplyCreateCatTask(context.Context, *ApplyCreateCatTaskRequest) (*ApplyCreateCatTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyCreateCatTask not implemented")
}
func (UnimplementedCatServiceServer) ClaimCatTask(context.Context, *ClaimCatTaskRequest) (*ClaimCatTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimCatTask not implemented")
}
func (UnimplementedCatServiceServer) AbandonCatTask(context.Context, *AbandonCatTaskRequest) (*AbandonCatTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbandonCatTask not implemented")
}
func (UnimplementedCatServiceServer) UploadTaskProgress(context.Context, *UploadTaskProgressRequest) (*UploadTaskProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadTaskProgress not implemented")
}
func (UnimplementedCatServiceServer) ApproveCreateCat(context.Context, *ApproveCreateCatRequest) (*ApproveCreateCatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveCreateCat not implemented")
}
func (UnimplementedCatServiceServer) RejectCreateCat(context.Context, *RejectCreateCatRequest) (*RejectCreateCatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectCreateCat not implemented")
}
func (UnimplementedCatServiceServer) GetCreateCatApplyDetail(context.Context, *GetCreateCatApplyDetailRequest) (*GetCreateCatApplyDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCreateCatApplyDetail not implemented")
}
func (UnimplementedCatServiceServer) ListCreateCatApply(context.Context, *ListCreateCatApplyRequest) (*ListCreateCatApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCreateCatApply not implemented")
}
func (UnimplementedCatServiceServer) ApproveUpdateCatInfo(context.Context, *ApproveUpdateCatInfoRequest) (*ApproveUpdateCatInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveUpdateCatInfo not implemented")
}
func (UnimplementedCatServiceServer) RejectUpdateCatInfo(context.Context, *RejectUpdateCatInfoRequest) (*RejectUpdateCatInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectUpdateCatInfo not implemented")
}
func (UnimplementedCatServiceServer) GetUpdateCatApplyDetail(context.Context, *GetUpdateCatApplyDetailRequest) (*GetUpdateCatApplyDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUpdateCatApplyDetail not implemented")
}
func (UnimplementedCatServiceServer) ListUpdateCatApply(context.Context, *ListUpdateCatApplyRequest) (*ListUpdateCatApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUpdateCatApply not implemented")
}
func (UnimplementedCatServiceServer) ApproveMedicalRecord(context.Context, *ApproveMedicalRecordRequest) (*ApproveMedicalRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveMedicalRecord not implemented")
}
func (UnimplementedCatServiceServer) RejectMedicalRecord(context.Context, *RejectMedicalRecordRequest) (*RejectMedicalRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectMedicalRecord not implemented")
}
func (UnimplementedCatServiceServer) ApproveCreateCatTask(context.Context, *ApproveCreateCatTaskRequest) (*ApproveCreateCatTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveCreateCatTask not implemented")
}
func (UnimplementedCatServiceServer) RejectCreateCatTask(context.Context, *RejectCreateCatTaskRequest) (*RejectCreateCatTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectCreateCatTask not implemented")
}
func (UnimplementedCatServiceServer) GetCreateCatTaskApplyDetail(context.Context, *GetCreateCatTaskApplyDetailRequest) (*GetCreateCatTaskApplyDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCreateCatTaskApplyDetail not implemented")
}
func (UnimplementedCatServiceServer) ListCreateCatTaskApply(context.Context, *ListCreateCatTaskApplyRequest) (*ListCreateCatTaskApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCreateCatTaskApply not implemented")
}
func (UnimplementedCatServiceServer) CreateCatTask(context.Context, *CreateCatTaskRequest) (*CreateCatTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCatTask not implemented")
}
func (UnimplementedCatServiceServer) UpdateCatTaskStatus(context.Context, *UpdateCatTaskStatusRequest) (*UpdateCatTaskStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCatTaskStatus not implemented")
}
func (UnimplementedCatServiceServer) UpdateAdoptionStatus(context.Context, *UpdateAdoptionStatusRequest) (*UpdateAdoptionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdoptionStatus not implemented")
}
func (UnimplementedCatServiceServer) GetCatDetail(context.Context, *GetCatDetailRequest) (*GetCatDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCatDetail not implemented")
}
func (UnimplementedCatServiceServer) ListCats(context.Context, *ListCatsRequest) (*ListCatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCats not implemented")
}
func (UnimplementedCatServiceServer) ListCatTasks(context.Context, *ListCatTasksRequest) (*ListCatTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCatTasks not implemented")
}
func (UnimplementedCatServiceServer) mustEmbedUnimplementedCatServiceServer() {}
func (UnimplementedCatServiceServer) testEmbeddedByValue()                    {}

// UnsafeCatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatServiceServer will
// result in compilation errors.
type UnsafeCatServiceServer interface {
	mustEmbedUnimplementedCatServiceServer()
}

func RegisterCatServiceServer(s grpc.ServiceRegistrar, srv CatServiceServer) {
	// If the following call panics, it indicates UnimplementedCatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatService_ServiceDesc, srv)
}

func _CatService_ApplyCreateCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyCreateCatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ApplyCreateCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ApplyCreateCat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ApplyCreateCat(ctx, req.(*ApplyCreateCatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ApplyUpdateCatInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyUpdateCatInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ApplyUpdateCatInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ApplyUpdateCatInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ApplyUpdateCatInfo(ctx, req.(*ApplyUpdateCatInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetMyCreateCatApplyDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyCreateCatApplyDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetMyCreateCatApplyDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetMyCreateCatApplyDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetMyCreateCatApplyDetail(ctx, req.(*GetMyCreateCatApplyDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetMyUpdateCatApplyDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyUpdateCatApplyDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetMyUpdateCatApplyDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetMyUpdateCatApplyDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetMyUpdateCatApplyDetail(ctx, req.(*GetMyUpdateCatApplyDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ApplyAddMedicalRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyAddMedicalRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ApplyAddMedicalRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ApplyAddMedicalRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ApplyAddMedicalRecord(ctx, req.(*ApplyAddMedicalRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ApplyAddRescueRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyAddRescueRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ApplyAddRescueRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ApplyAddRescueRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ApplyAddRescueRecord(ctx, req.(*ApplyAddRescueRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ApplyCreateCatTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyCreateCatTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ApplyCreateCatTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ApplyCreateCatTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ApplyCreateCatTask(ctx, req.(*ApplyCreateCatTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ClaimCatTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimCatTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ClaimCatTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ClaimCatTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ClaimCatTask(ctx, req.(*ClaimCatTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_AbandonCatTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonCatTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).AbandonCatTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_AbandonCatTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).AbandonCatTask(ctx, req.(*AbandonCatTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_UploadTaskProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadTaskProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).UploadTaskProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_UploadTaskProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).UploadTaskProgress(ctx, req.(*UploadTaskProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ApproveCreateCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveCreateCatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ApproveCreateCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ApproveCreateCat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ApproveCreateCat(ctx, req.(*ApproveCreateCatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_RejectCreateCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectCreateCatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).RejectCreateCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_RejectCreateCat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).RejectCreateCat(ctx, req.(*RejectCreateCatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetCreateCatApplyDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCreateCatApplyDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetCreateCatApplyDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetCreateCatApplyDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetCreateCatApplyDetail(ctx, req.(*GetCreateCatApplyDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListCreateCatApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCreateCatApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListCreateCatApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListCreateCatApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListCreateCatApply(ctx, req.(*ListCreateCatApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ApproveUpdateCatInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveUpdateCatInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ApproveUpdateCatInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ApproveUpdateCatInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ApproveUpdateCatInfo(ctx, req.(*ApproveUpdateCatInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_RejectUpdateCatInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectUpdateCatInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).RejectUpdateCatInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_RejectUpdateCatInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).RejectUpdateCatInfo(ctx, req.(*RejectUpdateCatInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetUpdateCatApplyDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpdateCatApplyDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetUpdateCatApplyDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetUpdateCatApplyDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetUpdateCatApplyDetail(ctx, req.(*GetUpdateCatApplyDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListUpdateCatApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUpdateCatApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListUpdateCatApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListUpdateCatApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListUpdateCatApply(ctx, req.(*ListUpdateCatApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ApproveMedicalRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveMedicalRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ApproveMedicalRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ApproveMedicalRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ApproveMedicalRecord(ctx, req.(*ApproveMedicalRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_RejectMedicalRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectMedicalRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).RejectMedicalRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_RejectMedicalRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).RejectMedicalRecord(ctx, req.(*RejectMedicalRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ApproveCreateCatTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveCreateCatTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ApproveCreateCatTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ApproveCreateCatTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ApproveCreateCatTask(ctx, req.(*ApproveCreateCatTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_RejectCreateCatTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectCreateCatTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).RejectCreateCatTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_RejectCreateCatTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).RejectCreateCatTask(ctx, req.(*RejectCreateCatTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetCreateCatTaskApplyDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCreateCatTaskApplyDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetCreateCatTaskApplyDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetCreateCatTaskApplyDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetCreateCatTaskApplyDetail(ctx, req.(*GetCreateCatTaskApplyDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListCreateCatTaskApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCreateCatTaskApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListCreateCatTaskApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListCreateCatTaskApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListCreateCatTaskApply(ctx, req.(*ListCreateCatTaskApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_CreateCatTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCatTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).CreateCatTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_CreateCatTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).CreateCatTask(ctx, req.(*CreateCatTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_UpdateCatTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCatTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).UpdateCatTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_UpdateCatTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).UpdateCatTaskStatus(ctx, req.(*UpdateCatTaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_UpdateAdoptionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdoptionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).UpdateAdoptionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_UpdateAdoptionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).UpdateAdoptionStatus(ctx, req.(*UpdateAdoptionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_GetCatDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).GetCatDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_GetCatDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).GetCatDetail(ctx, req.(*GetCatDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListCats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListCats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListCats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListCats(ctx, req.(*ListCatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatService_ListCatTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCatTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServiceServer).ListCatTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatService_ListCatTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServiceServer).ListCatTasks(ctx, req.(*ListCatTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatService_ServiceDesc is the grpc.ServiceDesc for CatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cat.CatService",
	HandlerType: (*CatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyCreateCat",
			Handler:    _CatService_ApplyCreateCat_Handler,
		},
		{
			MethodName: "ApplyUpdateCatInfo",
			Handler:    _CatService_ApplyUpdateCatInfo_Handler,
		},
		{
			MethodName: "GetMyCreateCatApplyDetail",
			Handler:    _CatService_GetMyCreateCatApplyDetail_Handler,
		},
		{
			MethodName: "GetMyUpdateCatApplyDetail",
			Handler:    _CatService_GetMyUpdateCatApplyDetail_Handler,
		},
		{
			MethodName: "ApplyAddMedicalRecord",
			Handler:    _CatService_ApplyAddMedicalRecord_Handler,
		},
		{
			MethodName: "ApplyAddRescueRecord",
			Handler:    _CatService_ApplyAddRescueRecord_Handler,
		},
		{
			MethodName: "ApplyCreateCatTask",
			Handler:    _CatService_ApplyCreateCatTask_Handler,
		},
		{
			MethodName: "ClaimCatTask",
			Handler:    _CatService_ClaimCatTask_Handler,
		},
		{
			MethodName: "AbandonCatTask",
			Handler:    _CatService_AbandonCatTask_Handler,
		},
		{
			MethodName: "UploadTaskProgress",
			Handler:    _CatService_UploadTaskProgress_Handler,
		},
		{
			MethodName: "ApproveCreateCat",
			Handler:    _CatService_ApproveCreateCat_Handler,
		},
		{
			MethodName: "RejectCreateCat",
			Handler:    _CatService_RejectCreateCat_Handler,
		},
		{
			MethodName: "GetCreateCatApplyDetail",
			Handler:    _CatService_GetCreateCatApplyDetail_Handler,
		},
		{
			MethodName: "ListCreateCatApply",
			Handler:    _CatService_ListCreateCatApply_Handler,
		},
		{
			MethodName: "ApproveUpdateCatInfo",
			Handler:    _CatService_ApproveUpdateCatInfo_Handler,
		},
		{
			MethodName: "RejectUpdateCatInfo",
			Handler:    _CatService_RejectUpdateCatInfo_Handler,
		},
		{
			MethodName: "GetUpdateCatApplyDetail",
			Handler:    _CatService_GetUpdateCatApplyDetail_Handler,
		},
		{
			MethodName: "ListUpdateCatApply",
			Handler:    _CatService_ListUpdateCatApply_Handler,
		},
		{
			MethodName: "ApproveMedicalRecord",
			Handler:    _CatService_ApproveMedicalRecord_Handler,
		},
		{
			MethodName: "RejectMedicalRecord",
			Handler:    _CatService_RejectMedicalRecord_Handler,
		},
		{
			MethodName: "ApproveCreateCatTask",
			Handler:    _CatService_ApproveCreateCatTask_Handler,
		},
		{
			MethodName: "RejectCreateCatTask",
			Handler:    _CatService_RejectCreateCatTask_Handler,
		},
		{
			MethodName: "GetCreateCatTaskApplyDetail",
			Handler:    _CatService_GetCreateCatTaskApplyDetail_Handler,
		},
		{
			MethodName: "ListCreateCatTaskApply",
			Handler:    _CatService_ListCreateCatTaskApply_Handler,
		},
		{
			MethodName: "CreateCatTask",
			Handler:    _CatService_CreateCatTask_Handler,
		},
		{
			MethodName: "UpdateCatTaskStatus",
			Handler:    _CatService_UpdateCatTaskStatus_Handler,
		},
		{
			MethodName: "UpdateAdoptionStatus",
			Handler:    _CatService_UpdateAdoptionStatus_Handler,
		},
		{
			MethodName: "GetCatDetail",
			Handler:    _CatService_GetCatDetail_Handler,
		},
		{
			MethodName: "ListCats",
			Handler:    _CatService_ListCats_Handler,
		},
		{
			MethodName: "ListCatTasks",
			Handler:    _CatService_ListCatTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/cat/v1/cat.proto",
}
