// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: cat.proto

package server

import (
	"context"

	"github.com/luyb177/meow-nook/service/cat/internal/logic"
	"github.com/luyb177/meow-nook/service/cat/internal/svc"
	"github.com/luyb177/meow-nook/service/cat/pb/cat/v1"
)

type CatServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedCatServiceServer
}

func NewCatServiceServer(svcCtx *svc.ServiceContext) *CatServiceServer {
	return &CatServiceServer{
		svcCtx: svcCtx,
	}
}

// 申请创建小猫档案
func (s *CatServiceServer) ApplyCreateCat(ctx context.Context, in *v1.ApplyCreateCatRequest) (*v1.ApplyCreateCatResponse, error) {
	l := logic.NewApplyCreateCatLogic(ctx, s.svcCtx)
	return l.ApplyCreateCat(in)
}

// 申请修改猫咪档案信息
func (s *CatServiceServer) ApplyUpdateCatInfo(ctx context.Context, in *v1.ApplyUpdateCatInfoRequest) (*v1.ApplyUpdateCatInfoResponse, error) {
	l := logic.NewApplyUpdateCatInfoLogic(ctx, s.svcCtx)
	return l.ApplyUpdateCatInfo(in)
}

// 查看自己提交的创建申请详情
func (s *CatServiceServer) GetMyCreateCatApplyDetail(ctx context.Context, in *v1.GetMyCreateCatApplyDetailRequest) (*v1.GetMyCreateCatApplyDetailResponse, error) {
	l := logic.NewGetMyCreateCatApplyDetailLogic(ctx, s.svcCtx)
	return l.GetMyCreateCatApplyDetail(in)
}

// 查看自己提交的修改申请详情
func (s *CatServiceServer) GetMyUpdateCatApplyDetail(ctx context.Context, in *v1.GetMyUpdateCatApplyDetailRequest) (*v1.GetMyUpdateCatApplyDetailResponse, error) {
	l := logic.NewGetMyUpdateCatApplyDetailLogic(ctx, s.svcCtx)
	return l.GetMyUpdateCatApplyDetail(in)
}

// 申请新增医疗记录
func (s *CatServiceServer) ApplyAddMedicalRecord(ctx context.Context, in *v1.ApplyAddMedicalRecordRequest) (*v1.ApplyAddMedicalRecordResponse, error) {
	l := logic.NewApplyAddMedicalRecordLogic(ctx, s.svcCtx)
	return l.ApplyAddMedicalRecord(in)
}

// 申请新增救助记录
func (s *CatServiceServer) ApplyAddRescueRecord(ctx context.Context, in *v1.ApplyAddRescueRecordRequest) (*v1.ApplyAddRescueRecordResponse, error) {
	l := logic.NewApplyAddRescueRecordLogic(ctx, s.svcCtx)
	return l.ApplyAddRescueRecord(in)
}

// 申请创建任务
func (s *CatServiceServer) ApplyCreateCatTask(ctx context.Context, in *v1.ApplyCreateCatTaskRequest) (*v1.ApplyCreateCatTaskResponse, error) {
	l := logic.NewApplyCreateCatTaskLogic(ctx, s.svcCtx)
	return l.ApplyCreateCatTask(in)
}

// 申请认领任务
func (s *CatServiceServer) ClaimCatTask(ctx context.Context, in *v1.ClaimCatTaskRequest) (*v1.ClaimCatTaskResponse, error) {
	l := logic.NewClaimCatTaskLogic(ctx, s.svcCtx)
	return l.ClaimCatTask(in)
}

// 申请放弃任务
func (s *CatServiceServer) AbandonCatTask(ctx context.Context, in *v1.AbandonCatTaskRequest) (*v1.AbandonCatTaskResponse, error) {
	l := logic.NewAbandonCatTaskLogic(ctx, s.svcCtx)
	return l.AbandonCatTask(in)
}

// 上传任务进度（图片/备注）
func (s *CatServiceServer) UploadTaskProgress(ctx context.Context, in *v1.UploadTaskProgressRequest) (*v1.UploadTaskProgressResponse, error) {
	l := logic.NewUploadTaskProgressLogic(ctx, s.svcCtx)
	return l.UploadTaskProgress(in)
}

func (s *CatServiceServer) ApproveCreateCat(ctx context.Context, in *v1.ApproveCreateCatRequest) (*v1.ApproveCreateCatResponse, error) {
	l := logic.NewApproveCreateCatLogic(ctx, s.svcCtx)
	return l.ApproveCreateCat(in)
}

func (s *CatServiceServer) RejectCreateCat(ctx context.Context, in *v1.RejectCreateCatRequest) (*v1.RejectCreateCatResponse, error) {
	l := logic.NewRejectCreateCatLogic(ctx, s.svcCtx)
	return l.RejectCreateCat(in)
}

func (s *CatServiceServer) GetCreateCatApplyDetail(ctx context.Context, in *v1.GetCreateCatApplyDetailRequest) (*v1.GetCreateCatApplyDetailResponse, error) {
	l := logic.NewGetCreateCatApplyDetailLogic(ctx, s.svcCtx)
	return l.GetCreateCatApplyDetail(in)
}

func (s *CatServiceServer) ListCreateCatApply(ctx context.Context, in *v1.ListCreateCatApplyRequest) (*v1.ListCreateCatApplyResponse, error) {
	l := logic.NewListCreateCatApplyLogic(ctx, s.svcCtx)
	return l.ListCreateCatApply(in)
}

func (s *CatServiceServer) ApproveUpdateCatInfo(ctx context.Context, in *v1.ApproveUpdateCatInfoRequest) (*v1.ApproveUpdateCatInfoResponse, error) {
	l := logic.NewApproveUpdateCatInfoLogic(ctx, s.svcCtx)
	return l.ApproveUpdateCatInfo(in)
}

func (s *CatServiceServer) RejectUpdateCatInfo(ctx context.Context, in *v1.RejectUpdateCatInfoRequest) (*v1.RejectUpdateCatInfoResponse, error) {
	l := logic.NewRejectUpdateCatInfoLogic(ctx, s.svcCtx)
	return l.RejectUpdateCatInfo(in)
}

func (s *CatServiceServer) GetUpdateCatApplyDetail(ctx context.Context, in *v1.GetUpdateCatApplyDetailRequest) (*v1.GetUpdateCatApplyDetailResponse, error) {
	l := logic.NewGetUpdateCatApplyDetailLogic(ctx, s.svcCtx)
	return l.GetUpdateCatApplyDetail(in)
}

func (s *CatServiceServer) ListUpdateCatApply(ctx context.Context, in *v1.ListUpdateCatApplyRequest) (*v1.ListUpdateCatApplyResponse, error) {
	l := logic.NewListUpdateCatApplyLogic(ctx, s.svcCtx)
	return l.ListUpdateCatApply(in)
}

func (s *CatServiceServer) ApproveMedicalRecord(ctx context.Context, in *v1.ApproveMedicalRecordRequest) (*v1.ApproveMedicalRecordResponse, error) {
	l := logic.NewApproveMedicalRecordLogic(ctx, s.svcCtx)
	return l.ApproveMedicalRecord(in)
}

func (s *CatServiceServer) RejectMedicalRecord(ctx context.Context, in *v1.RejectMedicalRecordRequest) (*v1.RejectMedicalRecordResponse, error) {
	l := logic.NewRejectMedicalRecordLogic(ctx, s.svcCtx)
	return l.RejectMedicalRecord(in)
}

// 管理员审核志愿者任务申请
func (s *CatServiceServer) ApproveCreateCatTask(ctx context.Context, in *v1.ApproveCreateCatTaskRequest) (*v1.ApproveCreateCatTaskResponse, error) {
	l := logic.NewApproveCreateCatTaskLogic(ctx, s.svcCtx)
	return l.ApproveCreateCatTask(in)
}

func (s *CatServiceServer) RejectCreateCatTask(ctx context.Context, in *v1.RejectCreateCatTaskRequest) (*v1.RejectCreateCatTaskResponse, error) {
	l := logic.NewRejectCreateCatTaskLogic(ctx, s.svcCtx)
	return l.RejectCreateCatTask(in)
}

func (s *CatServiceServer) GetCreateCatTaskApplyDetail(ctx context.Context, in *v1.GetCreateCatTaskApplyDetailRequest) (*v1.GetCreateCatTaskApplyDetailResponse, error) {
	l := logic.NewGetCreateCatTaskApplyDetailLogic(ctx, s.svcCtx)
	return l.GetCreateCatTaskApplyDetail(in)
}

func (s *CatServiceServer) ListCreateCatTaskApply(ctx context.Context, in *v1.ListCreateCatTaskApplyRequest) (*v1.ListCreateCatTaskApplyResponse, error) {
	l := logic.NewListCreateCatTaskApplyLogic(ctx, s.svcCtx)
	return l.ListCreateCatTaskApply(in)
}

// 管理员直接创建正式任务（无需审核）
func (s *CatServiceServer) CreateCatTask(ctx context.Context, in *v1.CreateCatTaskRequest) (*v1.CreateCatTaskResponse, error) {
	l := logic.NewCreateCatTaskLogic(ctx, s.svcCtx)
	return l.CreateCatTask(in)
}

// 管理员更新任务状态
func (s *CatServiceServer) UpdateCatTaskStatus(ctx context.Context, in *v1.UpdateCatTaskStatusRequest) (*v1.UpdateCatTaskStatusResponse, error) {
	l := logic.NewUpdateCatTaskStatusLogic(ctx, s.svcCtx)
	return l.UpdateCatTaskStatus(in)
}

func (s *CatServiceServer) UpdateAdoptionStatus(ctx context.Context, in *v1.UpdateAdoptionStatusRequest) (*v1.UpdateAdoptionStatusResponse, error) {
	l := logic.NewUpdateAdoptionStatusLogic(ctx, s.svcCtx)
	return l.UpdateAdoptionStatus(in)
}

// 猫咪详情
func (s *CatServiceServer) GetCatDetail(ctx context.Context, in *v1.GetCatDetailRequest) (*v1.GetCatDetailResponse, error) {
	l := logic.NewGetCatDetailLogic(ctx, s.svcCtx)
	return l.GetCatDetail(in)
}

// 猫咪列表
func (s *CatServiceServer) ListCats(ctx context.Context, in *v1.ListCatsRequest) (*v1.ListCatsResponse, error) {
	l := logic.NewListCatsLogic(ctx, s.svcCtx)
	return l.ListCats(in)
}

// 正式任务列表
func (s *CatServiceServer) ListCatTasks(ctx context.Context, in *v1.ListCatTasksRequest) (*v1.ListCatTasksResponse, error) {
	l := logic.NewListCatTasksLogic(ctx, s.svcCtx)
	return l.ListCatTasks(in)
}
