// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: cat.proto

package server

import (
	"context"

	"github.com/luyb177/meow-nook/service/cat/internal/logic"
	"github.com/luyb177/meow-nook/service/cat/internal/svc"
	"github.com/luyb177/meow-nook/service/cat/pb/cat/v1"
)

type CatServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedCatServiceServer
}

func NewCatServiceServer(svcCtx *svc.ServiceContext) *CatServiceServer {
	return &CatServiceServer{
		svcCtx: svcCtx,
	}
}

// 志愿者
func (s *CatServiceServer) ApplyCreateCat(ctx context.Context, in *v1.ApplyCreateCatRequest) (*v1.ApplyCreateCatResponse, error) {
	l := logic.NewApplyCreateCatLogic(ctx, s.svcCtx)
	return l.ApplyCreateCat(in)
}

func (s *CatServiceServer) CancelApplyCreateCat(ctx context.Context, in *v1.CancelApplyCreateCatRequest) (*v1.Response, error) {
	l := logic.NewCancelApplyCreateCatLogic(ctx, s.svcCtx)
	return l.CancelApplyCreateCat(in)
}

func (s *CatServiceServer) GetApplyDetail(ctx context.Context, in *v1.GetApplyDetailRequest) (*v1.GetApplyDetailResponse, error) {
	l := logic.NewGetApplyDetailLogic(ctx, s.svcCtx)
	return l.GetApplyDetail(in)
}

func (s *CatServiceServer) ListMyApplies(ctx context.Context, in *v1.ListMyAppliesRequest) (*v1.ListMyAppliesResponse, error) {
	l := logic.NewListMyAppliesLogic(ctx, s.svcCtx)
	return l.ListMyApplies(in)
}

// 管理员
func (s *CatServiceServer) ApproveCreateCat(ctx context.Context, in *v1.ApproveCreateCatRequest) (*v1.ApproveCreateCatResponse, error) {
	l := logic.NewApproveCreateCatLogic(ctx, s.svcCtx)
	return l.ApproveCreateCat(in)
}

func (s *CatServiceServer) RejectCreateCat(ctx context.Context, in *v1.RejectCreateCatRequest) (*v1.Response, error) {
	l := logic.NewRejectCreateCatLogic(ctx, s.svcCtx)
	return l.RejectCreateCat(in)
}

func (s *CatServiceServer) DirectCreateCat(ctx context.Context, in *v1.DirectCreateCatRequest) (*v1.DirectCreateCatResponse, error) {
	l := logic.NewDirectCreateCatLogic(ctx, s.svcCtx)
	return l.DirectCreateCat(in)
}

func (s *CatServiceServer) ListPendingApplies(ctx context.Context, in *v1.ListPendingAppliesRequest) (*v1.ListPendingAppliesResponse, error) {
	l := logic.NewListPendingAppliesLogic(ctx, s.svcCtx)
	return l.ListPendingApplies(in)
}

// 申请领养
func (s *CatServiceServer) ApplyAdopt(ctx context.Context, in *v1.ApplyAdoptRequest) (*v1.ApplyAdoptResponse, error) {
	l := logic.NewApplyAdoptLogic(ctx, s.svcCtx)
	return l.ApplyAdopt(in)
}

// 取消申请
func (s *CatServiceServer) CancelAdoptApply(ctx context.Context, in *v1.CancelAdoptApplyRequest) (*v1.CancelAdoptApplyResponse, error) {
	l := logic.NewCancelAdoptApplyLogic(ctx, s.svcCtx)
	return l.CancelAdoptApply(in)
}

// 查看申请详情
func (s *CatServiceServer) GetAdoptApplyDetail(ctx context.Context, in *v1.GetAdoptApplyDetailRequest) (*v1.GetAdoptApplyDetailResponse, error) {
	l := logic.NewGetAdoptApplyDetailLogic(ctx, s.svcCtx)
	return l.GetAdoptApplyDetail(in)
}

// 我的申请列表
func (s *CatServiceServer) ListMyAdoptApplies(ctx context.Context, in *v1.ListMyAdoptAppliesRequest) (*v1.ListMyAdoptAppliesResponse, error) {
	l := logic.NewListMyAdoptAppliesLogic(ctx, s.svcCtx)
	return l.ListMyAdoptApplies(in)
}

// 我的领养记录
func (s *CatServiceServer) ListMyAdoptions(ctx context.Context, in *v1.ListMyAdoptionsRequest) (*v1.ListAdoptionsResponse, error) {
	l := logic.NewListMyAdoptionsLogic(ctx, s.svcCtx)
	return l.ListMyAdoptions(in)
}

// 完成回访
func (s *CatServiceServer) CompleteVisit(ctx context.Context, in *v1.RecordFollowUpVisitRequest) (*v1.RecordFollowUpVisitResponse, error) {
	l := logic.NewCompleteVisitLogic(ctx, s.svcCtx)
	return l.CompleteVisit(in)
}

// 审核通过
func (s *CatServiceServer) ApproveAdopt(ctx context.Context, in *v1.ApproveAdoptRequest) (*v1.ApproveAdoptResponse, error) {
	l := logic.NewApproveAdoptLogic(ctx, s.svcCtx)
	return l.ApproveAdopt(in)
}

// 审核拒绝
func (s *CatServiceServer) RejectAdopt(ctx context.Context, in *v1.RejectAdoptRequest) (*v1.RejectAdoptResponse, error) {
	l := logic.NewRejectAdoptLogic(ctx, s.svcCtx)
	return l.RejectAdopt(in)
}

// 待审核列表
func (s *CatServiceServer) ListPendingAdoptApplies(ctx context.Context, in *v1.ListPendingAdoptAppliesRequest) (*v1.ListPendingAdoptAppliesResponse, error) {
	l := logic.NewListPendingAdoptAppliesLogic(ctx, s.svcCtx)
	return l.ListPendingAdoptApplies(in)
}

// 从申请创建领养记录
func (s *CatServiceServer) CreateAdoption(ctx context.Context, in *v1.CreateAdoptionRequest) (*v1.CreateAdoptionResponse, error) {
	l := logic.NewCreateAdoptionLogic(ctx, s.svcCtx)
	return l.CreateAdoption(in)
}

// 直接领养
func (s *CatServiceServer) DirectAdopt(ctx context.Context, in *v1.DirectAdoptRequest) (*v1.DirectAdoptResponse, error) {
	l := logic.NewDirectAdoptLogic(ctx, s.svcCtx)
	return l.DirectAdopt(in)
}

// 查看领养详情
func (s *CatServiceServer) GetAdoptionDetail(ctx context.Context, in *v1.GetAdoptionDetailRequest) (*v1.GetAdoptionDetailResponse, error) {
	l := logic.NewGetAdoptionDetailLogic(ctx, s.svcCtx)
	return l.GetAdoptionDetail(in)
}

// 领养记录列表
func (s *CatServiceServer) ListAdoptions(ctx context.Context, in *v1.ListAdoptionsRequest) (*v1.ListAdoptionsResponse, error) {
	l := logic.NewListAdoptionsLogic(ctx, s.svcCtx)
	return l.ListAdoptions(in)
}

// 更新领养信息
func (s *CatServiceServer) UpdateAdoption(ctx context.Context, in *v1.UpdateAdoptionRequest) (*v1.UpdateAdoptionResponse, error) {
	l := logic.NewUpdateAdoptionLogic(ctx, s.svcCtx)
	return l.UpdateAdoption(in)
}

// 记录家访
func (s *CatServiceServer) RecordHomeVisit(ctx context.Context, in *v1.RecordHomeVisitRequest) (*v1.RecordHomeVisitResponse, error) {
	l := logic.NewRecordHomeVisitLogic(ctx, s.svcCtx)
	return l.RecordHomeVisit(in)
}

// 记录回访
func (s *CatServiceServer) RecordFollowUpVisit(ctx context.Context, in *v1.RecordFollowUpVisitRequest) (*v1.RecordFollowUpVisitResponse, error) {
	l := logic.NewRecordFollowUpVisitLogic(ctx, s.svcCtx)
	return l.RecordFollowUpVisit(in)
}

// 更新退回状态
func (s *CatServiceServer) UpdateReturnStatus(ctx context.Context, in *v1.UpdateReturnStatusRequest) (*v1.UpdateReturnStatusResponse, error) {
	l := logic.NewUpdateReturnStatusLogic(ctx, s.svcCtx)
	return l.UpdateReturnStatus(in)
}

// 申请创建任务
func (s *CatServiceServer) ApplyCreateTask(ctx context.Context, in *v1.ApplyCreateTaskRequest) (*v1.ApplyCreateTaskResponse, error) {
	l := logic.NewApplyCreateTaskLogic(ctx, s.svcCtx)
	return l.ApplyCreateTask(in)
}

// 取消任务申请
func (s *CatServiceServer) CancelTaskApply(ctx context.Context, in *v1.CancelTaskApplyRequest) (*v1.CancelTaskApplyResponse, error) {
	l := logic.NewCancelTaskApplyLogic(ctx, s.svcCtx)
	return l.CancelTaskApply(in)
}

// 查看任务申请详情
func (s *CatServiceServer) GetTaskApplyDetail(ctx context.Context, in *v1.GetTaskApplyDetailRequest) (*v1.GetTaskApplyDetailResponse, error) {
	l := logic.NewGetTaskApplyDetailLogic(ctx, s.svcCtx)
	return l.GetTaskApplyDetail(in)
}

// 我的任务申请列表
func (s *CatServiceServer) ListMyTaskApplies(ctx context.Context, in *v1.ListMyTaskAppliesRequest) (*v1.ListMyTaskAppliesResponse, error) {
	l := logic.NewListMyTaskAppliesLogic(ctx, s.svcCtx)
	return l.ListMyTaskApplies(in)
}

// 认领任务
func (s *CatServiceServer) ClaimTask(ctx context.Context, in *v1.ClaimTaskRequest) (*v1.ClaimTaskResponse, error) {
	l := logic.NewClaimTaskLogic(ctx, s.svcCtx)
	return l.ClaimTask(in)
}

// 放弃任务
func (s *CatServiceServer) AbandonTask(ctx context.Context, in *v1.AbandonTaskRequest) (*v1.AbandonTaskResponse, error) {
	l := logic.NewAbandonTaskLogic(ctx, s.svcCtx)
	return l.AbandonTask(in)
}

// 完成任务
func (s *CatServiceServer) CompleteTask(ctx context.Context, in *v1.CompleteTaskRequest) (*v1.CompleteTaskResponse, error) {
	l := logic.NewCompleteTaskLogic(ctx, s.svcCtx)
	return l.CompleteTask(in)
}

// 查看任务详情
func (s *CatServiceServer) GetTaskDetail(ctx context.Context, in *v1.GetTaskDetailRequest) (*v1.GetTaskDetailResponse, error) {
	l := logic.NewGetTaskDetailLogic(ctx, s.svcCtx)
	return l.GetTaskDetail(in)
}

// 任务列表（公开查询）
func (s *CatServiceServer) ListTasks(ctx context.Context, in *v1.ListTasksRequest) (*v1.ListTasksResponse, error) {
	l := logic.NewListTasksLogic(ctx, s.svcCtx)
	return l.ListTasks(in)
}

// 我认领的任务列表
func (s *CatServiceServer) ListMyClaimedTasks(ctx context.Context, in *v1.ListMyClaimedTasksRequest) (*v1.ListMyClaimedTasksResponse, error) {
	l := logic.NewListMyClaimedTasksLogic(ctx, s.svcCtx)
	return l.ListMyClaimedTasks(in)
}

// 我完成的任务列表
func (s *CatServiceServer) ListMyCompletedTasks(ctx context.Context, in *v1.ListMyCompletedTasksRequest) (*v1.ListMyCompletedTasksResponse, error) {
	l := logic.NewListMyCompletedTasksLogic(ctx, s.svcCtx)
	return l.ListMyCompletedTasks(in)
}

// 审核通过任务申请
func (s *CatServiceServer) ApproveTaskApply(ctx context.Context, in *v1.ApproveTaskApplyRequest) (*v1.ApproveTaskApplyResponse, error) {
	l := logic.NewApproveTaskApplyLogic(ctx, s.svcCtx)
	return l.ApproveTaskApply(in)
}

// 拒绝任务申请
func (s *CatServiceServer) RejectTaskApply(ctx context.Context, in *v1.RejectTaskApplyRequest) (*v1.RejectTaskApplyResponse, error) {
	l := logic.NewRejectTaskApplyLogic(ctx, s.svcCtx)
	return l.RejectTaskApply(in)
}

// 待审核任务申请列表
func (s *CatServiceServer) ListPendingTaskApplies(ctx context.Context, in *v1.ListPendingTaskAppliesRequest) (*v1.ListPendingTaskAppliesResponse, error) {
	l := logic.NewListPendingTaskAppliesLogic(ctx, s.svcCtx)
	return l.ListPendingTaskApplies(in)
}

// 直接创建任务（跳过申请）
func (s *CatServiceServer) DirectCreateTask(ctx context.Context, in *v1.DirectCreateTaskRequest) (*v1.DirectCreateTaskResponse, error) {
	l := logic.NewDirectCreateTaskLogic(ctx, s.svcCtx)
	return l.DirectCreateTask(in)
}

// 更新任务
func (s *CatServiceServer) UpdateTask(ctx context.Context, in *v1.UpdateTaskRequest) (*v1.UpdateTaskResponse, error) {
	l := logic.NewUpdateTaskLogic(ctx, s.svcCtx)
	return l.UpdateTask(in)
}

// 取消任务
func (s *CatServiceServer) CancelTask(ctx context.Context, in *v1.CancelTaskRequest) (*v1.CancelTaskResponse, error) {
	l := logic.NewCancelTaskLogic(ctx, s.svcCtx)
	return l.CancelTask(in)
}

// 升级任务紧急度
func (s *CatServiceServer) EscalateTaskUrgency(ctx context.Context, in *v1.EscalateTaskUrgencyRequest) (*v1.EscalateTaskUrgencyResponse, error) {
	l := logic.NewEscalateTaskUrgencyLogic(ctx, s.svcCtx)
	return l.EscalateTaskUrgency(in)
}

// 查看任务流转日志
func (s *CatServiceServer) GetTaskFlows(ctx context.Context, in *v1.GetTaskFlowsRequest) (*v1.GetTaskFlowsResponse, error) {
	l := logic.NewGetTaskFlowsLogic(ctx, s.svcCtx)
	return l.GetTaskFlows(in)
}

// 查看任务操作日志
func (s *CatServiceServer) GetTaskLogs(ctx context.Context, in *v1.GetTaskLogsRequest) (*v1.GetTaskLogsResponse, error) {
	l := logic.NewGetTaskLogsLogic(ctx, s.svcCtx)
	return l.GetTaskLogs(in)
}

// 申请修改猫咪档案信息
func (s *CatServiceServer) ApplyUpdateCatInfo(ctx context.Context, in *v1.ApplyUpdateCatInfoRequest) (*v1.ApplyUpdateCatInfoResponse, error) {
	l := logic.NewApplyUpdateCatInfoLogic(ctx, s.svcCtx)
	return l.ApplyUpdateCatInfo(in)
}

// 查看自己提交的修改申请详情
func (s *CatServiceServer) GetMyUpdateCatApplyDetail(ctx context.Context, in *v1.GetMyUpdateCatApplyDetailRequest) (*v1.GetMyUpdateCatApplyDetailResponse, error) {
	l := logic.NewGetMyUpdateCatApplyDetailLogic(ctx, s.svcCtx)
	return l.GetMyUpdateCatApplyDetail(in)
}

// 申请新增医疗记录
func (s *CatServiceServer) ApplyAddMedicalRecord(ctx context.Context, in *v1.ApplyAddMedicalRecordRequest) (*v1.ApplyAddMedicalRecordResponse, error) {
	l := logic.NewApplyAddMedicalRecordLogic(ctx, s.svcCtx)
	return l.ApplyAddMedicalRecord(in)
}

// 申请新增救助记录
func (s *CatServiceServer) ApplyAddRescueRecord(ctx context.Context, in *v1.ApplyAddRescueRecordRequest) (*v1.ApplyAddRescueRecordResponse, error) {
	l := logic.NewApplyAddRescueRecordLogic(ctx, s.svcCtx)
	return l.ApplyAddRescueRecord(in)
}

// 上传任务进度（图片/备注）
func (s *CatServiceServer) UploadTaskProgress(ctx context.Context, in *v1.UploadTaskProgressRequest) (*v1.UploadTaskProgressResponse, error) {
	l := logic.NewUploadTaskProgressLogic(ctx, s.svcCtx)
	return l.UploadTaskProgress(in)
}

func (s *CatServiceServer) ApproveUpdateCatInfo(ctx context.Context, in *v1.ApproveUpdateCatInfoRequest) (*v1.ApproveUpdateCatInfoResponse, error) {
	l := logic.NewApproveUpdateCatInfoLogic(ctx, s.svcCtx)
	return l.ApproveUpdateCatInfo(in)
}

func (s *CatServiceServer) RejectUpdateCatInfo(ctx context.Context, in *v1.RejectUpdateCatInfoRequest) (*v1.RejectUpdateCatInfoResponse, error) {
	l := logic.NewRejectUpdateCatInfoLogic(ctx, s.svcCtx)
	return l.RejectUpdateCatInfo(in)
}

func (s *CatServiceServer) GetUpdateCatApplyDetail(ctx context.Context, in *v1.GetUpdateCatApplyDetailRequest) (*v1.GetUpdateCatApplyDetailResponse, error) {
	l := logic.NewGetUpdateCatApplyDetailLogic(ctx, s.svcCtx)
	return l.GetUpdateCatApplyDetail(in)
}

func (s *CatServiceServer) ListUpdateCatApply(ctx context.Context, in *v1.ListUpdateCatApplyRequest) (*v1.ListUpdateCatApplyResponse, error) {
	l := logic.NewListUpdateCatApplyLogic(ctx, s.svcCtx)
	return l.ListUpdateCatApply(in)
}

func (s *CatServiceServer) ApproveMedicalRecord(ctx context.Context, in *v1.ApproveMedicalRecordRequest) (*v1.ApproveMedicalRecordResponse, error) {
	l := logic.NewApproveMedicalRecordLogic(ctx, s.svcCtx)
	return l.ApproveMedicalRecord(in)
}

func (s *CatServiceServer) RejectMedicalRecord(ctx context.Context, in *v1.RejectMedicalRecordRequest) (*v1.RejectMedicalRecordResponse, error) {
	l := logic.NewRejectMedicalRecordLogic(ctx, s.svcCtx)
	return l.RejectMedicalRecord(in)
}

// 管理员更新任务状态
func (s *CatServiceServer) UpdateCatTaskStatus(ctx context.Context, in *v1.UpdateCatTaskStatusRequest) (*v1.UpdateCatTaskStatusResponse, error) {
	l := logic.NewUpdateCatTaskStatusLogic(ctx, s.svcCtx)
	return l.UpdateCatTaskStatus(in)
}

// 猫咪详情
func (s *CatServiceServer) GetCatDetail(ctx context.Context, in *v1.GetCatDetailRequest) (*v1.GetCatDetailResponse, error) {
	l := logic.NewGetCatDetailLogic(ctx, s.svcCtx)
	return l.GetCatDetail(in)
}

// 猫咪列表
func (s *CatServiceServer) ListCats(ctx context.Context, in *v1.ListCatsRequest) (*v1.ListCatsResponse, error) {
	l := logic.NewListCatsLogic(ctx, s.svcCtx)
	return l.ListCats(in)
}
