// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: cat.proto

package server

import (
	"context"

	"github.com/luyb177/meow-nook/service/cat/internal/logic"
	"github.com/luyb177/meow-nook/service/cat/internal/svc"
	"github.com/luyb177/meow-nook/service/cat/pb/cat/v1"
)

type CatServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedCatServiceServer
}

func NewCatServiceServer(svcCtx *svc.ServiceContext) *CatServiceServer {
	return &CatServiceServer{
		svcCtx: svcCtx,
	}
}

// CRUD
func (s *CatServiceServer) CreateCat(ctx context.Context, in *v1.CreateCatReq) (*v1.CreateCatResp, error) {
	l := logic.NewCreateCatLogic(ctx, s.svcCtx)
	return l.CreateCat(in)
}

func (s *CatServiceServer) GetCat(ctx context.Context, in *v1.GetCatReq) (*v1.GetCatResp, error) {
	l := logic.NewGetCatLogic(ctx, s.svcCtx)
	return l.GetCat(in)
}

func (s *CatServiceServer) UpdateCat(ctx context.Context, in *v1.UpdateCatReq) (*v1.UpdateCatResp, error) {
	l := logic.NewUpdateCatLogic(ctx, s.svcCtx)
	return l.UpdateCat(in)
}

func (s *CatServiceServer) DeleteCat(ctx context.Context, in *v1.DeleteCatReq) (*v1.DeleteCatResp, error) {
	l := logic.NewDeleteCatLogic(ctx, s.svcCtx)
	return l.DeleteCat(in)
}

func (s *CatServiceServer) ListCats(ctx context.Context, in *v1.ListCatsReq) (*v1.ListCatsResp, error) {
	l := logic.NewListCatsLogic(ctx, s.svcCtx)
	return l.ListCats(in)
}

// Rescue records
func (s *CatServiceServer) AddRescueRecord(ctx context.Context, in *v1.AddRescueRecordReq) (*v1.AddRescueRecordResp, error) {
	l := logic.NewAddRescueRecordLogic(ctx, s.svcCtx)
	return l.AddRescueRecord(in)
}

func (s *CatServiceServer) ListRescueRecords(ctx context.Context, in *v1.ListRescueRecordsReq) (*v1.ListRescueRecordsResp, error) {
	l := logic.NewListRescueRecordsLogic(ctx, s.svcCtx)
	return l.ListRescueRecords(in)
}

// Health records
func (s *CatServiceServer) AddHealthRecord(ctx context.Context, in *v1.AddHealthRecordReq) (*v1.AddHealthRecordResp, error) {
	l := logic.NewAddHealthRecordLogic(ctx, s.svcCtx)
	return l.AddHealthRecord(in)
}

func (s *CatServiceServer) ListHealthRecords(ctx context.Context, in *v1.ListHealthRecordsReq) (*v1.ListHealthRecordsResp, error) {
	l := logic.NewListHealthRecordsLogic(ctx, s.svcCtx)
	return l.ListHealthRecords(in)
}

// Stats & heatmap
func (s *CatServiceServer) GetStats(ctx context.Context, in *v1.GetStatsReq) (*v1.GetStatsResp, error) {
	l := logic.NewGetStatsLogic(ctx, s.svcCtx)
	return l.GetStats(in)
}

func (s *CatServiceServer) GetHeatmap(ctx context.Context, in *v1.GetHeatmapReq) (*v1.GetHeatmapResp, error) {
	l := logic.NewGetHeatmapLogic(ctx, s.svcCtx)
	return l.GetHeatmap(in)
}
