// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: task.proto

package server

import (
	"context"

	"github.com/luyb177/meow-nook/service/task/internal/logic"
	"github.com/luyb177/meow-nook/service/task/internal/svc"
	"github.com/luyb177/meow-nook/service/task/pb/task/v1"
)

type TaskServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedTaskServiceServer
}

func NewTaskServiceServer(svcCtx *svc.ServiceContext) *TaskServiceServer {
	return &TaskServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TaskServiceServer) CreateTask(ctx context.Context, in *v1.CreateTaskReq) (*v1.CreateTaskResp, error) {
	l := logic.NewCreateTaskLogic(ctx, s.svcCtx)
	return l.CreateTask(in)
}

func (s *TaskServiceServer) GetTask(ctx context.Context, in *v1.GetTaskReq) (*v1.GetTaskResp, error) {
	l := logic.NewGetTaskLogic(ctx, s.svcCtx)
	return l.GetTask(in)
}

func (s *TaskServiceServer) UpdateTask(ctx context.Context, in *v1.UpdateTaskReq) (*v1.UpdateTaskResp, error) {
	l := logic.NewUpdateTaskLogic(ctx, s.svcCtx)
	return l.UpdateTask(in)
}

func (s *TaskServiceServer) ListTasks(ctx context.Context, in *v1.ListTasksReq) (*v1.ListTasksResp, error) {
	l := logic.NewListTasksLogic(ctx, s.svcCtx)
	return l.ListTasks(in)
}

func (s *TaskServiceServer) ClaimTask(ctx context.Context, in *v1.ClaimTaskReq) (*v1.ClaimTaskResp, error) {
	l := logic.NewClaimTaskLogic(ctx, s.svcCtx)
	return l.ClaimTask(in)
}

func (s *TaskServiceServer) AbandonTask(ctx context.Context, in *v1.AbandonTaskReq) (*v1.AbandonTaskResp, error) {
	l := logic.NewAbandonTaskLogic(ctx, s.svcCtx)
	return l.AbandonTask(in)
}

func (s *TaskServiceServer) CompleteTask(ctx context.Context, in *v1.CompleteTaskReq) (*v1.CompleteTaskResp, error) {
	l := logic.NewCompleteTaskLogic(ctx, s.svcCtx)
	return l.CompleteTask(in)
}

func (s *TaskServiceServer) ExtendDeadline(ctx context.Context, in *v1.ExtendDeadlineReq) (*v1.ExtendDeadlineResp, error) {
	l := logic.NewExtendDeadlineLogic(ctx, s.svcCtx)
	return l.ExtendDeadline(in)
}
