// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	adoption "github.com/luyb177/meow-nook/service/gateway/internal/handler/adoption"
	auth "github.com/luyb177/meow-nook/service/gateway/internal/handler/auth"
	cats "github.com/luyb177/meow-nook/service/gateway/internal/handler/cats"
	posts "github.com/luyb177/meow-nook/service/gateway/internal/handler/posts"
	tasks "github.com/luyb177/meow-nook/service/gateway/internal/handler/tasks"
	user "github.com/luyb177/meow-nook/service/gateway/internal/handler/user"
	"github.com/luyb177/meow-nook/service/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: adoption.ListAdoptionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: adoption.GetAdoptionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/followup",
					Handler: adoption.ListFollowUpsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/followup",
					Handler: adoption.SubmitFollowUpHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/review",
					Handler: adoption.ReviewAdoptionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/apply",
					Handler: adoption.ApplyAdoptionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/adoption"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: cats.ListCatsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: cats.CreateCatHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: cats.GetCatHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: cats.UpdateCatHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: cats.DeleteCatHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/health",
					Handler: cats.ListHealthRecordsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/health",
					Handler: cats.AddHealthRecordHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/rescue",
					Handler: cats.ListRescueRecordsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/rescue",
					Handler: cats.AddRescueRecordHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/heatmap",
					Handler: cats.GetHeatmapHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/stats",
					Handler: cats.GetCatStatsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/cats"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: posts.ListPostsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: posts.CreatePostHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: posts.GetPostHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: posts.DeletePostHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/comments",
					Handler: posts.ListCommentsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/comments",
					Handler: posts.AddCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id/comments/:cid",
					Handler: posts.DeleteCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/favorite",
					Handler: posts.FavoritePostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/like",
					Handler: posts.LikePostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/report",
					Handler: posts.ReportPostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/unfavorite",
					Handler: posts.UnfavoritePostHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/unlike",
					Handler: posts.UnlikePostHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/posts"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: tasks.ListTasksHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: tasks.CreateTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: tasks.GetTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: tasks.UpdateTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/abandon",
					Handler: tasks.AbandonTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/claim",
					Handler: tasks.ClaimTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/complete",
					Handler: tasks.CompleteTaskHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/extend",
					Handler: tasks.ExtendDeadlineHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/tasks"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/feedback",
					Handler: user.SubmitFeedbackHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/info",
					Handler: user.UpdateUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: user.LogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/notifications",
					Handler: user.GetNotificationSettingsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/notifications",
					Handler: user.UpdateNotificationSettingsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/password",
					Handler: user.ChangePasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/points",
					Handler: user.GetPointsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/points/logs",
					Handler: user.ListPointLogsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/user"),
	)
}
