// Code generated by goctl. Safe to edit.
// goctl 1.10.1

package handler

import (
	"net/http"
	"time"

	httpmw "github.com/luyb177/meow-nook/common/middleware/http"
	adminhandler "github.com/luyb177/meow-nook/service/gateway/internal/handler/admin"
	authhandler "github.com/luyb177/meow-nook/service/gateway/internal/handler/auth"
	userhandler "github.com/luyb177/meow-nook/service/gateway/internal/handler/user"
	"github.com/luyb177/meow-nook/service/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	auth := httpmw.AuthMiddleware(serverCtx.JWTSecret)

	// ── 公开路由（无需鉴权）────────────────────────────────────────
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/test",
				Handler: authhandler.TestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/send_code",
				Handler: authhandler.SendVerificationCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/verify_code",
				Handler: authhandler.VerifyCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: authhandler.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: authhandler.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
		rest.WithTimeout(60000*time.Millisecond),
	)

	// ── 普通用户路由（需登录，role: user / volunteer / admin）──────
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: auth(userhandler.GetUserInfoHandler(serverCtx)),
			},
			{
				Method:  http.MethodGet,
				Path:    "/credit",
				Handler: auth(userhandler.GetCreditPointsHandler(serverCtx)),
			},
			{
				Method:  http.MethodPut,
				Path:    "/info",
				Handler: auth(userhandler.UpdateUserInfoHandler(serverCtx)),
			},
		},
		rest.WithPrefix("/api/v1/user"),
		rest.WithTimeout(30000*time.Millisecond),
	)

	// ── 管理员路由（需登录且 role == admin）──────────────────────
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/users/:userId/service_types",
				Handler: auth(httpmw.AdminMiddleware(adminhandler.UpdateUserServiceTypesHandler(serverCtx))),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
		rest.WithTimeout(30000*time.Millisecond),
	)
}
