// Code generated by goctl. Safe to edit.
// goctl 1.10.1

package handler

import (
	"net/http"
	"time"

	httpmw "github.com/luyb177/meow-nook/common/middleware/http"
	authhandler "github.com/luyb177/meow-nook/service/gateway/internal/handler/auth"
	"github.com/luyb177/meow-nook/service/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	auth := httpmw.AuthMiddleware(serverCtx.JWTSecret)

	// ── 公开路由（无需鉴权）────────────────────────────────────────
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/test",
				Handler: authhandler.TestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/send_code",
				Handler: authhandler.SendVerificationCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/verify_code",
				Handler: authhandler.VerifyCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: authhandler.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: authhandler.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
		rest.WithTimeout(60000*time.Millisecond),
	)

	// ── 普通用户路由（需登录，role: user / volunteer / admin）──────
	server.AddRoutes(
		[]rest.Route{
			// 示例：用户自身信息（后续业务接口挂在这里）
			// {
			// 	Method:  http.MethodGet,
			// 	Path:    "/info",
			// 	Handler: auth(userhandler.GetUserInfoHandler(serverCtx)),
			// },
		},
		rest.WithPrefix("/api/v1/user"),
		rest.WithTimeout(30000*time.Millisecond),
	)
	_ = auth // 避免 unused 编译错误，待业务路由接入后移除

	// ── 管理员路由（需登录且 role == admin）──────────────────────
	server.AddRoutes(
		[]rest.Route{
			// 示例：管理员接口（后续挂在这里）
			// {
			// 	Method:  http.MethodGet,
			// 	Path:    "/users",
			// 	Handler: auth(httpmw.AdminMiddleware(adminhandler.ListUsersHandler(serverCtx))),
			// },
		},
		rest.WithPrefix("/api/v1/admin"),
		rest.WithTimeout(30000*time.Millisecond),
	)
}
