// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: cat.proto

package catservice

import (
	"context"

	"github.com/luyb177/meow-nook/service/cat/pb/cat/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddHealthRecordReq    = v1.AddHealthRecordReq
	AddHealthRecordResp   = v1.AddHealthRecordResp
	AddRescueRecordReq    = v1.AddRescueRecordReq
	AddRescueRecordResp   = v1.AddRescueRecordResp
	CatInfo               = v1.CatInfo
	CreateCatReq          = v1.CreateCatReq
	CreateCatResp         = v1.CreateCatResp
	DeleteCatReq          = v1.DeleteCatReq
	DeleteCatResp         = v1.DeleteCatResp
	GetCatReq             = v1.GetCatReq
	GetCatResp            = v1.GetCatResp
	GetHeatmapReq         = v1.GetHeatmapReq
	GetHeatmapResp        = v1.GetHeatmapResp
	GetStatsReq           = v1.GetStatsReq
	GetStatsResp          = v1.GetStatsResp
	HealthRecord          = v1.HealthRecord
	HeatmapPoint          = v1.HeatmapPoint
	ListCatsReq           = v1.ListCatsReq
	ListCatsResp          = v1.ListCatsResp
	ListHealthRecordsReq  = v1.ListHealthRecordsReq
	ListHealthRecordsResp = v1.ListHealthRecordsResp
	ListRescueRecordsReq  = v1.ListRescueRecordsReq
	ListRescueRecordsResp = v1.ListRescueRecordsResp
	RescueRecord          = v1.RescueRecord
	UpdateCatReq          = v1.UpdateCatReq
	UpdateCatResp         = v1.UpdateCatResp

	CatService interface {
		// CRUD
		CreateCat(ctx context.Context, in *CreateCatReq, opts ...grpc.CallOption) (*CreateCatResp, error)
		GetCat(ctx context.Context, in *GetCatReq, opts ...grpc.CallOption) (*GetCatResp, error)
		UpdateCat(ctx context.Context, in *UpdateCatReq, opts ...grpc.CallOption) (*UpdateCatResp, error)
		DeleteCat(ctx context.Context, in *DeleteCatReq, opts ...grpc.CallOption) (*DeleteCatResp, error)
		ListCats(ctx context.Context, in *ListCatsReq, opts ...grpc.CallOption) (*ListCatsResp, error)
		// Rescue records
		AddRescueRecord(ctx context.Context, in *AddRescueRecordReq, opts ...grpc.CallOption) (*AddRescueRecordResp, error)
		ListRescueRecords(ctx context.Context, in *ListRescueRecordsReq, opts ...grpc.CallOption) (*ListRescueRecordsResp, error)
		// Health records
		AddHealthRecord(ctx context.Context, in *AddHealthRecordReq, opts ...grpc.CallOption) (*AddHealthRecordResp, error)
		ListHealthRecords(ctx context.Context, in *ListHealthRecordsReq, opts ...grpc.CallOption) (*ListHealthRecordsResp, error)
		// Stats & heatmap
		GetStats(ctx context.Context, in *GetStatsReq, opts ...grpc.CallOption) (*GetStatsResp, error)
		GetHeatmap(ctx context.Context, in *GetHeatmapReq, opts ...grpc.CallOption) (*GetHeatmapResp, error)
	}

	defaultCatService struct {
		cli zrpc.Client
	}
)

func NewCatService(cli zrpc.Client) CatService {
	return &defaultCatService{
		cli: cli,
	}
}

// CRUD
func (m *defaultCatService) CreateCat(ctx context.Context, in *CreateCatReq, opts ...grpc.CallOption) (*CreateCatResp, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.CreateCat(ctx, in, opts...)
}

func (m *defaultCatService) GetCat(ctx context.Context, in *GetCatReq, opts ...grpc.CallOption) (*GetCatResp, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.GetCat(ctx, in, opts...)
}

func (m *defaultCatService) UpdateCat(ctx context.Context, in *UpdateCatReq, opts ...grpc.CallOption) (*UpdateCatResp, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.UpdateCat(ctx, in, opts...)
}

func (m *defaultCatService) DeleteCat(ctx context.Context, in *DeleteCatReq, opts ...grpc.CallOption) (*DeleteCatResp, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.DeleteCat(ctx, in, opts...)
}

func (m *defaultCatService) ListCats(ctx context.Context, in *ListCatsReq, opts ...grpc.CallOption) (*ListCatsResp, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListCats(ctx, in, opts...)
}

// Rescue records
func (m *defaultCatService) AddRescueRecord(ctx context.Context, in *AddRescueRecordReq, opts ...grpc.CallOption) (*AddRescueRecordResp, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.AddRescueRecord(ctx, in, opts...)
}

func (m *defaultCatService) ListRescueRecords(ctx context.Context, in *ListRescueRecordsReq, opts ...grpc.CallOption) (*ListRescueRecordsResp, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListRescueRecords(ctx, in, opts...)
}

// Health records
func (m *defaultCatService) AddHealthRecord(ctx context.Context, in *AddHealthRecordReq, opts ...grpc.CallOption) (*AddHealthRecordResp, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.AddHealthRecord(ctx, in, opts...)
}

func (m *defaultCatService) ListHealthRecords(ctx context.Context, in *ListHealthRecordsReq, opts ...grpc.CallOption) (*ListHealthRecordsResp, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListHealthRecords(ctx, in, opts...)
}

// Stats & heatmap
func (m *defaultCatService) GetStats(ctx context.Context, in *GetStatsReq, opts ...grpc.CallOption) (*GetStatsResp, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.GetStats(ctx, in, opts...)
}

func (m *defaultCatService) GetHeatmap(ctx context.Context, in *GetHeatmapReq, opts ...grpc.CallOption) (*GetHeatmapResp, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.GetHeatmap(ctx, in, opts...)
}
