// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: cat.proto

package catservice

import (
	"context"

	"github.com/luyb177/meow-nook/service/cat/pb/cat/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AbandonCatTaskRequest               = v1.AbandonCatTaskRequest
	AbandonCatTaskResponse              = v1.AbandonCatTaskResponse
	ApplyAddMedicalRecordRequest        = v1.ApplyAddMedicalRecordRequest
	ApplyAddMedicalRecordResponse       = v1.ApplyAddMedicalRecordResponse
	ApplyAddRescueRecordRequest         = v1.ApplyAddRescueRecordRequest
	ApplyAddRescueRecordResponse        = v1.ApplyAddRescueRecordResponse
	ApplyCreateCatRequest               = v1.ApplyCreateCatRequest
	ApplyCreateCatResponse              = v1.ApplyCreateCatResponse
	ApplyCreateCatTaskRequest           = v1.ApplyCreateCatTaskRequest
	ApplyCreateCatTaskResponse          = v1.ApplyCreateCatTaskResponse
	ApplyUpdateCatInfoRequest           = v1.ApplyUpdateCatInfoRequest
	ApplyUpdateCatInfoResponse          = v1.ApplyUpdateCatInfoResponse
	ApproveCreateCatRequest             = v1.ApproveCreateCatRequest
	ApproveCreateCatResponse            = v1.ApproveCreateCatResponse
	ApproveCreateCatTaskRequest         = v1.ApproveCreateCatTaskRequest
	ApproveCreateCatTaskResponse        = v1.ApproveCreateCatTaskResponse
	ApproveMedicalRecordRequest         = v1.ApproveMedicalRecordRequest
	ApproveMedicalRecordResponse        = v1.ApproveMedicalRecordResponse
	ApproveUpdateCatInfoRequest         = v1.ApproveUpdateCatInfoRequest
	ApproveUpdateCatInfoResponse        = v1.ApproveUpdateCatInfoResponse
	CatItem                             = v1.CatItem
	CatTaskItem                         = v1.CatTaskItem
	ClaimCatTaskRequest                 = v1.ClaimCatTaskRequest
	ClaimCatTaskResponse                = v1.ClaimCatTaskResponse
	CreateCatApplyItem                  = v1.CreateCatApplyItem
	CreateCatTaskApplyItem              = v1.CreateCatTaskApplyItem
	CreateCatTaskRequest                = v1.CreateCatTaskRequest
	CreateCatTaskResponse               = v1.CreateCatTaskResponse
	GetCatDetailRequest                 = v1.GetCatDetailRequest
	GetCatDetailResponse                = v1.GetCatDetailResponse
	GetCreateCatApplyDetailRequest      = v1.GetCreateCatApplyDetailRequest
	GetCreateCatApplyDetailResponse     = v1.GetCreateCatApplyDetailResponse
	GetCreateCatTaskApplyDetailRequest  = v1.GetCreateCatTaskApplyDetailRequest
	GetCreateCatTaskApplyDetailResponse = v1.GetCreateCatTaskApplyDetailResponse
	GetMyCreateCatApplyDetailRequest    = v1.GetMyCreateCatApplyDetailRequest
	GetMyCreateCatApplyDetailResponse   = v1.GetMyCreateCatApplyDetailResponse
	GetMyUpdateCatApplyDetailRequest    = v1.GetMyUpdateCatApplyDetailRequest
	GetMyUpdateCatApplyDetailResponse   = v1.GetMyUpdateCatApplyDetailResponse
	GetUpdateCatApplyDetailRequest      = v1.GetUpdateCatApplyDetailRequest
	GetUpdateCatApplyDetailResponse     = v1.GetUpdateCatApplyDetailResponse
	ListCatTasksRequest                 = v1.ListCatTasksRequest
	ListCatTasksResponse                = v1.ListCatTasksResponse
	ListCatsRequest                     = v1.ListCatsRequest
	ListCatsResponse                    = v1.ListCatsResponse
	ListCreateCatApplyRequest           = v1.ListCreateCatApplyRequest
	ListCreateCatApplyResponse          = v1.ListCreateCatApplyResponse
	ListCreateCatTaskApplyRequest       = v1.ListCreateCatTaskApplyRequest
	ListCreateCatTaskApplyResponse      = v1.ListCreateCatTaskApplyResponse
	ListUpdateCatApplyRequest           = v1.ListUpdateCatApplyRequest
	ListUpdateCatApplyResponse          = v1.ListUpdateCatApplyResponse
	RejectCreateCatRequest              = v1.RejectCreateCatRequest
	RejectCreateCatResponse             = v1.RejectCreateCatResponse
	RejectCreateCatTaskRequest          = v1.RejectCreateCatTaskRequest
	RejectCreateCatTaskResponse         = v1.RejectCreateCatTaskResponse
	RejectMedicalRecordRequest          = v1.RejectMedicalRecordRequest
	RejectMedicalRecordResponse         = v1.RejectMedicalRecordResponse
	RejectUpdateCatInfoRequest          = v1.RejectUpdateCatInfoRequest
	RejectUpdateCatInfoResponse         = v1.RejectUpdateCatInfoResponse
	UpdateAdoptionStatusRequest         = v1.UpdateAdoptionStatusRequest
	UpdateAdoptionStatusResponse        = v1.UpdateAdoptionStatusResponse
	UpdateCatApplyItem                  = v1.UpdateCatApplyItem
	UpdateCatTaskStatusRequest          = v1.UpdateCatTaskStatusRequest
	UpdateCatTaskStatusResponse         = v1.UpdateCatTaskStatusResponse
	UploadTaskProgressRequest           = v1.UploadTaskProgressRequest
	UploadTaskProgressResponse          = v1.UploadTaskProgressResponse

	CatService interface {
		// 申请创建小猫档案
		ApplyCreateCat(ctx context.Context, in *ApplyCreateCatRequest, opts ...grpc.CallOption) (*ApplyCreateCatResponse, error)
		// 申请修改猫咪档案信息
		ApplyUpdateCatInfo(ctx context.Context, in *ApplyUpdateCatInfoRequest, opts ...grpc.CallOption) (*ApplyUpdateCatInfoResponse, error)
		// 查看自己提交的创建申请详情
		GetMyCreateCatApplyDetail(ctx context.Context, in *GetMyCreateCatApplyDetailRequest, opts ...grpc.CallOption) (*GetMyCreateCatApplyDetailResponse, error)
		// 查看自己提交的修改申请详情
		GetMyUpdateCatApplyDetail(ctx context.Context, in *GetMyUpdateCatApplyDetailRequest, opts ...grpc.CallOption) (*GetMyUpdateCatApplyDetailResponse, error)
		// 申请新增医疗记录
		ApplyAddMedicalRecord(ctx context.Context, in *ApplyAddMedicalRecordRequest, opts ...grpc.CallOption) (*ApplyAddMedicalRecordResponse, error)
		// 申请新增救助记录
		ApplyAddRescueRecord(ctx context.Context, in *ApplyAddRescueRecordRequest, opts ...grpc.CallOption) (*ApplyAddRescueRecordResponse, error)
		// 申请创建任务
		ApplyCreateCatTask(ctx context.Context, in *ApplyCreateCatTaskRequest, opts ...grpc.CallOption) (*ApplyCreateCatTaskResponse, error)
		// 申请认领任务
		ClaimCatTask(ctx context.Context, in *ClaimCatTaskRequest, opts ...grpc.CallOption) (*ClaimCatTaskResponse, error)
		// 申请放弃任务
		AbandonCatTask(ctx context.Context, in *AbandonCatTaskRequest, opts ...grpc.CallOption) (*AbandonCatTaskResponse, error)
		// 上传任务进度（图片/备注）
		UploadTaskProgress(ctx context.Context, in *UploadTaskProgressRequest, opts ...grpc.CallOption) (*UploadTaskProgressResponse, error)
		ApproveCreateCat(ctx context.Context, in *ApproveCreateCatRequest, opts ...grpc.CallOption) (*ApproveCreateCatResponse, error)
		RejectCreateCat(ctx context.Context, in *RejectCreateCatRequest, opts ...grpc.CallOption) (*RejectCreateCatResponse, error)
		GetCreateCatApplyDetail(ctx context.Context, in *GetCreateCatApplyDetailRequest, opts ...grpc.CallOption) (*GetCreateCatApplyDetailResponse, error)
		ListCreateCatApply(ctx context.Context, in *ListCreateCatApplyRequest, opts ...grpc.CallOption) (*ListCreateCatApplyResponse, error)
		ApproveUpdateCatInfo(ctx context.Context, in *ApproveUpdateCatInfoRequest, opts ...grpc.CallOption) (*ApproveUpdateCatInfoResponse, error)
		RejectUpdateCatInfo(ctx context.Context, in *RejectUpdateCatInfoRequest, opts ...grpc.CallOption) (*RejectUpdateCatInfoResponse, error)
		GetUpdateCatApplyDetail(ctx context.Context, in *GetUpdateCatApplyDetailRequest, opts ...grpc.CallOption) (*GetUpdateCatApplyDetailResponse, error)
		ListUpdateCatApply(ctx context.Context, in *ListUpdateCatApplyRequest, opts ...grpc.CallOption) (*ListUpdateCatApplyResponse, error)
		ApproveMedicalRecord(ctx context.Context, in *ApproveMedicalRecordRequest, opts ...grpc.CallOption) (*ApproveMedicalRecordResponse, error)
		RejectMedicalRecord(ctx context.Context, in *RejectMedicalRecordRequest, opts ...grpc.CallOption) (*RejectMedicalRecordResponse, error)
		// 管理员审核志愿者任务申请
		ApproveCreateCatTask(ctx context.Context, in *ApproveCreateCatTaskRequest, opts ...grpc.CallOption) (*ApproveCreateCatTaskResponse, error)
		RejectCreateCatTask(ctx context.Context, in *RejectCreateCatTaskRequest, opts ...grpc.CallOption) (*RejectCreateCatTaskResponse, error)
		GetCreateCatTaskApplyDetail(ctx context.Context, in *GetCreateCatTaskApplyDetailRequest, opts ...grpc.CallOption) (*GetCreateCatTaskApplyDetailResponse, error)
		ListCreateCatTaskApply(ctx context.Context, in *ListCreateCatTaskApplyRequest, opts ...grpc.CallOption) (*ListCreateCatTaskApplyResponse, error)
		// 管理员直接创建正式任务（无需审核）
		CreateCatTask(ctx context.Context, in *CreateCatTaskRequest, opts ...grpc.CallOption) (*CreateCatTaskResponse, error)
		// 管理员更新任务状态
		UpdateCatTaskStatus(ctx context.Context, in *UpdateCatTaskStatusRequest, opts ...grpc.CallOption) (*UpdateCatTaskStatusResponse, error)
		UpdateAdoptionStatus(ctx context.Context, in *UpdateAdoptionStatusRequest, opts ...grpc.CallOption) (*UpdateAdoptionStatusResponse, error)
		// 猫咪详情
		GetCatDetail(ctx context.Context, in *GetCatDetailRequest, opts ...grpc.CallOption) (*GetCatDetailResponse, error)
		// 猫咪列表
		ListCats(ctx context.Context, in *ListCatsRequest, opts ...grpc.CallOption) (*ListCatsResponse, error)
		// 正式任务列表
		ListCatTasks(ctx context.Context, in *ListCatTasksRequest, opts ...grpc.CallOption) (*ListCatTasksResponse, error)
	}

	defaultCatService struct {
		cli zrpc.Client
	}
)

func NewCatService(cli zrpc.Client) CatService {
	return &defaultCatService{
		cli: cli,
	}
}

// 申请创建小猫档案
func (m *defaultCatService) ApplyCreateCat(ctx context.Context, in *ApplyCreateCatRequest, opts ...grpc.CallOption) (*ApplyCreateCatResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ApplyCreateCat(ctx, in, opts...)
}

// 申请修改猫咪档案信息
func (m *defaultCatService) ApplyUpdateCatInfo(ctx context.Context, in *ApplyUpdateCatInfoRequest, opts ...grpc.CallOption) (*ApplyUpdateCatInfoResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ApplyUpdateCatInfo(ctx, in, opts...)
}

// 查看自己提交的创建申请详情
func (m *defaultCatService) GetMyCreateCatApplyDetail(ctx context.Context, in *GetMyCreateCatApplyDetailRequest, opts ...grpc.CallOption) (*GetMyCreateCatApplyDetailResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.GetMyCreateCatApplyDetail(ctx, in, opts...)
}

// 查看自己提交的修改申请详情
func (m *defaultCatService) GetMyUpdateCatApplyDetail(ctx context.Context, in *GetMyUpdateCatApplyDetailRequest, opts ...grpc.CallOption) (*GetMyUpdateCatApplyDetailResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.GetMyUpdateCatApplyDetail(ctx, in, opts...)
}

// 申请新增医疗记录
func (m *defaultCatService) ApplyAddMedicalRecord(ctx context.Context, in *ApplyAddMedicalRecordRequest, opts ...grpc.CallOption) (*ApplyAddMedicalRecordResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ApplyAddMedicalRecord(ctx, in, opts...)
}

// 申请新增救助记录
func (m *defaultCatService) ApplyAddRescueRecord(ctx context.Context, in *ApplyAddRescueRecordRequest, opts ...grpc.CallOption) (*ApplyAddRescueRecordResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ApplyAddRescueRecord(ctx, in, opts...)
}

// 申请创建任务
func (m *defaultCatService) ApplyCreateCatTask(ctx context.Context, in *ApplyCreateCatTaskRequest, opts ...grpc.CallOption) (*ApplyCreateCatTaskResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ApplyCreateCatTask(ctx, in, opts...)
}

// 申请认领任务
func (m *defaultCatService) ClaimCatTask(ctx context.Context, in *ClaimCatTaskRequest, opts ...grpc.CallOption) (*ClaimCatTaskResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ClaimCatTask(ctx, in, opts...)
}

// 申请放弃任务
func (m *defaultCatService) AbandonCatTask(ctx context.Context, in *AbandonCatTaskRequest, opts ...grpc.CallOption) (*AbandonCatTaskResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.AbandonCatTask(ctx, in, opts...)
}

// 上传任务进度（图片/备注）
func (m *defaultCatService) UploadTaskProgress(ctx context.Context, in *UploadTaskProgressRequest, opts ...grpc.CallOption) (*UploadTaskProgressResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.UploadTaskProgress(ctx, in, opts...)
}

func (m *defaultCatService) ApproveCreateCat(ctx context.Context, in *ApproveCreateCatRequest, opts ...grpc.CallOption) (*ApproveCreateCatResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ApproveCreateCat(ctx, in, opts...)
}

func (m *defaultCatService) RejectCreateCat(ctx context.Context, in *RejectCreateCatRequest, opts ...grpc.CallOption) (*RejectCreateCatResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.RejectCreateCat(ctx, in, opts...)
}

func (m *defaultCatService) GetCreateCatApplyDetail(ctx context.Context, in *GetCreateCatApplyDetailRequest, opts ...grpc.CallOption) (*GetCreateCatApplyDetailResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.GetCreateCatApplyDetail(ctx, in, opts...)
}

func (m *defaultCatService) ListCreateCatApply(ctx context.Context, in *ListCreateCatApplyRequest, opts ...grpc.CallOption) (*ListCreateCatApplyResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListCreateCatApply(ctx, in, opts...)
}

func (m *defaultCatService) ApproveUpdateCatInfo(ctx context.Context, in *ApproveUpdateCatInfoRequest, opts ...grpc.CallOption) (*ApproveUpdateCatInfoResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ApproveUpdateCatInfo(ctx, in, opts...)
}

func (m *defaultCatService) RejectUpdateCatInfo(ctx context.Context, in *RejectUpdateCatInfoRequest, opts ...grpc.CallOption) (*RejectUpdateCatInfoResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.RejectUpdateCatInfo(ctx, in, opts...)
}

func (m *defaultCatService) GetUpdateCatApplyDetail(ctx context.Context, in *GetUpdateCatApplyDetailRequest, opts ...grpc.CallOption) (*GetUpdateCatApplyDetailResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.GetUpdateCatApplyDetail(ctx, in, opts...)
}

func (m *defaultCatService) ListUpdateCatApply(ctx context.Context, in *ListUpdateCatApplyRequest, opts ...grpc.CallOption) (*ListUpdateCatApplyResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListUpdateCatApply(ctx, in, opts...)
}

func (m *defaultCatService) ApproveMedicalRecord(ctx context.Context, in *ApproveMedicalRecordRequest, opts ...grpc.CallOption) (*ApproveMedicalRecordResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ApproveMedicalRecord(ctx, in, opts...)
}

func (m *defaultCatService) RejectMedicalRecord(ctx context.Context, in *RejectMedicalRecordRequest, opts ...grpc.CallOption) (*RejectMedicalRecordResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.RejectMedicalRecord(ctx, in, opts...)
}

// 管理员审核志愿者任务申请
func (m *defaultCatService) ApproveCreateCatTask(ctx context.Context, in *ApproveCreateCatTaskRequest, opts ...grpc.CallOption) (*ApproveCreateCatTaskResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ApproveCreateCatTask(ctx, in, opts...)
}

func (m *defaultCatService) RejectCreateCatTask(ctx context.Context, in *RejectCreateCatTaskRequest, opts ...grpc.CallOption) (*RejectCreateCatTaskResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.RejectCreateCatTask(ctx, in, opts...)
}

func (m *defaultCatService) GetCreateCatTaskApplyDetail(ctx context.Context, in *GetCreateCatTaskApplyDetailRequest, opts ...grpc.CallOption) (*GetCreateCatTaskApplyDetailResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.GetCreateCatTaskApplyDetail(ctx, in, opts...)
}

func (m *defaultCatService) ListCreateCatTaskApply(ctx context.Context, in *ListCreateCatTaskApplyRequest, opts ...grpc.CallOption) (*ListCreateCatTaskApplyResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListCreateCatTaskApply(ctx, in, opts...)
}

// 管理员直接创建正式任务（无需审核）
func (m *defaultCatService) CreateCatTask(ctx context.Context, in *CreateCatTaskRequest, opts ...grpc.CallOption) (*CreateCatTaskResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.CreateCatTask(ctx, in, opts...)
}

// 管理员更新任务状态
func (m *defaultCatService) UpdateCatTaskStatus(ctx context.Context, in *UpdateCatTaskStatusRequest, opts ...grpc.CallOption) (*UpdateCatTaskStatusResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.UpdateCatTaskStatus(ctx, in, opts...)
}

func (m *defaultCatService) UpdateAdoptionStatus(ctx context.Context, in *UpdateAdoptionStatusRequest, opts ...grpc.CallOption) (*UpdateAdoptionStatusResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.UpdateAdoptionStatus(ctx, in, opts...)
}

// 猫咪详情
func (m *defaultCatService) GetCatDetail(ctx context.Context, in *GetCatDetailRequest, opts ...grpc.CallOption) (*GetCatDetailResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.GetCatDetail(ctx, in, opts...)
}

// 猫咪列表
func (m *defaultCatService) ListCats(ctx context.Context, in *ListCatsRequest, opts ...grpc.CallOption) (*ListCatsResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListCats(ctx, in, opts...)
}

// 正式任务列表
func (m *defaultCatService) ListCatTasks(ctx context.Context, in *ListCatTasksRequest, opts ...grpc.CallOption) (*ListCatTasksResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListCatTasks(ctx, in, opts...)
}
