// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: cat.proto

package catservice

import (
	"context"

	"github.com/luyb177/meow-nook/service/cat/pb/cat/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AbandonTaskRequest                   = v1.AbandonTaskRequest
	AbandonTaskResponse                  = v1.AbandonTaskResponse
	AdoptApplicationVO                   = v1.AdoptApplicationVO
	AdoptApplyItemVO                     = v1.AdoptApplyItemVO
	AdoptionItemVO                       = v1.AdoptionItemVO
	AdoptionVO                           = v1.AdoptionVO
	ApplyAdoptRequest                    = v1.ApplyAdoptRequest
	ApplyAdoptResponse                   = v1.ApplyAdoptResponse
	ApplyCreateCatRequest                = v1.ApplyCreateCatRequest
	ApplyCreateCatResponse               = v1.ApplyCreateCatResponse
	ApplyCreateTaskRequest               = v1.ApplyCreateTaskRequest
	ApplyCreateTaskResponse              = v1.ApplyCreateTaskResponse
	ApproveAdoptRequest                  = v1.ApproveAdoptRequest
	ApproveAdoptResponse                 = v1.ApproveAdoptResponse
	ApproveCreateCatRequest              = v1.ApproveCreateCatRequest
	ApproveCreateCatResponse             = v1.ApproveCreateCatResponse
	ApproveTaskApplyRequest              = v1.ApproveTaskApplyRequest
	ApproveTaskApplyResponse             = v1.ApproveTaskApplyResponse
	CancelAdoptApplyRequest              = v1.CancelAdoptApplyRequest
	CancelAdoptApplyResponse             = v1.CancelAdoptApplyResponse
	CancelApplyCreateCatRequest          = v1.CancelApplyCreateCatRequest
	CancelTaskApplyRequest               = v1.CancelTaskApplyRequest
	CancelTaskApplyResponse              = v1.CancelTaskApplyResponse
	CancelTaskRequest                    = v1.CancelTaskRequest
	CancelTaskResponse                   = v1.CancelTaskResponse
	CatBriefVO                           = v1.CatBriefVO
	CatInfo                              = v1.CatInfo
	ClaimItemVO                          = v1.ClaimItemVO
	ClaimTaskRequest                     = v1.ClaimTaskRequest
	ClaimTaskResponse                    = v1.ClaimTaskResponse
	CompleteTaskRequest                  = v1.CompleteTaskRequest
	CompleteTaskResponse                 = v1.CompleteTaskResponse
	CreateAdoptionRequest                = v1.CreateAdoptionRequest
	CreateAdoptionResponse               = v1.CreateAdoptionResponse
	DirectAdoptRequest                   = v1.DirectAdoptRequest
	DirectAdoptResponse                  = v1.DirectAdoptResponse
	DirectCreateCatRequest               = v1.DirectCreateCatRequest
	DirectCreateCatResponse              = v1.DirectCreateCatResponse
	DirectCreateTaskRequest              = v1.DirectCreateTaskRequest
	DirectCreateTaskResponse             = v1.DirectCreateTaskResponse
	EscalateTaskUrgencyRequest           = v1.EscalateTaskUrgencyRequest
	EscalateTaskUrgencyResponse          = v1.EscalateTaskUrgencyResponse
	GetAdoptApplyDetailRequest           = v1.GetAdoptApplyDetailRequest
	GetAdoptApplyDetailResponse          = v1.GetAdoptApplyDetailResponse
	GetAdoptionDetailRequest             = v1.GetAdoptionDetailRequest
	GetAdoptionDetailResponse            = v1.GetAdoptionDetailResponse
	GetApplyDetailRequest                = v1.GetApplyDetailRequest
	GetApplyDetailResponse               = v1.GetApplyDetailResponse
	GetTaskApplyDetailRequest            = v1.GetTaskApplyDetailRequest
	GetTaskApplyDetailResponse           = v1.GetTaskApplyDetailResponse
	GetTaskDetailRequest                 = v1.GetTaskDetailRequest
	GetTaskDetailResponse                = v1.GetTaskDetailResponse
	GetTaskFlowsRequest                  = v1.GetTaskFlowsRequest
	GetTaskFlowsResponse                 = v1.GetTaskFlowsResponse
	GetTaskLogsRequest                   = v1.GetTaskLogsRequest
	GetTaskLogsResponse                  = v1.GetTaskLogsResponse
	ImageItem                            = v1.ImageItem
	ListAdoptionsRequest                 = v1.ListAdoptionsRequest
	ListAdoptionsResponse                = v1.ListAdoptionsResponse
	ListCatsReq                          = v1.ListCatsReq
	ListCatsResp                         = v1.ListCatsResp
	ListMyAdoptAppliesRequest            = v1.ListMyAdoptAppliesRequest
	ListMyAdoptAppliesResponse           = v1.ListMyAdoptAppliesResponse
	ListMyAdoptionsRequest               = v1.ListMyAdoptionsRequest
	ListMyAppliesRequest                 = v1.ListMyAppliesRequest
	ListMyAppliesResponse                = v1.ListMyAppliesResponse
	ListMyAppliesResponse_ApplyItem      = v1.ListMyAppliesResponse_ApplyItem
	ListMyClaimedTasksRequest            = v1.ListMyClaimedTasksRequest
	ListMyClaimedTasksResponse           = v1.ListMyClaimedTasksResponse
	ListMyCompletedTasksRequest          = v1.ListMyCompletedTasksRequest
	ListMyCompletedTasksResponse         = v1.ListMyCompletedTasksResponse
	ListMyTaskAppliesRequest             = v1.ListMyTaskAppliesRequest
	ListMyTaskAppliesResponse            = v1.ListMyTaskAppliesResponse
	ListPendingAdoptAppliesRequest       = v1.ListPendingAdoptAppliesRequest
	ListPendingAdoptAppliesResponse      = v1.ListPendingAdoptAppliesResponse
	ListPendingAppliesRequest            = v1.ListPendingAppliesRequest
	ListPendingAppliesResponse           = v1.ListPendingAppliesResponse
	ListPendingAppliesResponse_ApplyItem = v1.ListPendingAppliesResponse_ApplyItem
	ListPendingTaskAppliesRequest        = v1.ListPendingTaskAppliesRequest
	ListPendingTaskAppliesResponse       = v1.ListPendingTaskAppliesResponse
	ListTasksRequest                     = v1.ListTasksRequest
	ListTasksResponse                    = v1.ListTasksResponse
	NearbyFilter                         = v1.NearbyFilter
	PendingApplyVO                       = v1.PendingApplyVO
	RecordFollowUpVisitRequest           = v1.RecordFollowUpVisitRequest
	RecordFollowUpVisitResponse          = v1.RecordFollowUpVisitResponse
	RecordHomeVisitRequest               = v1.RecordHomeVisitRequest
	RecordHomeVisitResponse              = v1.RecordHomeVisitResponse
	RejectAdoptRequest                   = v1.RejectAdoptRequest
	RejectAdoptResponse                  = v1.RejectAdoptResponse
	RejectCreateCatRequest               = v1.RejectCreateCatRequest
	RejectTaskApplyRequest               = v1.RejectTaskApplyRequest
	RejectTaskApplyResponse              = v1.RejectTaskApplyResponse
	Response                             = v1.Response
	TagVO                                = v1.TagVO
	TaskApplyItemVO                      = v1.TaskApplyItemVO
	TaskApplyVO                          = v1.TaskApplyVO
	TaskFlowVO                           = v1.TaskFlowVO
	TaskItemVO                           = v1.TaskItemVO
	TaskLogVO                            = v1.TaskLogVO
	TaskVO                               = v1.TaskVO
	UpdateAdoptionRequest                = v1.UpdateAdoptionRequest
	UpdateAdoptionResponse               = v1.UpdateAdoptionResponse
	UpdateReturnStatusRequest            = v1.UpdateReturnStatusRequest
	UpdateReturnStatusResponse           = v1.UpdateReturnStatusResponse
	UpdateTaskRequest                    = v1.UpdateTaskRequest
	UpdateTaskResponse                   = v1.UpdateTaskResponse
	UserBriefVO                          = v1.UserBriefVO

	CatService interface {
		// 志愿者
		ApplyCreateCat(ctx context.Context, in *ApplyCreateCatRequest, opts ...grpc.CallOption) (*ApplyCreateCatResponse, error)
		CancelApplyCreateCat(ctx context.Context, in *CancelApplyCreateCatRequest, opts ...grpc.CallOption) (*Response, error)
		GetApplyDetail(ctx context.Context, in *GetApplyDetailRequest, opts ...grpc.CallOption) (*GetApplyDetailResponse, error)
		ListMyApplies(ctx context.Context, in *ListMyAppliesRequest, opts ...grpc.CallOption) (*ListMyAppliesResponse, error)
		// 管理员
		ApproveCreateCat(ctx context.Context, in *ApproveCreateCatRequest, opts ...grpc.CallOption) (*ApproveCreateCatResponse, error)
		RejectCreateCat(ctx context.Context, in *RejectCreateCatRequest, opts ...grpc.CallOption) (*Response, error)
		DirectCreateCat(ctx context.Context, in *DirectCreateCatRequest, opts ...grpc.CallOption) (*DirectCreateCatResponse, error)
		ListPendingApplies(ctx context.Context, in *ListPendingAppliesRequest, opts ...grpc.CallOption) (*ListPendingAppliesResponse, error)
		ListCats(ctx context.Context, in *ListCatsReq, opts ...grpc.CallOption) (*ListCatsResp, error)
		// 申请领养
		ApplyAdopt(ctx context.Context, in *ApplyAdoptRequest, opts ...grpc.CallOption) (*ApplyAdoptResponse, error)
		// 取消申请
		CancelAdoptApply(ctx context.Context, in *CancelAdoptApplyRequest, opts ...grpc.CallOption) (*CancelAdoptApplyResponse, error)
		// 查看申请详情
		GetAdoptApplyDetail(ctx context.Context, in *GetAdoptApplyDetailRequest, opts ...grpc.CallOption) (*GetAdoptApplyDetailResponse, error)
		// 我的申请列表
		ListMyAdoptApplies(ctx context.Context, in *ListMyAdoptAppliesRequest, opts ...grpc.CallOption) (*ListMyAdoptAppliesResponse, error)
		// 我的领养记录
		ListMyAdoptions(ctx context.Context, in *ListMyAdoptionsRequest, opts ...grpc.CallOption) (*ListAdoptionsResponse, error)
		// 完成回访
		CompleteVisit(ctx context.Context, in *RecordFollowUpVisitRequest, opts ...grpc.CallOption) (*RecordFollowUpVisitResponse, error)
		// 审核通过
		ApproveAdopt(ctx context.Context, in *ApproveAdoptRequest, opts ...grpc.CallOption) (*ApproveAdoptResponse, error)
		// 审核拒绝
		RejectAdopt(ctx context.Context, in *RejectAdoptRequest, opts ...grpc.CallOption) (*RejectAdoptResponse, error)
		// 待审核列表
		ListPendingAdoptApplies(ctx context.Context, in *ListPendingAdoptAppliesRequest, opts ...grpc.CallOption) (*ListPendingAdoptAppliesResponse, error)
		// 从申请创建领养记录
		CreateAdoption(ctx context.Context, in *CreateAdoptionRequest, opts ...grpc.CallOption) (*CreateAdoptionResponse, error)
		// 直接领养
		DirectAdopt(ctx context.Context, in *DirectAdoptRequest, opts ...grpc.CallOption) (*DirectAdoptResponse, error)
		// 查看领养详情
		GetAdoptionDetail(ctx context.Context, in *GetAdoptionDetailRequest, opts ...grpc.CallOption) (*GetAdoptionDetailResponse, error)
		// 领养记录列表
		ListAdoptions(ctx context.Context, in *ListAdoptionsRequest, opts ...grpc.CallOption) (*ListAdoptionsResponse, error)
		// 更新领养信息
		UpdateAdoption(ctx context.Context, in *UpdateAdoptionRequest, opts ...grpc.CallOption) (*UpdateAdoptionResponse, error)
		// 记录家访
		RecordHomeVisit(ctx context.Context, in *RecordHomeVisitRequest, opts ...grpc.CallOption) (*RecordHomeVisitResponse, error)
		// 记录回访
		RecordFollowUpVisit(ctx context.Context, in *RecordFollowUpVisitRequest, opts ...grpc.CallOption) (*RecordFollowUpVisitResponse, error)
		// 更新退回状态
		UpdateReturnStatus(ctx context.Context, in *UpdateReturnStatusRequest, opts ...grpc.CallOption) (*UpdateReturnStatusResponse, error)
		// 申请创建任务
		ApplyCreateTask(ctx context.Context, in *ApplyCreateTaskRequest, opts ...grpc.CallOption) (*ApplyCreateTaskResponse, error)
		// 取消任务申请
		CancelTaskApply(ctx context.Context, in *CancelTaskApplyRequest, opts ...grpc.CallOption) (*CancelTaskApplyResponse, error)
		// 查看任务申请详情
		GetTaskApplyDetail(ctx context.Context, in *GetTaskApplyDetailRequest, opts ...grpc.CallOption) (*GetTaskApplyDetailResponse, error)
		// 我的任务申请列表
		ListMyTaskApplies(ctx context.Context, in *ListMyTaskAppliesRequest, opts ...grpc.CallOption) (*ListMyTaskAppliesResponse, error)
		// 认领任务
		ClaimTask(ctx context.Context, in *ClaimTaskRequest, opts ...grpc.CallOption) (*ClaimTaskResponse, error)
		// 放弃任务
		AbandonTask(ctx context.Context, in *AbandonTaskRequest, opts ...grpc.CallOption) (*AbandonTaskResponse, error)
		// 完成任务
		CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*CompleteTaskResponse, error)
		// 查看任务详情
		GetTaskDetail(ctx context.Context, in *GetTaskDetailRequest, opts ...grpc.CallOption) (*GetTaskDetailResponse, error)
		// 任务列表（公开查询）
		ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
		// 我认领的任务列表
		ListMyClaimedTasks(ctx context.Context, in *ListMyClaimedTasksRequest, opts ...grpc.CallOption) (*ListMyClaimedTasksResponse, error)
		// 我完成的任务列表
		ListMyCompletedTasks(ctx context.Context, in *ListMyCompletedTasksRequest, opts ...grpc.CallOption) (*ListMyCompletedTasksResponse, error)
		// 审核通过任务申请
		ApproveTaskApply(ctx context.Context, in *ApproveTaskApplyRequest, opts ...grpc.CallOption) (*ApproveTaskApplyResponse, error)
		// 拒绝任务申请
		RejectTaskApply(ctx context.Context, in *RejectTaskApplyRequest, opts ...grpc.CallOption) (*RejectTaskApplyResponse, error)
		// 待审核任务申请列表
		ListPendingTaskApplies(ctx context.Context, in *ListPendingTaskAppliesRequest, opts ...grpc.CallOption) (*ListPendingTaskAppliesResponse, error)
		// 直接创建任务（跳过申请）
		DirectCreateTask(ctx context.Context, in *DirectCreateTaskRequest, opts ...grpc.CallOption) (*DirectCreateTaskResponse, error)
		// 更新任务
		UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error)
		// 取消任务
		CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
		// 升级任务紧急度
		EscalateTaskUrgency(ctx context.Context, in *EscalateTaskUrgencyRequest, opts ...grpc.CallOption) (*EscalateTaskUrgencyResponse, error)
		// 查看任务流转日志
		GetTaskFlows(ctx context.Context, in *GetTaskFlowsRequest, opts ...grpc.CallOption) (*GetTaskFlowsResponse, error)
		// 查看任务操作日志
		GetTaskLogs(ctx context.Context, in *GetTaskLogsRequest, opts ...grpc.CallOption) (*GetTaskLogsResponse, error)
	}

	defaultCatService struct {
		cli zrpc.Client
	}
)

func NewCatService(cli zrpc.Client) CatService {
	return &defaultCatService{
		cli: cli,
	}
}

// 志愿者
func (m *defaultCatService) ApplyCreateCat(ctx context.Context, in *ApplyCreateCatRequest, opts ...grpc.CallOption) (*ApplyCreateCatResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ApplyCreateCat(ctx, in, opts...)
}

func (m *defaultCatService) CancelApplyCreateCat(ctx context.Context, in *CancelApplyCreateCatRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.CancelApplyCreateCat(ctx, in, opts...)
}

func (m *defaultCatService) GetApplyDetail(ctx context.Context, in *GetApplyDetailRequest, opts ...grpc.CallOption) (*GetApplyDetailResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.GetApplyDetail(ctx, in, opts...)
}

func (m *defaultCatService) ListMyApplies(ctx context.Context, in *ListMyAppliesRequest, opts ...grpc.CallOption) (*ListMyAppliesResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListMyApplies(ctx, in, opts...)
}

// 管理员
func (m *defaultCatService) ApproveCreateCat(ctx context.Context, in *ApproveCreateCatRequest, opts ...grpc.CallOption) (*ApproveCreateCatResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ApproveCreateCat(ctx, in, opts...)
}

func (m *defaultCatService) RejectCreateCat(ctx context.Context, in *RejectCreateCatRequest, opts ...grpc.CallOption) (*Response, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.RejectCreateCat(ctx, in, opts...)
}

func (m *defaultCatService) DirectCreateCat(ctx context.Context, in *DirectCreateCatRequest, opts ...grpc.CallOption) (*DirectCreateCatResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.DirectCreateCat(ctx, in, opts...)
}

func (m *defaultCatService) ListPendingApplies(ctx context.Context, in *ListPendingAppliesRequest, opts ...grpc.CallOption) (*ListPendingAppliesResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListPendingApplies(ctx, in, opts...)
}

func (m *defaultCatService) ListCats(ctx context.Context, in *ListCatsReq, opts ...grpc.CallOption) (*ListCatsResp, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListCats(ctx, in, opts...)
}

// 申请领养
func (m *defaultCatService) ApplyAdopt(ctx context.Context, in *ApplyAdoptRequest, opts ...grpc.CallOption) (*ApplyAdoptResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ApplyAdopt(ctx, in, opts...)
}

// 取消申请
func (m *defaultCatService) CancelAdoptApply(ctx context.Context, in *CancelAdoptApplyRequest, opts ...grpc.CallOption) (*CancelAdoptApplyResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.CancelAdoptApply(ctx, in, opts...)
}

// 查看申请详情
func (m *defaultCatService) GetAdoptApplyDetail(ctx context.Context, in *GetAdoptApplyDetailRequest, opts ...grpc.CallOption) (*GetAdoptApplyDetailResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.GetAdoptApplyDetail(ctx, in, opts...)
}

// 我的申请列表
func (m *defaultCatService) ListMyAdoptApplies(ctx context.Context, in *ListMyAdoptAppliesRequest, opts ...grpc.CallOption) (*ListMyAdoptAppliesResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListMyAdoptApplies(ctx, in, opts...)
}

// 我的领养记录
func (m *defaultCatService) ListMyAdoptions(ctx context.Context, in *ListMyAdoptionsRequest, opts ...grpc.CallOption) (*ListAdoptionsResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListMyAdoptions(ctx, in, opts...)
}

// 完成回访
func (m *defaultCatService) CompleteVisit(ctx context.Context, in *RecordFollowUpVisitRequest, opts ...grpc.CallOption) (*RecordFollowUpVisitResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.CompleteVisit(ctx, in, opts...)
}

// 审核通过
func (m *defaultCatService) ApproveAdopt(ctx context.Context, in *ApproveAdoptRequest, opts ...grpc.CallOption) (*ApproveAdoptResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ApproveAdopt(ctx, in, opts...)
}

// 审核拒绝
func (m *defaultCatService) RejectAdopt(ctx context.Context, in *RejectAdoptRequest, opts ...grpc.CallOption) (*RejectAdoptResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.RejectAdopt(ctx, in, opts...)
}

// 待审核列表
func (m *defaultCatService) ListPendingAdoptApplies(ctx context.Context, in *ListPendingAdoptAppliesRequest, opts ...grpc.CallOption) (*ListPendingAdoptAppliesResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListPendingAdoptApplies(ctx, in, opts...)
}

// 从申请创建领养记录
func (m *defaultCatService) CreateAdoption(ctx context.Context, in *CreateAdoptionRequest, opts ...grpc.CallOption) (*CreateAdoptionResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.CreateAdoption(ctx, in, opts...)
}

// 直接领养
func (m *defaultCatService) DirectAdopt(ctx context.Context, in *DirectAdoptRequest, opts ...grpc.CallOption) (*DirectAdoptResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.DirectAdopt(ctx, in, opts...)
}

// 查看领养详情
func (m *defaultCatService) GetAdoptionDetail(ctx context.Context, in *GetAdoptionDetailRequest, opts ...grpc.CallOption) (*GetAdoptionDetailResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.GetAdoptionDetail(ctx, in, opts...)
}

// 领养记录列表
func (m *defaultCatService) ListAdoptions(ctx context.Context, in *ListAdoptionsRequest, opts ...grpc.CallOption) (*ListAdoptionsResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListAdoptions(ctx, in, opts...)
}

// 更新领养信息
func (m *defaultCatService) UpdateAdoption(ctx context.Context, in *UpdateAdoptionRequest, opts ...grpc.CallOption) (*UpdateAdoptionResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.UpdateAdoption(ctx, in, opts...)
}

// 记录家访
func (m *defaultCatService) RecordHomeVisit(ctx context.Context, in *RecordHomeVisitRequest, opts ...grpc.CallOption) (*RecordHomeVisitResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.RecordHomeVisit(ctx, in, opts...)
}

// 记录回访
func (m *defaultCatService) RecordFollowUpVisit(ctx context.Context, in *RecordFollowUpVisitRequest, opts ...grpc.CallOption) (*RecordFollowUpVisitResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.RecordFollowUpVisit(ctx, in, opts...)
}

// 更新退回状态
func (m *defaultCatService) UpdateReturnStatus(ctx context.Context, in *UpdateReturnStatusRequest, opts ...grpc.CallOption) (*UpdateReturnStatusResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.UpdateReturnStatus(ctx, in, opts...)
}

// 申请创建任务
func (m *defaultCatService) ApplyCreateTask(ctx context.Context, in *ApplyCreateTaskRequest, opts ...grpc.CallOption) (*ApplyCreateTaskResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ApplyCreateTask(ctx, in, opts...)
}

// 取消任务申请
func (m *defaultCatService) CancelTaskApply(ctx context.Context, in *CancelTaskApplyRequest, opts ...grpc.CallOption) (*CancelTaskApplyResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.CancelTaskApply(ctx, in, opts...)
}

// 查看任务申请详情
func (m *defaultCatService) GetTaskApplyDetail(ctx context.Context, in *GetTaskApplyDetailRequest, opts ...grpc.CallOption) (*GetTaskApplyDetailResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.GetTaskApplyDetail(ctx, in, opts...)
}

// 我的任务申请列表
func (m *defaultCatService) ListMyTaskApplies(ctx context.Context, in *ListMyTaskAppliesRequest, opts ...grpc.CallOption) (*ListMyTaskAppliesResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListMyTaskApplies(ctx, in, opts...)
}

// 认领任务
func (m *defaultCatService) ClaimTask(ctx context.Context, in *ClaimTaskRequest, opts ...grpc.CallOption) (*ClaimTaskResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ClaimTask(ctx, in, opts...)
}

// 放弃任务
func (m *defaultCatService) AbandonTask(ctx context.Context, in *AbandonTaskRequest, opts ...grpc.CallOption) (*AbandonTaskResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.AbandonTask(ctx, in, opts...)
}

// 完成任务
func (m *defaultCatService) CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*CompleteTaskResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.CompleteTask(ctx, in, opts...)
}

// 查看任务详情
func (m *defaultCatService) GetTaskDetail(ctx context.Context, in *GetTaskDetailRequest, opts ...grpc.CallOption) (*GetTaskDetailResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.GetTaskDetail(ctx, in, opts...)
}

// 任务列表（公开查询）
func (m *defaultCatService) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListTasks(ctx, in, opts...)
}

// 我认领的任务列表
func (m *defaultCatService) ListMyClaimedTasks(ctx context.Context, in *ListMyClaimedTasksRequest, opts ...grpc.CallOption) (*ListMyClaimedTasksResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListMyClaimedTasks(ctx, in, opts...)
}

// 我完成的任务列表
func (m *defaultCatService) ListMyCompletedTasks(ctx context.Context, in *ListMyCompletedTasksRequest, opts ...grpc.CallOption) (*ListMyCompletedTasksResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListMyCompletedTasks(ctx, in, opts...)
}

// 审核通过任务申请
func (m *defaultCatService) ApproveTaskApply(ctx context.Context, in *ApproveTaskApplyRequest, opts ...grpc.CallOption) (*ApproveTaskApplyResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ApproveTaskApply(ctx, in, opts...)
}

// 拒绝任务申请
func (m *defaultCatService) RejectTaskApply(ctx context.Context, in *RejectTaskApplyRequest, opts ...grpc.CallOption) (*RejectTaskApplyResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.RejectTaskApply(ctx, in, opts...)
}

// 待审核任务申请列表
func (m *defaultCatService) ListPendingTaskApplies(ctx context.Context, in *ListPendingTaskAppliesRequest, opts ...grpc.CallOption) (*ListPendingTaskAppliesResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.ListPendingTaskApplies(ctx, in, opts...)
}

// 直接创建任务（跳过申请）
func (m *defaultCatService) DirectCreateTask(ctx context.Context, in *DirectCreateTaskRequest, opts ...grpc.CallOption) (*DirectCreateTaskResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.DirectCreateTask(ctx, in, opts...)
}

// 更新任务
func (m *defaultCatService) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.UpdateTask(ctx, in, opts...)
}

// 取消任务
func (m *defaultCatService) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.CancelTask(ctx, in, opts...)
}

// 升级任务紧急度
func (m *defaultCatService) EscalateTaskUrgency(ctx context.Context, in *EscalateTaskUrgencyRequest, opts ...grpc.CallOption) (*EscalateTaskUrgencyResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.EscalateTaskUrgency(ctx, in, opts...)
}

// 查看任务流转日志
func (m *defaultCatService) GetTaskFlows(ctx context.Context, in *GetTaskFlowsRequest, opts ...grpc.CallOption) (*GetTaskFlowsResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.GetTaskFlows(ctx, in, opts...)
}

// 查看任务操作日志
func (m *defaultCatService) GetTaskLogs(ctx context.Context, in *GetTaskLogsRequest, opts ...grpc.CallOption) (*GetTaskLogsResponse, error) {
	client := v1.NewCatServiceClient(m.cli.Conn())
	return client.GetTaskLogs(ctx, in, opts...)
}
