// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: adoption.proto

package adoptionservice

import (
	"context"

	"github.com/luyb177/meow-nook/service/adoption/pb/adoption/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdoptionApplication   = v1.AdoptionApplication
	ApplyAdoptionReq      = v1.ApplyAdoptionReq
	ApplyAdoptionResp     = v1.ApplyAdoptionResp
	FollowUpRecord        = v1.FollowUpRecord
	GetApplicationReq     = v1.GetApplicationReq
	GetApplicationResp    = v1.GetApplicationResp
	ListApplicationsReq   = v1.ListApplicationsReq
	ListApplicationsResp  = v1.ListApplicationsResp
	ListFollowUpsReq      = v1.ListFollowUpsReq
	ListFollowUpsResp     = v1.ListFollowUpsResp
	ReviewApplicationReq  = v1.ReviewApplicationReq
	ReviewApplicationResp = v1.ReviewApplicationResp
	SubmitFollowUpReq     = v1.SubmitFollowUpReq
	SubmitFollowUpResp    = v1.SubmitFollowUpResp

	AdoptionService interface {
		ApplyAdoption(ctx context.Context, in *ApplyAdoptionReq, opts ...grpc.CallOption) (*ApplyAdoptionResp, error)
		ReviewApplication(ctx context.Context, in *ReviewApplicationReq, opts ...grpc.CallOption) (*ReviewApplicationResp, error)
		GetApplication(ctx context.Context, in *GetApplicationReq, opts ...grpc.CallOption) (*GetApplicationResp, error)
		ListApplications(ctx context.Context, in *ListApplicationsReq, opts ...grpc.CallOption) (*ListApplicationsResp, error)
		SubmitFollowUp(ctx context.Context, in *SubmitFollowUpReq, opts ...grpc.CallOption) (*SubmitFollowUpResp, error)
		ListFollowUps(ctx context.Context, in *ListFollowUpsReq, opts ...grpc.CallOption) (*ListFollowUpsResp, error)
	}

	defaultAdoptionService struct {
		cli zrpc.Client
	}
)

func NewAdoptionService(cli zrpc.Client) AdoptionService {
	return &defaultAdoptionService{
		cli: cli,
	}
}

func (m *defaultAdoptionService) ApplyAdoption(ctx context.Context, in *ApplyAdoptionReq, opts ...grpc.CallOption) (*ApplyAdoptionResp, error) {
	client := v1.NewAdoptionServiceClient(m.cli.Conn())
	return client.ApplyAdoption(ctx, in, opts...)
}

func (m *defaultAdoptionService) ReviewApplication(ctx context.Context, in *ReviewApplicationReq, opts ...grpc.CallOption) (*ReviewApplicationResp, error) {
	client := v1.NewAdoptionServiceClient(m.cli.Conn())
	return client.ReviewApplication(ctx, in, opts...)
}

func (m *defaultAdoptionService) GetApplication(ctx context.Context, in *GetApplicationReq, opts ...grpc.CallOption) (*GetApplicationResp, error) {
	client := v1.NewAdoptionServiceClient(m.cli.Conn())
	return client.GetApplication(ctx, in, opts...)
}

func (m *defaultAdoptionService) ListApplications(ctx context.Context, in *ListApplicationsReq, opts ...grpc.CallOption) (*ListApplicationsResp, error) {
	client := v1.NewAdoptionServiceClient(m.cli.Conn())
	return client.ListApplications(ctx, in, opts...)
}

func (m *defaultAdoptionService) SubmitFollowUp(ctx context.Context, in *SubmitFollowUpReq, opts ...grpc.CallOption) (*SubmitFollowUpResp, error) {
	client := v1.NewAdoptionServiceClient(m.cli.Conn())
	return client.SubmitFollowUp(ctx, in, opts...)
}

func (m *defaultAdoptionService) ListFollowUps(ctx context.Context, in *ListFollowUpsReq, opts ...grpc.CallOption) (*ListFollowUpsResp, error) {
	client := v1.NewAdoptionServiceClient(m.cli.Conn())
	return client.ListFollowUps(ctx, in, opts...)
}
