// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"github.com/luyb177/meow-nook/service/user/internal/logic"
	"github.com/luyb177/meow-nook/service/user/internal/svc"
	"github.com/luyb177/meow-nook/service/user/pb/user/v1"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// Auth
func (s *UserServiceServer) Register(ctx context.Context, in *v1.RegisterReq) (*v1.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServiceServer) Login(ctx context.Context, in *v1.LoginReq) (*v1.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServiceServer) Logout(ctx context.Context, in *v1.LogoutReq) (*v1.LogoutResp, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

// Profile
func (s *UserServiceServer) GetUserInfo(ctx context.Context, in *v1.GetUserInfoReq) (*v1.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserServiceServer) UpdateUserInfo(ctx context.Context, in *v1.UpdateUserInfoReq) (*v1.UpdateUserInfoResp, error) {
	l := logic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}

func (s *UserServiceServer) ChangePassword(ctx context.Context, in *v1.ChangePasswordReq) (*v1.ChangePasswordResp, error) {
	l := logic.NewChangePasswordLogic(ctx, s.svcCtx)
	return l.ChangePassword(in)
}

// Points
func (s *UserServiceServer) GetPoints(ctx context.Context, in *v1.GetPointsReq) (*v1.GetPointsResp, error) {
	l := logic.NewGetPointsLogic(ctx, s.svcCtx)
	return l.GetPoints(in)
}

func (s *UserServiceServer) AddPoints(ctx context.Context, in *v1.AddPointsReq) (*v1.AddPointsResp, error) {
	l := logic.NewAddPointsLogic(ctx, s.svcCtx)
	return l.AddPoints(in)
}

func (s *UserServiceServer) ListPointLogs(ctx context.Context, in *v1.ListPointLogsReq) (*v1.ListPointLogsResp, error) {
	l := logic.NewListPointLogsLogic(ctx, s.svcCtx)
	return l.ListPointLogs(in)
}

// Notifications
func (s *UserServiceServer) GetNotificationSettings(ctx context.Context, in *v1.GetNotificationSettingsReq) (*v1.GetNotificationSettingsResp, error) {
	l := logic.NewGetNotificationSettingsLogic(ctx, s.svcCtx)
	return l.GetNotificationSettings(in)
}

func (s *UserServiceServer) UpdateNotificationSettings(ctx context.Context, in *v1.UpdateNotificationSettingsReq) (*v1.UpdateNotificationSettingsResp, error) {
	l := logic.NewUpdateNotificationSettingsLogic(ctx, s.svcCtx)
	return l.UpdateNotificationSettings(in)
}

// Feedback
func (s *UserServiceServer) SubmitFeedback(ctx context.Context, in *v1.SubmitFeedbackReq) (*v1.SubmitFeedbackResp, error) {
	l := logic.NewSubmitFeedbackLogic(ctx, s.svcCtx)
	return l.SubmitFeedback(in)
}
