// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"github.com/luyb177/meow-nook/service/user/internal/logic"
	"github.com/luyb177/meow-nook/service/user/internal/svc"
	"github.com/luyb177/meow-nook/service/user/pb/user/v1"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// Auth
func (s *UserServiceServer) Test(ctx context.Context, in *v1.TestReq) (*v1.Response, error) {
	l := logic.NewTestLogic(ctx, s.svcCtx)
	return l.Test(in)
}

func (s *UserServiceServer) SendVerificationCode(ctx context.Context, in *v1.SendVerificationCodeReq) (*v1.Response, error) {
	l := logic.NewSendVerificationCodeLogic(ctx, s.svcCtx)
	return l.SendVerificationCode(in)
}
