// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Response struct {
}

type SendVerificationCodeReq struct {
	Target  string `json:"target"` // phone or email
	Channel int32  `json:"channel"`
	Purpose int32  `json:"purpose"`
}

type TestReq struct {
}

type TestResp struct {
}
