// Code generated by goctl. Safe to edit.
// goctl 1.10.1

package types

type Response struct{}

type SendVerificationCodeReq struct {
	Target  string `json:"target"` // phone or email
	Channel int32  `json:"channel"`
	Purpose int32  `json:"purpose"`
}

type VerifyCodeReq struct {
	Target  string `json:"target"`
	Channel int32  `json:"channel"`
	Purpose int32  `json:"purpose"`
	Code    string `json:"code"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterResp struct {
	UserId int64  `json:"userId"`
	Token  string `json:"token"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token  string `json:"token"`
	UserId int64  `json:"userId"`
}

type TestReq struct{}

type TestResp struct{}

type UserInfoResp struct {
	Id           int64    `json:"id"`
	Username     string   `json:"username"`
	Avatar       string   `json:"avatar"`
	Phone        string   `json:"phone"`
	Area         string   `json:"area"`
	Gender       string   `json:"gender"`
	Points       int32    `json:"points"`
	Role         string   `json:"role"`
	CreatedAt    int64    `json:"createdAt"`
	ServiceTypes []string `json:"serviceTypes"`
}

type CreditPointsResp struct {
	CreditPoints int32 `json:"creditPoints"`
}

type UpdateUserInfoReq struct {
	Username *string `json:"username,omitempty"`
	Avatar   *string `json:"avatar,omitempty"`
	Phone    *string `json:"phone,omitempty"`
	Area     *string `json:"area,omitempty"`
}

type AdminUpdateUserServiceTypesReq struct {
	UserId       int64    `path:"userId"`
	ServiceTypes []string `json:"serviceTypes"`
}
